### ISSUE TITLE
Mapsforge themes compatibility

### ISSUE THREAD

**Issue by stleusc** [mapsforge/vtm#100]
are there plans to support mapsforge theme format?

**Comment by devemux86** [comment]
It's not something trivial, as they are two different rendering engines, so some incompatibilities may exist.
Nevertheless it's already in my todo list for VTM. :smile: 

For question please use our forum:
https://groups.google.com/group/mapsforge-dev

**Comment by devemux86** [comment]
Mapsforge and VTM use different priority ordering. :slightly_frowning_face: 
In [Mapsforge](https://github.com/mapsforge/mapsforge/blob/master/docs/Rendertheme.md#priorities) higher priorities are drawn first (priority 1 wins priority 0).
In VTM lower priorities are drawn first (priority 0 wins priority 1).

**Comment by Longri** [comment]
Mapsforge and VTM use different zoom-levels. 
VTM zoom 9 = Mapsforge zoom 10

**Comment by devemux86** [comment]
> Mapsforge and VTM use different zoom-levels.

What do you mean?

If use same tile size (e.g. 512px) and exact same map position, we have the same map view.
i.e. in VTM use integer zoom, not double intermediate scales.

In #217 I explain in detail the zoom / scale in the two libs, specifically [here](https://github.com/mapsforge/vtm/issues/217#issuecomment-257947100).

**Mapsforge**
![mapsforge](https://user-images.githubusercontent.com/3484020/29571231-57a47508-8761-11e7-9eab-a26001eedefb.png)

**VTM**
![vtm](https://user-images.githubusercontent.com/3484020/29571241-5ee00134-8761-11e7-8efd-2edfff2982d0.png)

**Comment by Longri** [comment]
Look into theme-comparator/src/org/oscim/theme_comparator/BothMapPositionHandler.java
Line 54 
Only with different zoom we have the same representation. See on Mapscale!

**Comment by devemux86** [comment]
Have you set tile size [512px](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-awt/src/main/java/org/mapsforge/samples/awt/Samples.java#L161) in Mapsforge (default 256px) like in VTM (default 512px) ?

**Comment by devemux86** [comment]
I pushed the common tile size / zoom improvement in b110314077dd93999f685516cff74ed60970a7f1.

**Comment by devemux86** [comment]
Thanks to PR #388 by @Longri we now have Mapsforge theme compatibility!

See VTM rendering [OpenAndroMaps](https://www.openandromaps.org/en/) maps with [Elevate](https://www.openandromaps.org/en/legend/elevate-mountain-hike-theme) theme:
![opengl_openandromaps_elevate](https://user-images.githubusercontent.com/3484020/30004221-00c996ce-90d4-11e7-8e31-751da619a4ae.png)

**Comment by devemux86** [comment]
Don't know if need to support the [display](https://github.com/mapsforge/mapsforge/blob/master/docs/Rendertheme.md#display) directive, since VTM `LabelLayer` works already fine and differently than Mapsforge.

Also for any missing rules, would need first to implement them **separately** in VTM and then proceed with their Mapsforge support.

**Comment by devemux86** [comment]
After fixing #124, most needed functions are present and working.
So closing, any extra features can be checked in their own issues.

**Comment by devemux86** [comment]
OpenAndroMaps forum topic with feedback is [here](https://www.openandromaps.org/en/oam-forums/topic/vtm-mapsforge-openandromaps-themes-compatibility).

**Comment by devemux86** [comment]
I merged VTM + Mapsforge theme parsers for easier maintenance.
