### ISSUE TITLE
Line stipple / texture rendering problems

### ISSUE THREAD

**Issue by demiantres** [mapsforge/vtm#1005]
The commit "707e1c406984bb22567133cea426bf6519246a97" (https://github.com/mapsforge/vtm/commit/707e1c406984bb22567133cea426bf6519246a97)  introduces new rendering problems with OpenAndroMaps Elements/Elevate themes:

Before (I is ok, II is no ok):
![image](https://user-images.githubusercontent.com/5980561/211208455-c86fc30c-20d4-43b0-8d81-5d905a458db2.png)

after the patch (I is not ok, II is ok):
![image](https://user-images.githubusercontent.com/5980561/211208484-9c8c69e7-5268-48c6-b1ac-6b29f13c903c.png)

**Comment by devemux86** [comment]
Thanks for the report.
Please also write the theme rules that appear in the image and coordinates of the area.

Line textures did not work properly, see https://github.com/mapsforge/vtm/issues/983 and https://github.com/mapsforge/vtm/issues/985.
Now it's better with a new implementation, but there's always room for improvement. :slightly_smiling_face:

**Comment by demiantres** [comment]
The problem are the hardcoded "*8" values:
`b.stipple *= 8;
f *= 8;`

The screenshots show the OpenAndroMaps Austria map, with Elements style at 47.63082°, 15.69521°.

**Comment by demiantres** [comment]
When removing the "*8" factor then I is drawn correctly, but II is wrong again.

**Comment by devemux86** [comment]
Thanks for the details.

Mapsforge and VTM are different map engines and their themes are not fully compatible.
So some compromises are needed and the result should not be expected to be the same.

These values are active in the case of Mapsforge themes.
If there is a better way, we can certainly check it.

**Comment by demiantres** [comment]
What I don't understand is why the values have to multiplied by factor 8 for Mapsforge themes? The stipple size is defined in the theme's "stroke-dasharray" attribute, isn't it?

**Comment by devemux86** [comment]
Can you try absolute values, does it work with all Mapsforge theme rules and everywhere?

As they are different engines, value 2 in Mapsforge could need 4 in OpenGL (or vice versa),
trying to look "similar" and still not succeeding in the same rendering.

Rendering stipples in VTM themes seems to works properly (see the [VTM themes](https://github.com/mapsforge/vtm/tree/master/vtm-themes/resources/assets/vtm)).

Converting a Mapsforge theme into VTM engine is different, as a translation of another engine's rules is needed.
We still need to find the most compatible translation.

**Comment by demiantres** [comment]
Actually this code (starting with line 613 in XmlThemeBuilder.java) ignores the space length:
```
        if (b.dashArray != null) {
            // Stroke dash array
            if (b.dashArray.length == 2) {
                b.randomOffset = false;
                b.stipple = b.dashArray[0] < 1 ? 1 : (int) b.dashArray[0];
                if (mTheme.isMapsforgeTheme())
                    b.stipple *= 8;
                b.stippleWidth = 1;
                b.stippleColor = Color.TRANSPARENT;
                b.dashArray = null;
            } else {
```

It would only make sense if the check is `` if (b.dashArray.length == 1) ``?

**Comment by devemux86** [comment]
In the case of a 2-value dash array, it is better for rendering and performance to use stipples instead of textures.
(stipples can work with 2 values)

What is space length?

Odd number of dash array entries is duplicated, so 1 becomes 2.
We probably need to do the duplication of 1 before that `if` too.

**Comment by demiantres** [comment]
Sorry, I meant this with "space length": ``dashArray = [2, 10];`` means draw 2 pixels, 10 pixel spaces, draw 2 pixels, ...

>> In the case of a 2-value dash array, it is better for rendering and performance to use stipples instead of textures.
Yes, but the code does not do this but renders only dashes of size dashArray[0]?

For testing purposes I changed the check ``if (b.dashArray.length == 2)`` to ``if (b.dashArray.length == 1)`` and removed the ``*8`` factors. Actually this works exactly as intended. The problem is that the render themes (i.e. OpenAndroMaps Elevate) are optimized for the Mapsforge renderer (as you wrote) and the Mapsforge render seems to handle dashed lines incorrectly.

**Comment by devemux86** [comment]
> I meant this with "space length": dashArray = [2, 10]; means draw 2 pixels, 10 pixel spaces, draw 2 pixels, ...

Different values mean texture rendering instead of stipples.
Texture rendering is not visually good, so it is better to avoid it.

> The problem is that the render themes (i.e. OpenAndroMaps Elevate) are optimized for the Mapsforge renderer

Indeed and so far there is no easy solution to properly render Mapsforge / OpenAndroMaps / Freizeitkarte themes in VTM.

**Comment by demiantres** [comment]
Here are some results with my changes mentioned above (VTM):
![image](https://user-images.githubusercontent.com/5980561/211538004-43848057-d7e9-452a-8d95-344d4e620d90.png)

Mapsforge engine:
![image](https://user-images.githubusercontent.com/5980561/211538124-c7db3713-9729-46a3-a8d7-54d7b4f03201.png)

VTM engine with your patches:
![image](https://user-images.githubusercontent.com/5980561/211538289-6dd4d728-8466-4846-bf96-e14ad9fe2b84.png)

**Comment by devemux86** [comment]
(as there are usually no themes with a 1 element dash array)

What you suggest is use textures everywhere (with worse rendering, above the rectangles are broken).
We can add a new flag in `Parameters` class and developers can decide what to use.

About the `*8` or better value, it was added because dash array with small values do not work.
We can also make this value adjustable, as there does not seem to exist a solution working in all cases.

**Comment by demiantres** [comment]
Thanks. Another thing is that the line widths do not fully scale, i.e. the Mapsforge renderer fills the whole street width with the orange/white pattern, while the VTM renderer does not fill it in higher zoom levels. It seems as if the VTM renderer has a maximum width limit but I am still trying to figure out how this actually works.

**Comment by devemux86** [comment]
There is a parameter, 'fixed' in style and 'fix' in VTM themes, to try.
However, the results are still not like Mapsforge.

**Comment by devemux86** [comment]
Also OpenGL has limits, see https://github.com/mapsforge/vtm/issues/121#issuecomment-238960462.

**Comment by demiantres** [comment]
Ok, I think the problem is the ``variableScale`` in the LineBucket class.

**Comment by demiantres** [comment]
```LineTexBucket":
```
/* keep line width fixed */
gl.uniform1f(shader.uWidth, (lb.scale * line.width) / s * COORD_SCALE_BY_DIR_SCALE);
```

should be:
```
/* keep line width fixed */
gl.uniform1f(shader.uWidth, (lb.scale * line.width) / Math.sqrt(s) * COORD_SCALE_BY_DIR_SCALE);
```

**Comment by demiantres** [comment]
Better change this line in ``LineTexBucket``:
```
float s = scale / div;
```
to
```
float s = Math.sqrt(scale / div);
```

Now lines (even with thin dash pattern) look much better, almost like Mapsforge.

**Comment by devemux86** [comment]
For reference, Berlin map with Freizeitkarte theme and `MAPSFORGE_DASH_FACTOR` set as 1 or 8:
(the green line has different renderings, depends on the scale between zoom levels)
![Freizeitkarte1](https://user-images.githubusercontent.com/3484020/211573374-2ff5d20f-a5cb-490e-ab26-72a18fd48eae.jpg)
![Freizeitkarte8](https://user-images.githubusercontent.com/3484020/211573383-ac944567-a5c2-455a-a28c-d8546c382a81.jpg)

**Comment by demiantres** [comment]
Better (move this into the loop):
```
float s;
if (line.fixed)
  s = scale / div;
else
  s = Math.sqrt(scale / div);
```

**Comment by demiantres** [comment]
With this fix you no longer need to set the ``MAPSFORGE_DASH_FACTOR`` imaho.

**Comment by devemux86** [comment]
It is still the same small dashes and the green line still has 2 different renderings between zoom levels.

**Comment by demiantres** [comment]
I can reproduce the problem with the Freizeitkarte too. OAM maps + themes seem to work fine though.

**Comment by demiantres** [comment]
I think the problem is this check in the ``XmlThemeBuilder``:
```
if (f < 1) f = 1;
```

Freizeitkarte uses dash sizes < 1, while OAM uses sizes >= 1.

**Comment by devemux86** [comment]
Android / Java bitmaps used in line textures have integer width and height.
(maybe they are the ones that need the multiplier)

**Comment by demiantres** [comment]
Yes, this is what I meant.

**Comment by demiantres** [comment]
The Mapsforge renderer uses this:

```
void MFRenderContext::setScaleStrokeWidth(int zoomLevel)
{
    if (this->renderTheme)
    {
        int zoomLevelDiff = qMax(zoomLevel - STROKE_MIN_ZOOM_LEVEL, 0);
        this->renderTheme->scaleStrokeWidth(static_cast<float>(qPow(STROKE_INCREASE, zoomLevelDiff)), this->rendererJob->tile.zoomLevel);
    }
}
```

Maybe we can use this somehow...

**Comment by devemux86** [comment]
See #1008.

**Comment by devemux86** [comment]
Mapsforge rendering at large zooms isn't the best (extending width but not dash length),
so we have to be careful what similarity we're looking for.

**Comment by devemux86** [comment]
With https://github.com/mapsforge/vtm/pull/1008 it should be better.
If more work is needed, please create new issues with examples and suggestions for code improvement.
