### ISSUE TITLE
Add dy offset to lines

### ISSUE THREAD

**Issue by demiantres** [mapsforge/vtm#1007]
The Mapsforge renderer supports drawing of symbols with an offset (red dots in this example):
![image](https://user-images.githubusercontent.com/5980561/211767832-22a2d6f2-d34a-48af-89b9-c001e2623064.png)

The Mapsforge renderer calculates an offset path in the "RendererUtils,parallelPath" method.

I am currently investigating means for adding support for this in VTM. Do you have an idea how this can be done? One possibility is to create another vertex buffer with the offset path points but this adds a lot of complexity.

**Comment by devemux86** [comment]
This would be useful.

I had created https://github.com/mapsforge/vtm/issues/232 on 2016,
but I didn't have time to see it and neither did anyone else. :slightly_frowning_face: 

See also a topic in the [old forum](https://groups.google.com/g/mapsforge-dev/c/nb9w5s07s2Y).
