### ISSUE TITLE
Areas overlap and subtract

### ISSUE THREAD

**Issue by abdullahO2** [mapsforge/vtm#1010]
Hello
When two natural areas overlap, one does not appear on vtm but does on mapsforge:

![image](https://user-images.githubusercontent.com/61907628/213902756-55165bcb-0f20-4ec2-8244-1e7f95a1116d.png)

![image](https://user-images.githubusercontent.com/61907628/213902601-9637c705-ad85-47cb-a34e-bb5c60a51cb5.png)

- Application used: Cruiser 3.0.7
- The map used: Arab-Peninsular - 2023-01-06 from OpenAndroMaps:
 https://www.openandromaps.org/en/downloads/asia-middle-east
- Theme used: Elevate - Elements 5.2
- Image location:
https://www.openstreetmap.org/#map=11/25.5604/47.3477
[25.5187, 47.3542](https://www.openstreetmap.org/#map=13/25.5187/47.3542)

**Comment by devemux86** [comment]
Thanks for the detailed report.

Unfortunately it is a known issue in OpenGL, see https://github.com/mapsforge/vtm/issues/212.

- There is a possible solution with the VTM theme attribute `mesh`
(with other side effects: https://github.com/mapsforge/vtm/issues/224#issuecomment-564487735)
- Or organize the existing theme rules better, in case they are not declared at separate layers
(see https://github.com/mapsforge/vtm/issues/224#issuecomment-261043687)

Both cases require to modify the theme and this is more difficult with themes for Mapsforge engine.

**Comment by abdullahO2** [comment]
Thank you so much

**Comment by devemux86** [comment]
Let's keep it open, in case we can do something in the library.

**Comment by devemux86** [comment]
Another case was reported in Cruiser Discussions: https://github.com/devemux86/cruiser/discussions/38

This is a `natural=water` north of Munich: https://www.openstreetmap.org/relation/12048180

**Comment by abdullahO2** [comment]
I tried adding the following:
place=region
region:type=mountain_area
This led to the tag: natural=sand being ignored and the polygon representing the sand disappeared. Here is an example of relation that no longer appear in OAM maps:
https://www.openstreetmap.org/relation/10827666
https://www.openstreetmap.org/relation/12048768
