### ISSUE TITLE
NextzenMvtTileSource has a render bug: wrong tile positions (shuffled) on the level 2 zoom.

### ISSUE THREAD

**Issue by Psijic** [mapsforge/vtm#1065]
`NextzenMvtTileSource` has a render bug: wrong tile positions (shuffled) on the level 2 zoom. That's why I used `NextzenGeojsonTileSource`

**Comment by devemux86** [comment]
Please attach some screenshots to understand what you mean.

**Comment by Psijic** [comment]
https://i.imgur.com/12UHehV.png

**Comment by devemux86** [comment]
This is probably an error in the map provider.
At zoom levels 0-2 they provide the wrong tiles.

![Nextzen](https://github.com/mapsforge/vtm/assets/3484020/d18d45ae-f9c6-42de-b0e6-f5c23bdd755d)
