### ISSUE TITLE
TileSource: httpFactory by default

### ISSUE THREAD

**Issue by Psijic** [mapsforge/vtm#1066]
I see, the map loading is not working if you skip 
`.httpFactory(OkHttpEngine.OkHttpFactory(builder))`.
Currently I copy-pasted this file from the  `vtm-parent` sample, but could you include the default factory in the library?

**Comment by devemux86** [comment]
As seen in the [integration guide](https://github.com/mapsforge/vtm/blob/master/docs/Integration.md#online-tiles), the online tiles need some extra dependencies.

Many users are only interested in offline maps,
which do not need these extra dependencies.

**Comment by Psijic** [comment]
`OkHttpEngine` class is only 80 strings with imports and `OkHttp` is already used by Vtm. Looks like `proguard` should make this addon size negligible.
