### ISSUE TITLE
Overlapping transparent polylines produce darker regions

### ISSUE THREAD

**Issue by eddiemuc** [mapsforge/vtm#1082]
It seems that drawing polylines (e.g. Routes) with VTM with a certain thickness and a semi-transparent color leads to "darker edges" when those line segments are overlapping on polyline points. This effect is also visible when zooming out. 

Update: Also "spikes" appear with thick lines at small zooms.

Some screenshots:

Screenshot zoomed a bit above the polyline:
![image](https://github.com/mapsforge/vtm/assets/6909759/c89a1499-0837-42a6-927f-8b116d317520)

Screenshot close to polyline:
![image](https://github.com/mapsforge/vtm/assets/6909759/375623c9-9159-4413-9a28-2dba4ee9a2d3)

More details and code to reproduce issue can be found on this PR: #1081

**Comment by devemux86** [comment]
Also "spikes" appear with thick lines at small zooms.

**Comment by devemux86** [comment]
@eddiemuc playing with the OpenGL calls, but it needs more work and tests:

<img src="https://github.com/mapsforge/vtm/assets/3484020/f216d85b-5acd-4b9e-9a61-86c4182f4f36" width="50%"/>

**Comment by eddiemuc** [comment]
Very impressive! How did you do it?

Two comments:
* do you have any idea yet why one of the "turns" of the polyline is a "spike" while the others are "flat"?
* comparing with Google Maps: it would be ok if lines really crossing each other create a "darker" pattern IMHO. Only on the "turns" this should not happen. See below an example screenshot from GMaps for same polyline:

![image](https://github.com/cgeo/cgeo/assets/6909759/f2379963-a9bc-4333-a905-b159fe4bfe5b)

**Comment by charlenni** [comment]
A good article to this problem could be found [here](https://wwwtyro.net/2019/11/18/instanced-lines.html). Interesting are the diagrams where you could see, that your double drawing take place, when two of the segments are drawn on top of each other.

**Comment by devemux86** [comment]
@charlenni thanks, this a very interesting document.

**Comment by devemux86** [comment]
@charlenni thanks, this a very interesting document.

The lines certainly need more work at the corners.

**Comment by devemux86** [comment]
> Very impressive! How did you do it?

@eddiemuc I tested this code in [LineBucket.java#L643](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/renderer/bucket/LineBucket.java#L643).

```java
if (!Color.isOpaque(line.color)) {
    gl.depthMask(true);
    gl.clear(GL.DEPTH_BUFFER_BIT);
    GLState.test(true, false);
}
```

**Comment by fm-sys** [comment]
> comparing with Google Maps: it would be ok if lines really crossing each other create a "darker" pattern IMHO. Only on the "turns" this should not happen.

IMHO this is not necessary. Just because Google does it, it doesn't have to be good. If it's easier to never create the darker pattern we should go that way. But no strong preference, both is fine for me...

BTW, thanks @devemux86 for looking into this issue!

**Comment by charlenni** [comment]
It isn't because of Google having it this way (btw. Mapbox too), it is, because it is a bug. There shouldn't any of this dark parts at the edges. And the spike is also a problem, because it isn't the same edge form as the rest.

**Comment by eddiemuc** [comment]
> > comparing with Google Maps: it would be ok if lines really crossing each other create a "darker" pattern IMHO. Only on the "turns" this should not happen.
> 
> IMHO this is not necessary. Just because Google does it, it doesn't have to be good. If it's easier to never create the darker pattern we should go that way. But no strong preference, both is fine for me...
> 
> BTW, thanks @devemux86 for looking into this issue! 

That's correct. What I rather meant to say is: if it is for any reason much easier implementation-wise to just fix the dark pattern in turns (and not in crossings) then that would also be acceptable for us (because we accept it in GMaps as well). I wanted to lift the "implementation burden" a bit, that's all. Sorry for the confusion.

**Comment by devemux86** [comment]
If anyone knows OpenGL and want to help, I am happy to review pull requests.

For now I can push something like the above solution, probably via an option.

---

To avoid the spikes could use the `pointReduction(false)` in the `Style`.

Corners to be round instead of miter or bevel, needs work in `LineBucket`.
(the bevel currently is applied after a [condition](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/renderer/bucket/LineBucket.java#L382))

**Comment by devemux86** [comment]
@eddiemuc I merged https://github.com/mapsforge/vtm/pull/1084 in the latest [snapshot](https://github.com/mapsforge/vtm/blob/master/docs/Integration.md#snapshots).

As it is a core change, it can be enabled vix `Parameters.TRANSPARENT_LINES`.

**Comment by devemux86** [comment]
@eddiemuc

I merged https://github.com/mapsforge/vtm/pull/1084 in the latest [snapshot](https://github.com/mapsforge/vtm/blob/master/docs/Integration.md#snapshots), please test it in your implementation.

As it is a core change, it can be enabled via `Parameters.TRANSPARENT_LINES`.

**Comment by eddiemuc** [comment]
> @eddiemuc
> 
> I merged #1084 in the latest [snapshot](https://github.com/mapsforge/vtm/blob/master/docs/Integration.md#snapshots), please test it in your implementation.
> 
> As it is a core change, it can be enabled via `Parameters.TRANSPARENT_LINES`.

Looks MUCH better with the fix applied:

![image](https://github.com/mapsforge/vtm/assets/6909759/25c18fa3-2ef3-4400-b08d-23136dadc490)

But the "spike" remains, even when I set `pointReduction(false)`

Also zooming out leaves the polyline visible:

![image](https://github.com/mapsforge/vtm/assets/6909759/f7f00cbb-8524-4a9b-badd-029e5c8d1d14)

![image](https://github.com/mapsforge/vtm/assets/6909759/9eebf44e-c4e8-40d8-ada4-a41ee38c8a4a)

**Comment by devemux86** [comment]
> Also zooming out leaves the polyline visible:

The layers are always visible unless we hide them.

The `pointReduction` disables or not the default reduction of points when we zoom out.
When the line is too thick, the point reduction can show spikes around some line areas.

You can try without setting it, which is the default and see if it works better in your case.

> But the "spike" remains

Do you mean the line joins at the corners, this is different and needs new implementation.
Currently the best we can do is to force the bevel join in more corners (see [above](https://github.com/mapsforge/vtm/issues/1082#issuecomment-1859078472)).

**Comment by eddiemuc** [comment]
Already as is your change is a huge improvement! Thanks a lot!

> The `pointReduction` disables or not the default reduction of points when we zoom out. When the line is too thick, the point reduction can show spikes around some line areas.
> 
> You can try without setting it, which is the default and see if it works better in your case.

When I leave point reduction on then at a certain zoom level the polyline "thing" vanishes. That's a good thing. But the "vanish" zoom level is too far out. Is there any way to have more control over this?

The most "zoomed out" level where polyline thingy is still visible:
![image](https://github.com/mapsforge/vtm/assets/6909759/2d5075ab-50d3-4b1a-9706-c910740226eb)

One more "zoomed-out" level where polyline finally vanishes:
![image](https://github.com/mapsforge/vtm/assets/6909759/2b885457-5c98-45d8-9f07-d33bd648eee8)

> 
> > But the "spike" remains
> 
> Do you mean the line joins at the corners, this is different and needs new implementation. Currently the best we can do is to force the bevel join in more corners:

I mean the spike circled in red in following screenshot. But this is IMHO not the most pressing issue, I would consider this a minor thing.

![image](https://github.com/mapsforge/vtm/assets/6909759/fd9c98f9-6220-4805-af8b-d02922c9f76c)

**Comment by devemux86** [comment]
Try without using the point reduction call, that is leave it on (as default).

Otherwise you can hide the layer at the required zoom level.

**Comment by eddiemuc** [comment]
> Try without using the point reduction call, that is leave it on (as default).

I looked into the underlying code of pointReduction and found that the flag just sets a default constant drop distance to the line bucket. Experimenting with this I found that the zooming problem could be solved in a great way if the drop distance could be set directly (as a float) on the Style object. I prepared PR #15020 for this and would be glad if you would consider adding such a feature.

**Comment by eddiemuc** [comment]
Sorry, PR #1085 (I updated the previous comment)

**Comment by devemux86** [comment]
> I prepared PR https://github.com/mapsforge/vtm/pull/1085 for this and would be glad if you would consider adding such a feature.

@eddiemuc thanks! :+1:

**Comment by eddiemuc** [comment]
With PRs #1084 and #1085 merged I would consider this issue solved. Thanks a lot!

@devemux86 : we would like to include these fixes into c:geo (but don't want to use the snapshots for official c:geo builds). There was no release since the two PRs were merged, so we considered using jitpack.io. However, we noticed that since 0.19.0 both mapsforge and vtm seem not to build on jitpack.io any more (see https://jitpack.io/#mapsforge/mapsforge for mapsforge and https://jitpack.io/#mapsforge/vtm for vtm). Do you know the reason for this? Is there any other way to link to a stable build of e.g. https://github.com/mapsforge/vtm/commit/8d43af49170692fa65d1d4518c53017b1c1276ca (current master's head)

**Comment by devemux86** [comment]
@eddiemuc thanks for your contributions!

Does JitPack require special rules?
I just update Gradle when needed and make sure that it builds successfully and publish also works.

You can use the snapshots, the latest or a fixed version.
I always use the snapshots, releases are just snapshots with a label.

**Comment by eddiemuc** [comment]
> Does JitPack require special rules? I just update Gradle when needed and make sure that it builds successfully and publish also works.

Apparently jitpack requires a project to explicitely specify the Java version used for compile if it is not Java 8. See https://jitpack.io/docs/BUILDING/#java-version. This is why the build currently fails (see https://jitpack.io/com/github/mapsforge/vtm/0.20.0/build.log).

However, sorry for that, I somehow thought that mapsforge and vtm support jitpack (because we used it in the past :-)).

> You can use the snapshots, the latest or a fixed version. I always use the snapshots, releases are just snapshots with a label.

I found just one snapshot release here: https://oss.sonatype.org/#nexus-search;quick~vtm 
Wouldn't that one be overwritten any time a new commit is brought to vtm master? Sorry if this is a dumb question.

**Comment by devemux86** [comment]
@eddiemuc the snapshot builds and versions are here:
https://oss.sonatype.org/content/repositories/snapshots/org/mapsforge/

**Comment by devemux86** [comment]
@eddiemuc probably instead of:
```groovy
implementation 'org.mapsforge:vtm:master-SNAPSHOT'
```
could use for example:
```groovy
implementation 'org.mapsforge:vtm:master-20231227.121602-914'
```

**Comment by devemux86** [comment]
> Wouldn't that one be overwritten any time a new commit is brought to vtm master?

This only happens when using:
```groovy
implementation 'org.mapsforge:vtm:master-SNAPSHOT'
```

**Comment by eddiemuc** [comment]
> 
> ```groovy
> implementation 'org.mapsforge:vtm:master-20231227.121602-914'
> ```

There seems to be no consistency across the different sub-libs of VTM with regards to such snapshot version numbers, or I am doing something wrong here again?

E.g. using above version `master-20231227.121602-914` gives me:

![image](https://github.com/mapsforge/vtm/assets/6909759/98f7a911-0790-428c-8191-b67adaf880e3)

Using one earlier version `master-20231227.121602-913` gives me:

![image](https://github.com/mapsforge/vtm/assets/6909759/1e3fd57f-826b-42ce-bd87-0a6122016920)

**Comment by devemux86** [comment]
@eddiemuc indeed Maven publishes independently the modules, so need to use a fixed version for each one.

**Comment by eddiemuc** [comment]
> @eddiemuc indeed Maven publishes independently the modules, so need to use a fixed version for each one.

Ok, thanks! Using different versions it worked out. It's a bit tricky though.

**Comment by eddiemuc** [comment]
> I added `jitpack.yml` in Mapsforge and VTM in `jitpack` branch and they seem to build successfully.
> 
> @eddiemuc can you test if they work in c:geo?
> 
> https://jitpack.io/#mapsforge/mapsforge/jitpack-SNAPSHOT https://jitpack.io/#mapsforge/vtm/jitpack-SNAPSHOT

Works fine!

**Comment by devemux86** [comment]
@eddiemuc thanks for the confirmation!

I merged the JitPack improvement in both Mapsforge and VTM repositories.

**Comment by eddiemuc** [comment]
> @eddiemuc thanks for the confirmation!
> 
> I merged the JitPack support in both Mapsforge and VTM repositories.

Thanks a lot! I will now link this version to our master build (until VTM release 0.21.0 comes out :-))
