### ISSUE TITLE
Triangulation issues since release 0.18

### ISSUE THREAD

**Issue by dnesbitt61** [mapsforge/vtm#1097]
With Mapsforge VTM releases 0.18, 0.19, and 0.20 I am seeing triangulation issues with multiple map files. We develop on Android so the screenshots below are from an Andoid app. We have maryland.map and pennsylvania.map data loaded. This data was generated over a year ago, and we noted these issues when trying to upgrade to the latest VTM library. Checking versions we found proper rendering using version 0.17, but from 0.18 onwards we see issues. Images below compare an area near Perryville, Maryland. Land/sea triangulation appears, but also we see issues with 

With 0.17:
![mf017](https://github.com/mapsforge/vtm/assets/1838768/1e828c9a-14f1-4721-a027-3198472db079)
![aberdeen0_17](https://github.com/mapsforge/vtm/assets/1838768/f484467e-256c-4563-8b32-2124151b3138)

With 0.20 (similar with 0.18 and 0.19):
![mf020](https://github.com/mapsforge/vtm/assets/1838768/dd7126c5-7a3f-40ff-8493-9fc0e81f533f)
![aberdeen0_20](https://github.com/mapsforge/vtm/assets/1838768/64445623-17af-463f-acb3-55ab237ffc30)

**Comment by devemux86** [comment]
@dnesbitt61 what do you mean with "triangulation"?
For users not familiar with this map area, can you point what is wrong and how it should be rendered?

Or do you mean overlapping map files?
This is an OpenGL case and before there was an issue with e.g. same lake existing on overlapping map files.

There was a fix for overlapping maps in VTM 0.18, see:
- https://github.com/mapsforge/vtm/pull/903
- https://github.com/mapsforge/vtm/pull/905

There is also an open issue about overlapping regions in the same map:
- https://github.com/mapsforge/vtm/issues/1010

**Comment by dnesbitt61** [comment]
what do you mean with "triangulation"

I have been assuming that the issues I see are due to how polygons get converted into triangles. I am assuming that this is done within VTM since OpenGL can only render triangles. I could be wrong (not sure if you store polygons or triangles in the .map file - e.g. split polygons into triangles at run time or during data creation).

I see issues starting with 0.18. I tried attaching a video showing how areas change - with different triangle cutouts and such but the videos are too large. Here is another image comparison with maryland.map and pennsylvania.map loaded. See the large triangular parts of land that cut out into the Chesapeake Bay.

![vtm0_18](https://github.com/mapsforge/vtm/assets/1838768/19317cfc-0ad1-4642-af7c-09b665986372)

With 0.17:
![vtm0_17](https://github.com/mapsforge/vtm/assets/1838768/48888ba6-d9b9-4ab9-b6b4-d6f2347273b3)

**Comment by devemux86** [comment]
@dnesbitt61 I cannot reproduce it with Cruiser with latest VTM, default themes and maps from Mapsforge.

In your themes use the "mesh" just for land / sea, because it can cause artifacts in other areas.
- See the use of "mesh" in [default themes](https://github.com/mapsforge/vtm/blob/master/vtm-themes/resources/assets/vtm/default.xml#L176-L182)
- What happens if used elsewhere: https://github.com/mapsforge/vtm/issues/224#issuecomment-564487735
And commit https://github.com/mapsforge/vtm/commit/892ea925802e1805d309ca33e710c56388031324

Note: Mapsforge format is not related with the OpenGL or software rendering.
Map engines read the data and render them using the rules of each engine.

<img src="https://github.com/mapsforge/vtm/assets/3484020/a046338d-9c31-48a7-9887-80a28ea9a2b3" width="50%"/>

**Comment by dnesbitt61** [comment]
Should I expect Mapsforge/VTM versions to be backwards compatible? Specifically, should a newer version of the library work with prior versions of data, or do I need to generate new data (with compatible version of mapwriter) when we update the Mapsforge/VTM library? I am seeing these artifacts when using version 0.18 with older data. No artifacts with 0.17 on Android with the same data. I see no differences when I use a style file with only nosea and issea|sea with mesh="true" (compared with mesh="true" for all area features).

**Comment by devemux86** [comment]
All libraries are constantly being improved and being open source, everyone can contribute. :slightly_smiling_face: 

I can not know your maps / themes, but the tests are made with available Mapsforge maps and the themes in library.
In the above links there are details for the changes and why "mesh="true" for all area features" can lead to artifacts.

The fact that it could work in one map does make it good choice if it does not work in other maps
and produces a lot of GL warnings / errors in the log.

**Comment by devemux86** [comment]
All libraries are constantly being improved and being open source, everyone can contribute. :slightly_smiling_face: 

We cannot know your maps / themes, but the tests are made with available Mapsforge maps and the themes in library.
In the above links there are details for the changes and why "mesh="true" for all area features" can lead to artifacts.

Working good on one map does not make it a good choice if it does not work in other maps
and produces a lot of GL warnings / errors in the log.
