### ISSUE TITLE
Some default bitmap tile layers violate licenses

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#110]
To my opinion 
ARCGIS_RELIEF violates license:
http://downloads2.esri.com/ArcGISOnline/docs/tou_summary.pdf

> YOU MAY NOT
> Systematically harvest map tiles through any method other than using Esri Content Packages

HD_HILLSHADE violates license:
http://korona.geog.uni-heidelberg.de/contact.html

> If you intend to use tiles from OpenMapSurfer services in your own applications please contact us.

If I am right, may be they should be removed?

**Comment by devemux86** [comment]
You mean in `DefaultSources`?
I agree we should be careful with map source licenses.
Likewise Google Maps can be removed too.

**Comment by devemux86** [comment]
I removed also MapQuest, as direct tile access to MapQuest legacy maps has been [discontinued](http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/).

**Comment by hjanetzek** [comment]
What about attributing OSM data ;) 

```You are free to copy, distribute, transmit and adapt our data, as long as you credit OpenStreetMap and its contributors.```

**Comment by devemux86** [comment]
@hjanetzek you are right.

Eventually users can use the API to build a map source and retrieve tiles from anywhere.
Should not expose the sources that don't mean providing tiles outside their engines (i.e. Google Maps).

For testing purposes we could host such sources in the samples modules?

**Comment by hjanetzek** [comment]
@devemux86  yes, it might make sense to move this out of the library and put it in a place where users better realize that they have to take care of the licenses.
