### ISSUE TITLE
vtm-web Gradle 9

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#1110]
[vtm-web](https://github.com/mapsforge/vtm/tree/master/vtm-web) and [vtm-web-app](https://github.com/mapsforge/vtm/tree/master/vtm-web-app) during Gradle build show:

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
```

To not remove these modules, their Gradle build needs improvements.

**Comment by schedul-xor** [comment]
gwt-gradle-plugin , calling `getConvention()` inside, is raising the warnings.
https://github.com/jiakuan/gwt-gradle-plugin/issues/75
