### ISSUE TITLE
publish artifacts on Maven

### ISSUE THREAD

**Issue by stleusc** [mapsforge/vtm#115]
It would be nice to get the released artifacts from Maven.
Also, many libs use another hosting provider for snapshots (basically nightly builds) which allows users to get the latest and greatest via maven. Helpful for a lib that get's a lot of action :-)

**Comment by devemux86** [comment]
I plan to release VTM in Maven, see discussion [here](https://groups.google.com/forum/#!topic/mapsforge-dev/eB9ie_aThJw).
It's now in good condition for modern devices, we should really decide when it's that time to release a RC. :smile: 

Maven publishing is not automated, we support JitPack for that purpose, see the [integration guide](https://github.com/mapsforge/vtm/blob/master/docs/Integration.md).

**Comment by devemux86** [comment]
Closing this such discussion can be made in our forum:
https://groups.google.com/group/mapsforge-dev
