### ISSUE TITLE
Area style stroke-width is ignored

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#121]
I've tried to set wide outline for area (3.0 in my case) and didn't get desired result.

**Comment by devemux86** [comment]
Maybe something with `PolygonBucket` render calls.

**Comment by devemux86** [comment]
See commit https://github.com/mapsforge/vtm/commit/3c9e18d70c9ccbb90221496d401f5885c528e3e3 in `issue_121` branch if it fixes the problem.

Currently we use the `HairLineBucket` width 2 everywhere, set in above [line](https://github.com/mapsforge/vtm/blob/issue_121/vtm/src/org/oscim/renderer/bucket/PolygonBucket.java#L241).
Thorough testing is needed to check map's rendering after the change.

@hjanetzek any hint on this?

**Comment by hjanetzek** [comment]
The Area outline was mainly intended to get cheap anti-aliasing.The maximal GL_LINES width is hardware dependent and thicker lines would also have ugly cut-offs on steep angles. For hi-dpi displays 4px may look ok though, if the hardware supports it.

For thicker lines one should use an additional LineLayer

**Comment by devemux86** [comment]
>The maximal GL_LINES width is hardware dependent and thicker lines would also have ugly cut-offs on steep angles.

@hjanetzek thanks for the feedback, indeed with the change too large values have visual artifacts.

**Comment by andreynovikov** [comment]
> For thicker lines one should use an additional LineLayer

This is how I do it now, but the problem with line is that it does not support smooth fading, so my area fades but line stays solid.

**Comment by devemux86** [comment]
I find line fade working.
It needs good care the fade value not being smaller than the zoom where the element actually exist in the map.

**Comment by andreynovikov** [comment]
Do you mean just disappearing or smooth transparency change?

**Comment by devemux86** [comment]
The line fade works similar to area fade.

If setting `zoom-min="14"` or `fade="14"` in the theme and the data were declared in `tag-mapping` with `zoom-appear="15"`, then they'll appear on zoom 15 and the fade will not work too.

**Comment by devemux86** [comment]
I think we can close this.

**Comment by devemux86** [comment]
Better use separate lines for area outlines to avoid rendering problems:

Before:
![1](https://user-images.githubusercontent.com/3484020/70623976-e5078900-1c27-11ea-9cd6-7ad02ac91386.png)

After:
![2](https://user-images.githubusercontent.com/3484020/70623985-ea64d380-1c27-11ea-8e35-644a727d4bdb.png)
