### ISSUE TITLE
How to render cliff?

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#123]
A line with small ticks on it:
http://www.openstreetmap.org/#map=16/44.8367/34.5538

It is an essential item for hiking.

**Comment by devemux86** [comment]
See #105, we now support line stipples and textures.
Set a symbol in `src` and play with the various `stipple` parameters.

BTW such a question is more relevant in the [forum](https://groups.google.com/group/mapsforge-dev). :smile:

**Comment by andreynovikov** [comment]
I've got suitable result with:

```
<m k="natural" v="cliff">
    <line fix="true" stroke="#888888" width="4" />
    <line fix="true" stipple-stroke="#888888" src="assets:symbols/cliff.svg" stipple="100" width="24" />
</m>
```

But it would be more logical to control texture width with `stipple-width` instead of `width` so that above rule can look like:

```
<m k="natural" v="cliff">
    <line fix="true" stroke="#888888" width="4" stipple-stroke="#888888" src="assets:symbols/cliff.svg" stipple="100" stipple-width="24" />
</m>
```

Or normal line and textured line can not (should not) be combined?

**Comment by devemux86** [comment]
Stroke width is always present and it's what defines the whole line (textured or not) width.
The `stipple-width` has values `0.0-1.0` and is relative to line width, suitable for micromanagement.

**Comment by andreynovikov** [comment]
Ok, can be closed then.
