### ISSUE TITLE
Line stipple is not scaled

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#126]
If line is not fixed, its width scales together with map scale. But stipple is not. This results in bad visual perception of stripped lines on large map zooms.

**Comment by andreynovikov** [comment]
This is not what I mean. Stipple should be scaled like width is scaled here:
https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/renderer/bucket/LineBucket.java#L665

**Comment by devemux86** [comment]
Can discuss in [forum](https://groups.google.com/group/mapsforge-dev) and if there is interest from community to contribute.
