### ISSUE TITLE
Programmatically created line does not fade

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#127]
As mentioned in #121 I have a problem with line fading. It appears that when defined through XML style line fades as expected. But when created programmatically it disappears at once. My code extract is:

```
mAreaStyle = AreaStyle.builder().fadeScale(5).color(Color.BLUE).build();
mLineStyle = LineStyle.builder().fadeScale(5).color(Color.DKGRAY).strokeWidth(2f).fixed(true).build();
...
protected void processFeatures(AbstractVectorLayer.Task t, Box b) {
    ...
    MeshBucket mesh = t.buckets.getMeshBucket(1);
    if (mesh.area == null)
        mesh.area = mAreaStyle;

    LineBucket line = t.buckets.getLineBucket(0);
    if (line.line == null)
        line.line = mLineStyle;

    mesh.addMesh(mGeom);
    line.addLine(mGeom);
}
```

**Comment by devemux86** [comment]
I tested the (regular) PathLayer, as the JTS one has not yet a fade property.

Using in dark background the following line style:
```java
LineStyle.builder().fadeScale(5).color(Color.WHITE).strokeWidth(2f).fixed(true).build()
```
I see while in zoom 5 the fading, from invisible in 4 to completely visible in 6.

**Comment by devemux86** [comment]
Any news on that?

**Comment by andreynovikov** [comment]
I will look at it later.

**Comment by devemux86** [comment]
@andreynovikov any feedback?

**Comment by devemux86** [comment]
@andreynovikov is it still an issue?

**Comment by andreynovikov** [comment]
Yes, but my tests show that it's very specific. I'm now working hard on first public release of my application, have no time to dig it further.

**Comment by devemux86** [comment]
Closing, please reopen if needed.
