### ISSUE TITLE
Render themes: stroke dash array

### ISSUE THREAD

**Issue by stleusc** [mapsforge/vtm#131]
not much else to say ;-)

**Comment by devemux86** [comment]
We have line stipples implemented in #105, a good base for that.

See also https://github.com/opensciencemap/vtm/issues/3

**Comment by Klaus-Tockloth** [comment]
Dashed lines are very important in maps. Stipples aren't a surrogate for dashed lines because the underlaying object is always overwritten. Sometimes this ok but in most times it isn't. See example:

![bildschirmfoto 2016-10-29 um 20 45 26](https://cloud.githubusercontent.com/assets/5493128/19831995/ae83570a-9e18-11e6-87d4-13930a497c67.jpg)

**Comment by devemux86** [comment]
>the underlaying object is always overwritten

@Klaus-Tockloth what do you mean?
We can use transparency in stipples too.

**Comment by Klaus-Tockloth** [comment]
What I want to achieve is this: A short line followed by a gap followed by a short line and so one. In the gap one sees the underlaying object. In the picture above this is the wood area (with the tree symbols). My understanding of the stipples feature is, that you always have a solid line, and on top of this line you draw the stipples. If you make the stipples semitransparent you see the underlaying solid line but not the underlaying wood. Right?

PS: For a railway stipples are a possible option, but for the track (brown line) they are not.

**Comment by devemux86** [comment]
We can have in stipples the stroke color semi or completely transparent, see [here](https://github.com/mapsforge/vtm/blob/master/vtm-themes/resources/assets/styles/default.xml#L79-L80).

Still this pattern cannot have the flexibility of a dasharray's various combinations. :slightly_smiling_face:

**Comment by devemux86** [comment]
Thanks to PR #388 by @Longri for Mapsforge theme compatibility, we now have an implementation of line stroke dash array also in VTM themes.

**Comment by andreynovikov** [comment]
`dasharray` in `style-line` does not work. If I put it there no line is drawn at all, if I remove it, solid line is drawn. If I put `dasharray` in `line` it is still not drawn. If I remove `dasharray` from `style-line` it is drawn correctly.

**Comment by andreynovikov** [comment]
`dasharray` in `style-line` does not work. If I put it there no line is drawn at all, if I remove it, solid line is drawn. If I put `dasharray` in `line` it is still not drawn. If I remove `dasharray` from `style-line` it is drawn correctly.

**Comment by andreynovikov** [comment]
`fix="true"` seems not to be honored too.

**Comment by devemux86** [comment]
@andreynovikov thanks for the report!
See if latest update handles the issues.
