### ISSUE TITLE
use the building as a button on map.

### ISSUE THREAD

**Issue by saeid1** [mapsforge/vtm#136]
I will like to use the building as a Layer button. The know when the user clicks on a building, it is an ID returns.
please can you help me?

**Comment by devemux86** [comment]
With what map source, Mapsforge map files or online vector tiles?

And you mean to click an element on the map and perform reverse geocode to retrieve its attributes?

**Comment by saeid1** [comment]
**With what map source, Mapsforge map files or online vector tiles?** 
online vector tiles
**And you mean to click an element on the map and perform reverse geocode to retrieve its attributes?**
Yes

**Comment by devemux86** [comment]
I had implemented reverse geocoding in Mapsforge engine, see https://github.com/mapsforge/mapsforge/issues/727.
That could be integrated here too.

Regarding online vector tiles, I don't think there is something ready.

**Comment by saeid1** [comment]
**Regarding online vector tiles, I don't think there is something ready.** 
Yes i think too. do you have any idea who can do it?
I want to do the following:

1- seting the ID with x,y of Tiles +  minX , minY, maxX maxY in org.oscim.core.MapElement
2- in MapEventLayer at onTouchEvent returns the ID ...

**Comment by devemux86** [comment]
For questions please use our forum:
https://groups.google.com/group/mapsforge-dev
