### ISSUE TITLE
OkHttp 3

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#138]
Update to OkHttp 3.

**Comment by andreynovikov** [comment]
I can do it but in terms of  #140 is it still needed?

**Comment by devemux86** [comment]
In #140 I intend to separate OkHttp from `vtm` core, probably with a `vtm-http` module.
Like I did with external dependency `JTS` in #53 by creating the `vts-jts` module.

I won't remove anything, so you can proceed freely with the update (I can work with any result).

**Comment by andreynovikov** [comment]
Going on trip next week. Will do it in a month. You can assign it to me if you wish.

**Comment by devemux86** [comment]
I created `vtm-http` module for the external dependencies like `OkHttp`.
Moving there also its class, so it can be updated to latest version.

**Comment by devemux86** [comment]
I pushed an improved API for `OkHttpEngine` which permits external `OkHttpClient.Builder`, allowing for a wide range of customizations for OkHttp client used in VTM.
