### ISSUE TITLE
Intel Graphics crash

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#139]
I updated recently some machines with Ubuntu from 14.04 to 16.04.
VTM now does not work at all on both desktop and on Android emulator with Intel graphics.
Previously it worked fine. The cpu / graphics tested are `Sandy Bridge` and `Haswell`.

On desktop the application freezes the pc for a while and then crashes with the following:
`intel_do_flush_locked failed: Input/output error`
On Android the same behavior, at the end the whole emulator crashes.

I tried the various samples we have in repository (even with newer `Mesa` driver).
The simple ones like the Bezier work, but the complex ones like the map do not.

Note that OpenGL at machines works fine, also on Android emulator.
It seems something in our implementation / shaders causes now all the mess.

@hjanetzek any hints where to start looking?

**Comment by devemux86** [comment]
Investigation revealed that even on simple working examples if we enable the debug `TileGridLayer` then the crash happens immediately.

**Comment by devemux86** [comment]
The labels (text buckets) cause the issue. OpenGL in any example without them works fine.

**Comment by hjanetzek** [comment]
It's a driver bug then - opengl call may never crash, that's what vulkan is for :)

Some android adreno drivers had an issue with glSubBufferData. You can disable it somewhere in Renderer.java iirc

**Comment by devemux86** [comment]
Well previous distribution worked, so the indications show the driver.
But why the Google Maps app works without issues in Android emulator?
Should we do something wrong somewhere?

**Comment by devemux86** [comment]
Thanks for the feedback.
I tried changing `GLAdapter.NO_BUFFER_SUB_DATA` but the crashes still happen.

**Comment by hjanetzek** [comment]
I would wait for the intel driver to be fixed or file a bug report there. Of course one could try removing gl calls until finding the one that triggers the crash. When gmaps works it just means that it does not hit the bug.

**Comment by devemux86** [comment]
The problem arises from the billboard [check](https://github.com/mapsforge/vtm/blob/master/vtm/resources/assets/shaders/texture_layer.glsl#L16) in `texture_layer` shader.

That's a floating point number comparison made with `==` where we can have accuracy issues.

Usually it's safer using an epsilon value, e.g. replacing with the following seems to fix the problem:
```glsl
if (mod(vertex.x, 2.0) < 1.0)
```

**Comment by hjanetzek** [comment]
wow that's a good catch! 

The weird thing is that vertex.x should not have a fractional part (since all vertex buffers use signed shorts for coordinates)

**Comment by devemux86** [comment]
>The weird thing is that vertex.x should not have a fractional part (since all vertex buffers use signed shorts for coordinates)

The `mod` has two `float` arguments and result a `float`.
In case of expected result `0.0`, the floating point calculation can evaluate e.g. `0.00000001` breaking our shader branching (depending on GPU / driver).

**Comment by hjanetzek** [comment]
I could rather imagine that the modulus evaluate to -0.0 (https://www.opengl.org/sdk/docs/man/html/mod.xhtml) which is then considered != 0.0. Just curious, could you try:
```if (mod(vertex.x, 2.0) == 0.0 || mod(vertex.x, 2.0) == -0.0)``` ?

**Comment by devemux86** [comment]
@hjanetzek :+1: 
Indeed checking for both `0.0` and `-0.0` works, no need for floating point epsilon here.

**Comment by hjanetzek** [comment]
ah ok - good to know :) ```if (abs(mod(vertex.x, 2.0)) == 0.0``` is slightly nicer, if you want to take that change.

**Comment by devemux86** [comment]
Yes that's a more fine check, just pushed it.
Thanks @hjanetzek for the valuable feedback!
