### ISSUE TITLE
LocationRenderer: rendering all the time

### ISSUE THREAD

**Issue by JawenChuang** [mapsforge/vtm#141]
Hi,
I notice that the map keep rendering even there's nothing update on it. 
What cause doing rendering as I see the render mode is "RENDERMODE_WHEN_DIRTY".
Thanks.

**Comment by devemux86** [comment]
I suppose you mean on Android.
How did you check the continuous rendering?
Can you confirm it in e.g. Samples SimpleMapActivity?
Because a map event listener can cause such behavior.

**Comment by andreynovikov** [comment]
If you [enable debugging](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/backend/GLAdapter.java#L21) you will see when rendering occurs.

**Comment by JawenChuang** [comment]
Thanks for reply.
Yes I use it on android. I  try to debug my app and found that it continuous draw by glview thread itself.

![debug](https://cloud.githubusercontent.com/assets/19699213/17878459/68e67950-691d-11e6-9aca-d2711f871a2b.png)

It makes me confused that why it keep drawing in 'dirty mode'.

**Comment by devemux86** [comment]
Indeed we needed more info.
So you are not just showing a plain map, but have also a location overlay.
How do you use it, does it update continuously from  sensor?

**Comment by devemux86** [comment]
See in [LocationIndicator.animate](https://github.com/mapsforge/vtm/blob/master/vtm-app/src/org/oscim/app/location/LocationOverlay.java#L119).

**Comment by JawenChuang** [comment]
Yeah I found it's caused by sensor. Thanks for your help.

**Comment by mathieudebrito** [comment]
Hi guys,

I'm also facing this issue, I debugged until understanding this was the LocationLayer that ask the map to render again and again. The thing is that I don't understand why : I removed the code using sensors (for bearing) but still, the map is asked to render itself.

I tested on the LocationActivity example and I see the same problem.
Do you have any idea why the locationRenderer asks the map to render so often ?

**Comment by devemux86** [comment]
It's controlled via `LocationRenderer.animate(boolean)`, where there is map rendering calls every 50ms.

**Comment by mathieudebrito** [comment]
Ok ! Shouldn't we call `mMap.render()` only if the location or bearing has changed ?

**Comment by devemux86** [comment]
Need to test that.
There is also the case of location out of screen where the animation happens.

**Comment by mathieudebrito** [comment]
Indeed, good point.
I think it could still be not rendering unless map has changed (bounds/location) ?

**Comment by devemux86** [comment]
Probably, would need refactor the location renderer (or for compatibility better provide a 2nd improved one), as currently it doesn't follow a location listener, but uses GL render instead.

Let's reopen the issue to check for improvements.

**Comment by devemux86** [comment]
I pushed a minor change letting continuous rendering only when location is outside screen for the animation effect.

Please check to see how it behaves for you too.
