### ISSUE TITLE
Long text labels should be wrapped

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#144]
Sometimes POI names are so long that do not fit the screen.

**Comment by andreynovikov** [comment]
Am I the only one who is very annoyed with this issue? I am a dumb in OpenGL but if you will point me where to look for it I will try to fix it.

**Comment by devemux86** [comment]
In Mapsforge we use percentage of tile size (default 70%) and process it differently on:
- [Android](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-android/src/main/java/org/mapsforge/map/android/graphics/AndroidPointTextContainer.java) via [StaticLayout](https://developer.android.com/reference/android/text/StaticLayout.html)
- [Desktop](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-awt/src/main/java/org/mapsforge/map/awt/graphics/AwtPointTextContainer.java) via [LineBreakMeasurer](https://docs.oracle.com/javase/7/docs/api/java/awt/font/LineBreakMeasurer.html)

Here probably [TextBucket](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/renderer/bucket/TextBucket.java) could be a start. Also remains how break text into lines for all platforms.

**Comment by andreynovikov** [comment]
Yes, I know it's about TextBucket. I'm a little bit confused how to calculate text width and height.

**Comment by devemux86** [comment]
Apparently this needs to work on all VTM platforms (Android, iOS, Desktop, Browser).
Probably instead of creating a global calculation, could we use each platform's special classes (seen above)? (like we do already in graphics API)

**Comment by devemux86** [comment]
Can discuss in [forum](https://groups.google.com/group/mapsforge-dev) and if there is interest from community to contribute.
