### ISSUE TITLE
Stippled outline not rendered correctly

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#146]
Through XML render style permits stippled outlines if you add `stipple` and `stipple-stroke` to the outline it will start drawing as a regular line.

**Comment by devemux86** [comment]
What do you mean by outline?
Stippled lines have background the `stroke` color and stipples with `stipple-width` width and `stipple-stroke` color.

e.g. making more intense the default [footway](https://github.com/mapsforge/vtm/blob/master/vtm-themes/resources/assets/styles/default.xml#L79-L80) stippled line, the rendering seems as expected.
```xml
<style-line cap="butt" fix="true" id="footway" stipple="4" stipple-stroke="#ffffff" stipple-width="0.6" stroke="#ff0000" width="4" />
```

**Comment by devemux86** [comment]
@andreynovikov any feedback?

**Comment by andreynovikov** [comment]
I mean outlines that are used to outline roads. There is no way to create such outline:
http://a.tile.openstreetmap.org/19/305391/152280.png

**Comment by devemux86** [comment]
Ok I understand now what you mean.

Currently not supported, i.e. only `LineBucket` renders outlines, not `LineTexBucket` being responsible for textures and stipples.
