### ISSUE TITLE
Android libGDX flickering

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#148]
Android libGDX sometimes flickers and jitters when panning / zooming.

Related to #149.

**Comment by devemux86** [comment]
The issue can be clearly observed if we enable the continuous rendering in [GdxMap.create()](https://github.com/mapsforge/vtm/blob/master/vtm-gdx/src/org/oscim/gdx/GdxMap.java#L73):
```java
Gdx.graphics.setContinuousRendering(true);
```

**Comment by devemux86** [comment]
Playing with the various settings of `AndroidApplicationConfiguration` in [MainActivity](https://github.com/mapsforge/vtm/blob/master/vtm-android-gdx/src/org/oscim/gdx/MainActivity.java#L48) this seems to help:
```java
cfg.numSamples = 2;
```

**Comment by RootSoft** [comment]
It seems 
`cfg.numSamples = 2;`
is helping a little bit. but the camera is still acting up/weird when panning/zooming/rotating.

What about clearing the screen in your render method?
```
@Override
    public void render(float delta) {

        if (!mRenderRequest)
            return;

        //clear screen
        Gdx.gl.glClearColor(1, 1, 1, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

        mMapRenderer.onDrawFrame();
    }
```

This seems to help also, but again the camera is sometimes jittering/flickering.

**Comment by devemux86** [comment]
Which `render` do you mean?

Regarding clearing see also #5, where a fix was needed for the desktop.

_Side note: we have multiple platforms sharing a common core, so need to be extremely careful with any change in the `vtm` module._

**Comment by RootSoft** [comment]
Yes, the one in GdxMap. I've been putting all my code in a GdxMapScreen so I can handle different [screens](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/Screen.html) on my Game. I don't have any jittery effects anymore, but sometimes the camera (viewport) is acting strange.

**Comment by devemux86** [comment]
Made a quick test with just the clearing, the result is the same with flickering.

**Comment by RootSoft** [comment]
Mhmm yes indeed, thought it was fixed but after a while it started flickering again.
Holding in (touching) the screen withouth doing anything else, shakes the camera  little bot too.

**Comment by devemux86** [comment]
@RootSoft on what device(s) do you see the flicker?

Because I'm able to see it on [Nexus 9](http://www.gsmarena.com/htc_nexus_9-5823.php) but not on [Samsung Galaxy Tab 4 7.0 LTE](http://www.gsmarena.com/samsung_galaxy_tab_4_7_0_lte-6241.php) (Android 5.1.1).

**Comment by RootSoft** [comment]
I'm using an [Elephone P9000 ](http://www.devicespecifications.com/en/model/7da9397e)(Android 6.0).

**Comment by devemux86** [comment]
I enabled MSAA in example to check it in action.

**Comment by RootSoft** [comment]
I've uploaded a video showcasing the flicker and camera issue [here](https://drive.google.com/open?id=0B2y6dyBq3t97bUt5MkVvQmM4YzA).

Using the following settings:
```
AndroidApplicationConfiguration cfg = new AndroidApplicationConfiguration();
cfg.stencil = 8;
cfg.numSamples = 2;
Gdx.graphics.setContinuousRendering(false);
```

As you can see, the tree's are sometimes flickering and not rendering for 1/2 seconds too. Don't know if it's related to this issue

**Comment by devemux86** [comment]
Thanks for the visual feedback, it helps understanding your view.
That's what I saw and with the MSAA not happening anymore.
Here flicker appears on all the map and trees follow.

**Comment by devemux86** [comment]
@RootSoft have you tried desktop libGDX #149, how is the behavior there and on what platforms?

**Comment by RootSoft** [comment]
I haven't tried it on desktop yet since I haven't configured the LibGDX desktop side yet. I'll notify once I've tried it there

**Comment by glensimar** [comment]
Hi Guys! I have this jittering/flickering efects sometimes when i tried to include seamarks to map, and it seems that user the same icon for all seamarks, i use a rendertheme from mapsforge (i don't know if this works) with some changes.. But this happened in version 5.1 or lower.. i android 6 works nice..

**Comment by devemux86** [comment]
`GdxMap.render` has a check to skip renders. If we comment it, then works without flickering (no MSAA needed).
I pushed the changes in [libGDX](https://github.com/mapsforge/vtm/tree/libGDX) branch.
Tested on Android and Linux with rendering seems fine. More tests needed on Windows and macOS.
Can you also test in your environments?
