### ISSUE TITLE
Desktop libGDX flickering

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#149]
Desktop libGDX sometimes flickers and jitters when panning / zooming.
This appears more often on Windows and macOS platforms.

Related to #148.

**Comment by devemux86** [comment]
The issue can be more clearly observed if we enable the continuous rendering in [GdxMap.create()](https://github.com/mapsforge/vtm/blob/master/vtm-gdx/src/org/oscim/gdx/GdxMap.java#L73):
```java
Gdx.graphics.setContinuousRendering(true);
```

**Comment by devemux86** [comment]
Playing with the various settings of `LwjglApplicationConfiguration` in [GdxMapApp](https://github.com/mapsforge/vtm/blob/master/vtm-desktop/src/org/oscim/gdx/GdxMapApp.java#L63) this seems to help:
```java
cfg.samples = 2;
```

**Comment by devemux86** [comment]
I enabled MSAA in example to check it in action.

**Comment by devemux86** [comment]
Closing as tests are successful in affected platforms.
Please report any feedback from your systems.

**Comment by andreynovikov** [comment]
Flicker disappeared but jitter persists (simply on mouse move over map, without button pressing)...

**Comment by devemux86** [comment]
What OS, graphics card, driver?

I tested on (Windows, macOS, Linux) with (nVidia, Intel) without seeing anything.

**Comment by devemux86** [comment]
Latest Mesa 17.2.4 release on Linux shows this behavior with Intel GPU.

**Comment by devemux86** [comment]
`GdxMap.render` has a check to skip renders. If we comment it, then works without flickering (no MSAA needed).
I pushed the changes in [libGDX](https://github.com/mapsforge/vtm/tree/libGDX) branch.
Tested on Android and Linux with rendering seems fine. More tests needed on Windows and macOS.
Can you also test in your environments?
