### ISSUE TITLE
PathLayer dotted line

### ISSUE THREAD

**Issue by ago75** [mapsforge/vtm#15]
hello, I'm glad you've taken over the development of vtm. I'm trying to make a dotted line with the use of PathLayer class with poor results, you could help. thank you

**Comment by devemux86** [comment]
I have not tried with `PathLayer`, but I fixed `LineRenderTest` via #30 to show the use of [stippled line](https://github.com/mapsforge/vtm/blob/master/vtm-playground/src/org/oscim/test/LineRenderTest.java#L81-L82).

Related to [opensciencemap/vtm/issues/3](https://github.com/opensciencemap/vtm/issues/3).

**Comment by devemux86** [comment]
Line or `PathLayer` stipples and textures was implemented in #105.
You can also check the examples for the API use.
