### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by stleusc** [mapsforge/vtm#152]
While running the android app I created a heap dump after closing map and running GC.

There are MANY references to:
- VertexData$Chunk
- LineBucket
- PolygonBucket
- RenderBuckets
- MapTile
  etc.

Using Android studio this is rather easy to reproduce.

I also look in the code, for example BitmapBucket:

``` java
protected void clear()
```

is not called anywhere, this is the case for many many objects. They are rather large and that should be looked at.

Numbers: package org.oscim, retained heap: 95MB, out of that 75MB in VertexData$Chunk, 10MB in other buckets, 4MB layers, 4MB theme

So we really should look at that. Especially VertedData$Chunk and how we can free that.

I added this to my copy, which is based on older/mixed code base:

MapRenderer.java

``` java
    public static void destroy() {
        BufferObject.clear();
        mBufferPool.releaseBuffers();
        mBufferPool = null;
    }
```

MyMapActivity.java

``` java
    public void onDestroy() {
        System.out.println("-----> MAP DESTROYED....");
        super.onDestroy();
        mMap.destroy();
        MapRenderer.destroy();
        TextureBucket.pool.clear();
    }
```

That already freed quite a big chunk, but retaining so much memory is bad....

**Comment by stleusc** [comment]
from RenderBuckets.java
```java
    public static void initRenderer() {
        LineBucket.Renderer.init();
        LineTexBucket.Renderer.init();
        PolygonBucket.Renderer.init();
        TextureBucket.Renderer.init();
        BitmapBucket.Renderer.init();
        MeshBucket.Renderer.init();
        HairLineBucket.Renderer.init();
    }
```

While there is an init, there is no destroy or similar and many of these renderers keep static references that could be cleared.

Based on trial and error, adding this:

```java
        TextureBucket.pool.clear();
        VertexData.pool.clear();
        TextItem.pool.clear();
        TextureItem.disposeTextures();
        MapRenderer.destroy(); // after TextureItem.disposeTextures(); or NPE
```

will get the retained memory down to 80k, from 90M+. Good start I guess.

Like I said, trial and error, I'm sure there is a more scientific way to do this ;-)

**Comment by devemux86** [comment]
Thanks for the feedback, will need careful look at it.

A central `destroy()` that performs such tasks and gets called on each platform's life cycle could work.

_Reminder: `RenderTheme.dispose()` is not called too._

**Comment by stleusc** [comment]
Down to 5k retained memory... Some is simple static array with null values. So I guess that would be acceptable in my eyes.

**Comment by mpelesh** [comment]
`static AssetAdapter g` in `AssetAdapter` is also never cleared, and I believe this one is the primary leak cause (reported by LeakCanary). While it is easy to set it to null using `AssetAdapter.init(null)` in activity/fragment onDestroy() method, sometimes it causes an app crash because GLTHread thread is still alive and it trying to use this method. See a stack trace below:

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.InputStream org.oscim.backend.AssetAdapter.openFileAsStream(java.lang.String)' on a null object reference
       at org.oscim.backend.AssetAdapter.readTextFile(AssetAdapter.java:44)
       at org.oscim.renderer.GLShader.loadShader(GLShader.java:48)
       at org.oscim.renderer.GLShader.create(GLShader.java:24)
       at org.oscim.renderer.bucket.PolygonBucket$Shader.(PolygonBucket.java)
       at org.oscim.renderer.bucket.PolygonBucket$Renderer.init(PolygonBucket.java:168)
       at org.oscim.renderer.bucket.RenderBuckets.initRenderer(RenderBuckets.java:419)
       at org.oscim.renderer.MapRenderer.onSurfaceCreated(MapRenderer.java:231)
       at org.oscim.android.gl.GLView$GLRenderer.onSurfaceCreated(GLView.java:38)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1503)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by devemux86** [comment]
> reported by LeakCanary

:+1: 

We need to address those issues and improve the API.
(probably after next VTM release)

**Comment by mfatiga** [comment]
Hi!
What's the progress on this issue? Have the fixes proposed by @stleusc been implemented to at least partially solve the issue? Memory leaks are never good :-)

**Comment by mfatiga** [comment]
I currently can't do it, because I haven't used the library or studied the code long enough to be capable of doing it :-)

**Comment by devemux86** [comment]
We'll see what can be done with that.
Like all open source projects, there is no any ETA, just free time to implement anything. :slightly_smiling_face:

**Comment by mfatiga** [comment]
Of course, I understand :). I have started using the android library and I'm working on an App where the main focus will be the map, so I hope that I will learn enough about it to be able to contribute.

**Comment by devemux86** [comment]
For further discussion can use the [forum](https://groups.google.com/group/mapsforge-dev).
