### ISSUE TITLE
LwHttp SkImageDecoder::Factory returned null

### ISSUE THREAD

**Issue by JawenChuang** [mapsforge/vtm#153]
Hi,
I found that using lwhttp is much easier faild to decode tile data. Especially some larger tile like google sat map.
30695-3289/org.oscim.android.test D/skia: --- SkImageDecoder::Factory returned null.

Okhttp is much better.

**Comment by devemux86** [comment]
`OkHttp` support exists via the `vtm-http` module.
You can set it via `.httpFactory(new OkHttpEngine.OkHttpFactory())` with `UrlTileSource.Builder`, like [here](https://github.com/mapsforge/vtm/blob/master/vtm-playground/src/org/oscim/stuff/MapzenTest.java#L49).

**Comment by stleusc** [comment]
why would the Http engine matter for bitmap decoding???

**Comment by devemux86** [comment]
[LwHttp](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/tiling/source/LwHttp.java) often has missed tiles with on-demand tile generated map sources, like OpenScienceMap or Mapbox (Mapzen #57) and consequently failed decoding.

`OkHttp` is a more advanced and recommended solution (#138).

**Comment by devemux86** [comment]
`LwHttp` erroneous behavior should be fixed via #460.
