### ISSUE TITLE
ScaleBar disappears sometimes

### ISSUE THREAD

**Issue by easdue** [mapsforge/vtm#155]
Playing around with vtm-android-example SimpleMapActivity (33b68f)  I noticed that the map scale bar disappears sometimes. Easiest way to reproduce is zoom in to maximum zoom level. If the scale bar is still shown, pan until it disappears. On zoomlevel 21 is even easier to reproduce.

I also noticed that the scalebar is never drawn when I remove the label layer.

**Comment by easdue** [comment]
I don't know anything about openGL but looking at TextRender.java I tried calling GLState.test(false, false) in BitmapRenderer.render() first and it seems to solve the problem, see attached patch..

[BitmapRenderer.patch.txt](https://github.com/mapsforge/vtm/files/444585/BitmapRenderer.patch.txt)

**Comment by devemux86** [comment]
Thanks for this, will need to check it.

**Comment by devemux86** [comment]
Indeed depth buffer test causes the issue, scale bar layer must not participate in it.

Still we shouldn't modify the generic `BitmapRenderer` class.
Instead we could create a `MapScaleBarRenderer` for the specific behavior.

Do you want to submit a PR with all that?

**Comment by easdue** [comment]
Without the missing GLState.test(false, false) in the BitmapRenderer other BitmapLayers will not  be drawn when there is no LabelLayer. (because that calls GLState.test(false, false).  I'm just reading a little about openGL and I don't feel confident enough yet to contribute to the code.

**Comment by devemux86** [comment]
`BitmapRenderer` currently is not used elsewhere than `MapScaleBarLayer`.
Let's handle this here and will see for other cases, where there may be different requirements.

I pushed the fix (with your name).
