### ISSUE TITLE
Render Theme - Improve visibility/distinguishability of Streets

### ISSUE THREAD

**Issue by boldtrn** [mapsforge/vtm#157]
I noticed that it is hard to see differences between streets. For example on a zoom-level when the residential roads are shown, there is (almost?) no difference between tertiary roads and residential roads. 

For this  purpose I think one of the best rendering styles is the [OSM Germany style](https://www.openstreetmap.de/karte.html). It adds different colors for different street types and also nice labels with the street name, for some streets. The Mapnik German style is available [here](http://svn.openstreetmap.org/applications/rendering/mapnik-german/).

**Comment by devemux86** [comment]
BTW another nice feature is the road shield symbols. :smile:

**Comment by devemux86** [comment]
Probably related to #67.

**Comment by devemux86** [comment]
Closing as internal render themes are improved continuously.
And pull requests for enhancements are always welcome! :slightly_smiling_face:
