### ISSUE TITLE
3D building roofs disappear with MapsForge maps

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#163]
Having MapsForge map as a tile source on some zooms/camera positions 3D building roofs disappear.

For instance here roofs are rendered:

![screenshot_20160908-120603](https://cloud.githubusercontent.com/assets/2943625/18343781/6d101548-75bd-11e6-999c-c967d2872832.png)

But when a map is slightly moved they disappear:

![screenshot_20160908-120612](https://cloud.githubusercontent.com/assets/2943625/18343797/7abe379c-75bd-11e6-8ab4-af1ebe6bc42a.png)

Opening the same place from online tile source does not reproduce a problem:

![screenshot_20160908-120622](https://cloud.githubusercontent.com/assets/2943625/18343803/82adaf78-75bd-11e6-8ca4-7b7c330e858b.png)

This means that the problem is in the way geometries are stored in MapsForge map file. This is the Austria map, coordinates: 47.288965 11.416759
But this problem can be found in nearly any settlement.

**Comment by devemux86** [comment]
I think I have seen that issue.

**Comment by devemux86** [comment]
VTM has changed a lot since then, can discuss in [forum](https://groups.google.com/group/mapsforge-dev) if still valid.
