### ISSUE TITLE
How to integrate to Android Studio using gradle?

### ISSUE THREAD

**Issue by HoverAlex** [mapsforge/vtm#166]
The integration guide documents there is Gradle support but I cannot seem to find the latest build. The badge on the main page shows unknown.

So how can i integrate vtm in Android Studio using gradle?

**Comment by devemux86** [comment]
We have not published yet VTM in Maven Central repository.

You can still use the `master-SNAPSHOT` version by adding as repository (see in [guide](https://github.com/mapsforge/vtm/blob/master/docs/Integration.md#snapshots)):
```groovy
maven { url "https://oss.sonatype.org/content/groups/public/" }
```

For questions please use our forum:
https://groups.google.com/group/mapsforge-dev
