### ISSUE TITLE
MapRenderer: not all OpenGL resources are re-created when EGL context is lost.

### ISSUE THREAD

**Issue by easdue** [mapsforge/vtm#167]
When the EGL context is lost onSurfaceCreated() is called but only minimal OpenGl resources are re-created (e.g. tile vertex buffers are not re-initialized). Rendering continues to be performed but without the needed resources being in place this ultimately leads to a segmentation violation in the jni library.

**Comment by devemux86** [comment]
For questions and discussion please use the [forum](https://groups.google.com/group/mapsforge-dev).
