### ISSUE TITLE
House numbers (nodes) not visible

### ISSUE THREAD

**Issue by stkb** [mapsforge/vtm#168]
From https://groups.google.com/forum/#!topic/cruiser-users/boEVk7rMM0c

Using Cruiser on Android (v1.4.11) in software (mapsforge) rendering, house numbers are visible from zoom level 18. With OpenGL rendering (VTM) house numbers are not visible at all, at any zoom level.

Example screenshots: of a section of [Bussum, Netherlands](http://www.openstreetmap.org/#map=18/52.27489/5.16961). On the left is mapsforge rendering, on the right VTM. Map is the netherlands.map file downloaded from http://download.mapsforge.org/maps/europe/

<img width="720" alt="20160915_175648 2" src="https://cloud.githubusercontent.com/assets/6125444/18558014/961011b4-7b71-11e6-9240-fed33ed65647.png">

**Comment by devemux86** [comment]
Related to #33.

**Comment by devemux86** [comment]
Some house numbers are visible (e.g. see berlin.map), so an additional fix is needed here.

![housenumber](https://cloud.githubusercontent.com/assets/3484020/18561077/fba19056-7b86-11e6-876e-c65e7f3ad19d.png)

**Comment by devemux86** [comment]
We have 2 types of house numbers: ways and nodes.
Those that don't appear on VTM are the node house numbers.

**Comment by devemux86** [comment]
Actually the reason for this issue seems to be #219.
Permitting `MapFileTileSource` reading from zoom 18 can show all house numbers but with other problems (see https://github.com/opensciencemap/vtm/issues/122).

The question is why the node house numbers need level 18 at reading?

**Comment by devemux86** [comment]
Mapsforge map writer has a fixed zoom 18 for inclusion of house numbers (nodes).
I changed it to 17 in https://github.com/mapsforge/mapsforge/issues/895 and in the future we could make it totally customizable.

You will need new maps to see all house numbers.
Build them with latest map writer `master-SNAPSHOT` and we'll use it also at next build cycle in our download server.
