### ISSUE TITLE
Line textures artifacts

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#174]
Line textures rendering has visual artifacts on some mobile graphics cards at large zoom levels.

![1](https://cloud.githubusercontent.com/assets/3484020/18668362/a0603764-7f3d-11e6-928f-4190dfdd9e62.png)
![2](https://cloud.githubusercontent.com/assets/3484020/18668364/a3e72f82-7f3d-11e6-8c52-9755c816747f.png)

Screenshots from [Samsung Galaxy Tab 4 7.0 LTE](http://www.gsmarena.com/samsung_galaxy_tab_4_7_0_lte-6241.php) with Mali-400MP4 GPU.

**Comment by Pedinel** [comment]
Hi!,
I'm having a similar issue in a Blu R1HD (Only in high zoom levels). When I reach zoomLevel 17 (or higher), the Texture icon (The default arrow pattern) is pixelated (Like a low resolution bitmap being size-increased).
[http://imgur.com/a/eYZZt](url)

**Comment by devemux86** [comment]
[BLU R1 HD](http://www.gsmarena.com/blu_r1_hd-8171.php) with Mali-T720 GPU.

**Comment by D0ni3L** [comment]
Hi, i have this bug too, but, I have Qualcomm Adreno 306 GPU in Motorola Moto G4 play XT1607

![captura de pantalla 2016-10-26 a las 3 05 59 p m](https://cloud.githubusercontent.com/assets/23084339/19740561/1b1d8c02-9b8d-11e6-9f4e-386206810a69.png)

**Comment by devemux86** [comment]
Reminder to check if using POT textures in such line overlays can help.
