### ISSUE TITLE
Theme texture not drawn on iOS

### ISSUE THREAD

**Issue by Longri** [mapsforge/vtm#179]
Wood texture 
I will check this later.

**Comment by Longri** [comment]
This problem coms with new iOS10 and need changes on robovm.
I will check this with install a iOS9 simulater!

**Comment by Longri** [comment]
We can close this!

I do not know since when the error is fixed, but I guess it happened with the last RoboVm update.

![screen shot 2017-03-05 at 17 19 47](https://cloud.githubusercontent.com/assets/2542295/23589136/5f7b791c-01c8-11e7-85f5-1723258a0b4a.png)

**Comment by devemux86** [comment]
@Longri 
So I suppose it should be working with VTM 0.7.0 too?

**Comment by Longri** [comment]
Maybe! I'll check out the 0.7.0 and try

**Comment by Longri** [comment]
I have tried 0.7.0 and 0.6.0 and both are ok!
Maybe it was a fix from iOS him self!
