### ISSUE TITLE
C-style string comparisons

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#190]
We have several C-style string comparisons which need fixing.

**Comment by devemux86** [comment]
Reopening as we have more cases.

**Comment by hjanetzek** [comment]
Hey @devemux86 it's nothing like 'c-style' string comparison.  It's comparing *interned* strings by object directly. See e.g. https://en.wikipedia.org/wiki/String_interning#Motivation

**Comment by devemux86** [comment]
Thanks @hjanetzek for keeping an eye here. :+1: 

I had seen you use interns and we have some regular strings.
Reopening to review their origin at each compare.

>At least for Tag keys I would stick with interned Strings

@andreynovikov what was the issue with the #185 ?

**Comment by andreynovikov** [comment]
```
if (element.tags.containsKey(mLocalizedName))
    name = element.tags.get(mLocalizedName).value;
```
gave no result while
```
if (element.tags.containsKey("name:ru"))
    name = element.tags.get("name:ru").value;
```
was working as intended.

**Comment by devemux86** [comment]
We could use some unit tests for such classes, to easily catch any issues.
