### ISSUE TITLE
Renderthemes: Caption with large stroke value draws stroke at wrong places

### ISSUE THREAD

**Issue by mar-v-in** [mapsforge/vtm#193]
![Sample](http://i.imgur.com/nL1QiLJ.png)

I extended the rendertheme with the intention to put a nice caption on motorways. The relevant rule is:

``` xml
<text caption="true" fill="#eeeeee" k="ref" priority="2" size="14" stroke="#E79608" stroke-width="16.0"/>
```

While it renders with larger stroke as expected, it seems the drawing area is cut to a certain area and the part of the stroke that goes beyond is put to some other text element.

Reproducable on desktop and android.

**Comment by devemux86** [comment]
Confirmed.
BTW I like the implementation. :smile:

**Comment by devemux86** [comment]
VTM has changed a lot since then, can discuss in [forum](https://groups.google.com/group/mapsforge-dev) if still valid.

**Comment by devemux86** [comment]
See #737.
