### ISSUE TITLE
Android: Multiple MapView's apparently not supported?

### ISSUE THREAD

**Issue by mar-v-in** [mapsforge/vtm#194]
I see various issues when having multiple MapView's on Android at the same time:
1. Sometimes, the text is not rendered correctly, there is only a black box where text is supposed to be
2. Sometimes, parts of the map are not rendered (lines and/or areas).
3. Sometimes, wrong symbols are put in place
4. Sometimes, it just crashes.

Is it intended to support multiple map views at the same time?

**Comment by devemux86** [comment]
Could be due to shared static data among the map views.

If you want to provide a pull request example for Samples, in order to have it live and check it.

**Comment by mar-v-in** [comment]
Set of screenshots done using the new sample just provided via PR: http://imgur.com/a/2b4TW

**Comment by devemux86** [comment]
I improved slightly the multi map example.
Note: it keeps crashing on emulator, working on device.

**Comment by andreynovikov** [comment]
MapView on Android uses GLSurfaceView. GLSurfaceViews can not overlap:
https://groups.google.com/forum/#!topic/android-developers/COffLpanlz0

**Comment by mathieudebrito** [comment]
Hi Andrey, you can use mapview.setZOrderOnTop(true) on the map on the top
to make it work.

--
Mathieu de Brito
www.mathieudebrito.fr <http://mathieudebrito.fr>
Fr : +33 6 87 36 74 78

**Comment by devemux86** [comment]
@andreynovikov thanks for the info.
So they mention not overlapping, what about having them side by side?

**Comment by mathieudebrito** [comment]
Hi guys, 

I made a working sample of fragments stack showing different mapviews. 
It works perfectly until you pop a fragment: coming back to the mapview of the previous fragment, it all works fine except labels. 

Any ideas ?
![device-2017-01-26-150944](https://cloud.githubusercontent.com/assets/1231274/22334074/89c0dd5a-e3d9-11e6-8bc8-f789666ec045.png)

**Comment by ocsike** [comment]
Hi,
Possible solution for black label. It's work for me
`onResume `event add: `mLabelLayer.update();`
and `onPause` event add  `mLabelLayer.clearLabels();`

Where mLabelLayer is a LabelLayer instance

**Comment by devemux86** [comment]
@ocsike where do you use those statements, have you managed to work with [MultiMapActivity](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/MultiMapActivity.java) example?

**Comment by ocsike** [comment]
Yes, but is not perfect solution. Black labels are show when move or zoom the map,  but not continuous and not all situation.
Here is a code:

```
public class MultiMapActivity extends Activity {
    private MapView mMapView1, mMapView2;
    private MapPreferences mPrefs1, mPrefs2;
	
	private LabelLayer map1LabelLayer;
	private LabelLayer map2LabelLayer;
	private Map map1; 
	private Map map2;

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Tile.SIZE = Tile.calculateTileSize(getResources().getDisplayMetrics().scaledDensity);
        setContentView(R.layout.activity_map_multi);

        setTitle(getClass().getSimpleName());

        // 1st map view
        mMapView1 = (MapView) findViewById(R.id.mapView1);
        map1 = mMapView1.map();
        mPrefs1 = new MapPreferences(MultiMapActivity.class.getName() + "1", this);
        VectorTileLayer baseLayer1 = map1.setBaseMap(new OSciMap4TileSource());
		map1LabelLayer = new LabelLayer(map1, baseLayer1);
        map1.layers().add(new BuildingLayer(map1, baseLayer1));
        map1.layers().add(map1LabelLayer);
        map1.setTheme(VtmThemes.DEFAULT);

        // 2nd map view
        mMapView2 = (MapView) findViewById(R.id.mapView2);
        map2 = mMapView2.map();
        mPrefs2 = new MapPreferences(MultiMapActivity.class.getName() + "2", this);
        VectorTileLayer baseLayer2 = map2.setBaseMap(new OSciMap4TileSource());
		map2LabelLayer = new LabelLayer(map2, baseLayer2);
		
        map2.layers().add(new BuildingLayer(map2, baseLayer2));
        map2.layers().add(map2LabelLayer);
        map2.setTheme(VtmThemes.DEFAULT);
    }

    @Override
    protected void onResume() {
        super.onResume();

        mPrefs1.load(mMapView1.map());
        mMapView1.onResume();

        mPrefs2.load(mMapView2.map());
        mMapView2.onResume();
		
		
		map2LabelLayer.update();
		map1LabelLayer.update();
    }

    @Override
    protected void onPause() {
        super.onPause();

        mMapView1.onPause();
        mPrefs1.save(mMapView1.map());

        mMapView2.onPause();
        mPrefs2.save(mMapView2.map());
		
		map2LabelLayer.clearLabels(); 
		map2.render();
		
		map1LabelLayer.clearLabels(); 
		map1.render();
		
    }
}
```

![2017_04_19_08 55 29](https://cloud.githubusercontent.com/assets/13695075/25167625/68519266-24e0-11e7-8de3-be4fa11ccfd9.png)

**Comment by mathieudebrito** [comment]
I tried your solution @ocsike but for me it's same with or without update()/clear() 

Do anyone have any idea of when this issue will be addressed ?
This is really annoying when using the Android Backstack. because even if you have only one mapview, it gets messed up when just resuming the fragment. And when using multiple mapviews, it's just not usable anymore :p

**Comment by devemux86** [comment]
@mathieudebrito doesn't the fragment example in samples work?

**Comment by mathieudebrito** [comment]
@devemux86 Indeed, it works with a single fragment.  
But when we pause and resume multiple times using the fragment backstack, the map gets messed up :p

**Comment by Gustl22** [comment]
I'll try to solve. But cannot give any promises.

**Comment by devemux86** [comment]
There is [MultiMapViewActivity](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/MultiMapViewActivity.java) sample to play.

_It never got any traction due to small interest and as any solution must not affect rest library functionality._

**Comment by Gustl22** [comment]
As Note: I noticed that make `GLState` as object is a huge intervention in whole library which could have unexpected results. Even though current approach not correspond the design patterns I propose to let all be synchronized via current `GLState` and find a solution to for multiple MapViews with static context.

**Comment by devemux86** [comment]
> I noticed that make `GLState` as object is a huge intervention in whole library which could have unexpected results.

Indeed, one feature can never justify such huge intervention and the possible negative outcome.

> I propose to let all be synchronized via current `GLState` and find a solution to for multiple MapViews with static context.

:+1:

**Comment by devemux86** [comment]
Not supported by library.

**Comment by mathieudebrito** [comment]
Hi @devemux86 ! Sorry for the question, but I just want to clarify : Is this a "Not supported by library for now" or a "will Not be supported by library" ?

**Comment by devemux86** [comment]
"Not supported by library", the future is unknown... :slightly_smiling_face: 

It remains open source, but if changes are so huge, then like mentioned [above](https://github.com/mapsforge/vtm/issues/194#issuecomment-465583568):

_"one feature can never justify such huge intervention and the possible negative outcome"_

**Comment by vvavepacket** [comment]
> As Note: I noticed that make `GLState` as object is a huge intervention in whole library which could have unexpected results. Even though current approach not correspond the design patterns I propose to let all be synchronized via current `GLState` and find a solution to for multiple MapViews with static context.

Hello, could you provide some context or background regarding what variables need to be synchronized, and whats the root cause in laymen's term? Would like to spend some personal time here to solve this issue

**Comment by Gustl22** [comment]
Hi @vvavepacket, like @devemux86 [mendioned](https://github.com/mapsforge/vtm/issues/194#issuecomment-250981310) the main reason is that library uses static variables (especially the [GLState](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/renderer/GLState.java) and some Pools, and may TileData) which is shared between multiple map instances but accessing the same indices. 

I came to the conclusion, that it's very hard to find all shared (static) resources and properly separate them for each map view (uploaded my attempt [here](https://github.com/Gustl22/vtm/tree/glstate_object), which I wouldn't recommend). You may have luck if you synchronize the `GLState` calls for each draw (but doesn't solve the issue with shared pools e.g on TextBuckets).

Sorry haven't worked on VTM for a while to give you more insight. Unfortunately I'm busy with other projects, so can't afford much time for this issue. Maybe there's an easier proper solution, too, which I overlooked. Hope you can continue with these infos.
