### ISSUE TITLE
Render themes: Draw caption around the symbol

### ISSUE THREAD

**Issue by mar-v-in** [mapsforge/vtm#195]
Currently it's only possible to draw the caption over or under the symbol (using `dy`), how about adding support to put the label left or right of the symbol?

**Comment by devemux86** [comment]
Thanks for reminding that! :+1: 

The plan is to provide all possible positions for symbols / captions, like in Mapsforge (see [here](https://github.com/mapsforge/mapsforge/blob/master/docs/Rendertheme.md#symbol-positioning)).

**Comment by devemux86** [comment]
Can discuss in [forum](https://groups.google.com/group/mapsforge-dev) and if there is interest from community to contribute.
