### ISSUE TITLE
Cannot do proguard becase of slf4j

### ISSUE THREAD

**Issue by saturngod** [mapsforge/vtm#203]
When I generate the self sign apk , I got following error

Error:Error converting bytecode to dex:
Cause: java.lang.IllegalArgumentException: already added: Lorg/slf4j/ILoggerFactory;

**Comment by devemux86** [comment]
VTM has the `slf4j-api` dependency, with any SLF4J binding.

What's your projects dependencies related to SLF4J?
Using the following is any help?
```groovy
compile('org.mapsforge:vtm:[CURRENT-VERSION]') {
    transitive = false
}
```

**Comment by saturngod** [comment]
I was using snapshot jar before and got that error. After using gradle , it working fine.
