### ISSUE TITLE
Any reason for having caption style element?

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#206]
The only difference between `<caption>` and `<text>` is that `caption` sets the corresponding flag by default. So may be it should be removed to eliminate ambiguity in styles?

**Comment by devemux86** [comment]
I think that each has also some extra tags: `<caption>` can use [symbols](https://github.com/mapsforge/vtm/blob/master/resources/rendertheme.xsd#L150) and `<text>` can be used in [styles](https://github.com/mapsforge/vtm/blob/master/resources/rendertheme.xsd#L210-L211).
