### ISSUE TITLE
Moving vim-extra into vtm

### ISSUE THREAD

**Issue by charlenni** [mapsforge/vtm#21]
I wonder, if vtm-extra isn't the same as vtm. Both contain tile sources and other thing. Wouldn't it be correct to integrate vtm-extra into vtm?

**Comment by devemux86** [comment]
`vtm-extras` contains material on top of the absolutely necessary for map rendering, e.g. OSM, GeoJSON parsing.
And its dependencies have various libraries which shouldn't be forced to users who want just a map view.

@hjanetzek lately had included JTS in `vtm` which could be located externally, for not loading library core.
