### ISSUE TITLE
How to set custom font for map data?

### ISSUE THREAD

**Issue by ahmadazimi** [mapsforge/vtm#210]
Is there any public method to set custom font for features on the map?
For example creating a TypeFace from a font in asset then pass it to the vtm.

**Comment by devemux86** [comment]
Map is rendered via rules defined in render theme files (like [this](https://github.com/mapsforge/vtm/blob/master/vtm-themes/resources/assets/styles/default.xml)).
In render themes currently the available fonts are [fixed](https://github.com/mapsforge/vtm/blob/master/resources/rendertheme.xsd#L45-L53).

For additional fonts it'd be needed each Paint implementation to load them per platform.

**Comment by devemux86** [comment]
Discussion in [forum](https://groups.google.com/forum/#!topic/mapsforge-dev/veB2fIBHpIo).
