### ISSUE TITLE
Overlapping areas of the same type get subtracted

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#212]
This is the original area with many overlapping military areas:
http://osm.org/go/TbJ9qA
![openstreetmap](https://cloud.githubusercontent.com/assets/2943625/19799351/d683ddd0-9cfe-11e6-9646-55c8e8263ffb.png)

This is how it looks like in MapsForge raster renderer:
![screenshot_20161028-111000](https://cloud.githubusercontent.com/assets/2943625/19799425/4bb847b2-9cff-11e6-91de-ef49bd1ef7d3.png)

And this is how it looks like in VTM vector renderer:
![screenshot_20161028-111035](https://cloud.githubusercontent.com/assets/2943625/19799437/5b551a7e-9cff-11e6-9e08-b7ecf670dbe2.png)

The same happens with any overlapping areas of the same type (rendering rule?), for instance this is often the case for protected areas.

**Comment by devemux86** [comment]
Probably a known problem(?) and related to OpenGL rendering (see https://github.com/opensciencemap/vtm/issues/84, https://github.com/opensciencemap/vtm/issues/118).

As @hjanetzek explains there, polygons using the default  stencil buffer rendering without tessellation, require elements coming from one layer to not overlap.
Using the mesh rendering is slightly slower to load (requires tessellation) and requires more memory, but should be faster to render. And it does not support currently pattern textures.

I had the same problem with Mapsforge map land 'split overlapped' polygons and solved it in #37, #38 by adding a tessellation option to area style and make it configurable via the theme.

**Comment by andreynovikov** [comment]
Yes, when I add `mesh="true"` to the theme problem disappears for simple areas. But I use patterns for them. Is it hard to add support for pattern textures to `MeshBucket`?

**Comment by devemux86** [comment]
So far I hadn't the chance checking it to give a good answer. :slightly_smiling_face:

**Comment by andreynovikov** [comment]
Or may be any other workaround to overcome that? Will adding layers to overlapping polygons help?

**Comment by devemux86** [comment]
You mean @hjanetzek 's suggestion [here](https://github.com/opensciencemap/vtm/issues/84#issuecomment-47440931)?
That could probably work (have not tried it), but with a performance hit due to multiple layers and need connected to the themes too.

**Comment by andreynovikov** [comment]
No, I mean OSM element layer.

**Comment by devemux86** [comment]
@andreynovikov see also my https://github.com/mapsforge/vtm/issues/224#issuecomment-261043687.

**Comment by devemux86** [comment]
See solution [above](https://github.com/mapsforge/vtm/issues/212#issuecomment-256869127).
