### ISSUE TITLE
Framing of areas not working properly

### ISSUE THREAD

**Issue by Klaus-Tockloth** [mapsforge/vtm#213]
It seems that the framing of areas isn't working. This leads to nothing:

```
    <m e="way" k="leisure" v="pitch" closed="yes">
      <area fill="#80d7b4" stroke="#49ba8e" stroke-width="0.1" />
    </m>
```

That's the expected result (from mapsforge rendering):

![bildschirmfoto 2016-10-29 um 20 24 02](https://cloud.githubusercontent.com/assets/5493128/19831936/834f03ba-9e16-11e6-813f-e13d26210900.jpg)

And that is what I get with VTM:

![bildschirmfoto 2016-10-29 um 20 27 00](https://cloud.githubusercontent.com/assets/5493128/19831939/97ceab42-9e16-11e6-8e82-0a218dce568e.jpg)

**Comment by devemux86** [comment]
See also #121.

**Comment by devemux86** [comment]
Closing as OpenGL has some limits, explained by @hjanetzek [here](https://github.com/mapsforge/vtm/issues/121#issuecomment-238960462).
The recommended way for area stroke in VTM themes is using extra line rule.

For Mapsforge themes compatibility (#100), we need to think how to handle that.
