### ISSUE TITLE
Scaling for SVG resources

### ISSUE THREAD

**Issue by Klaus-Tockloth** [mapsforge/vtm#214]
According to the XSD scaling for symbols (icons) isn't supported yet:

```
<xs:complexType name="symbol">
      <xs:attribute name="cat" type="xs:string" use="optional" />
      <xs:attribute name="src" type="tns:src" use="required" />
</xs:complexType>
```

Mapsforge has options for scaling:

```
<rule e="node" k="*" v="cycle_barrier" zoom-min="18">
  <symbol display="always" src="file:/symbols/umlaufsperre.svg" symbol-scaling="size" symbol-width="20" />
</rule>
```

Please see this issue as a feature request.

**Comment by devemux86** [comment]
Thanks @Klaus-Tockloth for mentioning it!
Indeed now we use the SVG symbols with default scaled size.

I had added in #74 the complete SVG customization we have in Mapsforge.
So it shouldn't be too difficult to implement, we need the connection with the theme.

**Comment by vk45** [comment]
Is something like symbol-scaling="size" symbol-width="20"  or symbol-scaling="percent "to scale svg's in the rendertheme implemented now?
Please see this issue as a feature request.

**Comment by devemux86** [comment]
Not yet, I'll look after it soon. :slightly_smiling_face:

**Comment by devemux86** [comment]
The SVG scaling tags are the same with Mapsforge (see [here](https://github.com/mapsforge/mapsforge/blob/master/docs/Rendertheme.md#svg-scaling)).
