### ISSUE TITLE
Rendering of new features not possible in ZL 18 and above

### ISSUE THREAD

**Issue by Klaus-Tockloth** [mapsforge/vtm#216]
It seems that isn't possible to introduce new map feature in zoomlevel above 17.

This works:

```
    <m e="way" k="building" v="gebaeude_allgemein" closed="yes" zoom-min="17">
        <caption k="addr:housenumber" style="normal" size="11" fill="#333333" stroke="#00123456" stroke-width="1.0" />
    </m>
```

This didn't:

```
    <m e="way" k="building" v="gebaeude_allgemein" closed="yes" zoom-min="18">
        <caption k="addr:housenumber" style="normal" size="11" fill="#333333" stroke="#00123456" stroke-width="1.0" />
    </m>
```

Peculiar ...

**Comment by devemux86** [comment]
`MapFileTileSource` has a default max zoom level [17](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/tiling/source/mapfile/MapFileTileSource.java#L56).
Related zoom conversation in https://github.com/opensciencemap/vtm/issues/122.

**Comment by devemux86** [comment]
@hjanetzek 's change from max zoom 18 is in https://github.com/opensciencemap/vtm/commit/3178787954c990b4d8d15e3023f8559a4036c7c1.

**Comment by Klaus-Tockloth** [comment]
There is a relation to issue #217

**Comment by devemux86** [comment]
`MapFileTileSource`'s default max zoom level 17 is for tiles rendering, the map view can zoom much more, e.g. to zoom 20.

**Comment by devemux86** [comment]
Permitting `MapFileTileSource` reading also from zoom 18 can solve this, but with other problems (see opensciencemap#122).

**Comment by braandl** [comment]
There is another issue with Mapsforge Mapfiles and zl >= 18. Using Float Datatypes in the Projection Code causes the renderer to genereate hugh round-off errors. Changing all lat-lon related datatypes to double fixes a whole lot of this errors and does not cost too much performance on newer smartphones.

I did write a patch for this (https://github.com/schudt/vtm/commit/739941b4d3241bbbebb4214d47e3baf3c9c3edcb) but it is not well tested so far.

**Comment by devemux86** [comment]
And there is more, e.g. core classes like `GeoPoint` and `BoundingBox` use integers for their coordinates.
(in [Mapsforge](https://github.com/mapsforge/mapsforge) we use everywhere doubles without issues)

So shouldn't we start from those first and then proceed with other areas of the library?

@braandl if you want to submit a pull request on latest master, I can merge it in a separate branch.
Data type is a very important change and would need extremely good testing.

@hjanetzek any particular reason for using integers (or it's an [Osmdroid](https://github.com/osmdroid/osmdroid) influence)?

**Comment by braandl** [comment]
@devemux86 Ok, I will create a Pull-Request. I did run my configuration with a mapsforge file and the visual render quality is way better!
But the Issues from https://github.com/opensciencemap/vtm/issues/122 are not resolved with this.

**Comment by devemux86** [comment]
First screenshots in https://github.com/opensciencemap/vtm/issues/122 probably refer to an old Mapsforge issue with grid artifacts on zooms 12-13.
See [here](https://groups.google.com/forum/#!topic/mapsforge-dev/1TzknbgeJgo) for discussion and [here](https://groups.google.com/forum/#!topic/mapsforge-dev/GadiGI5iQNU) for a solution involving different map creation.

**Comment by braandl** [comment]
Thank you! I will look into that :-) I did create a pull-request with the datatype changes.

**Comment by devemux86** [comment]
Closing as there is no blocker now, just need to use `MapFileTileSource(0, 18)` or larger.

For proper separation of data extraction and rendering, continue in #393.
