### ISSUE TITLE
Zoomlevel shift between Mapsforge and VTM

### ISSUE THREAD

**Issue by Klaus-Tockloth** [mapsforge/vtm#217]
It seems that there is a basic zoomlevel shift by minus one (-1) in VTM. In other words: What I get in Mapsforge in ZL 18 is equal to what I get in VTM in ZL 17.

Mapsforge zoomlevel 18:
![screenshot_2016-10-30-06-15-38](https://cloud.githubusercontent.com/assets/5493128/19834676/49feec8e-9e6a-11e6-8a90-97e2b308b736.png)

VTM zoomlevel 17:
![screenshot_2016-10-30-06-07-37](https://cloud.githubusercontent.com/assets/5493128/19834683/79127f40-9e6a-11e6-8dc9-a435f43ea13d.png)

**Comment by devemux86** [comment]
VTM has continuous zooming, so if you zoom a little more at start of 18, you'll see the Mapsforge equivalent fixed zoom.

Mapsforge:
![mapsforge](https://cloud.githubusercontent.com/assets/3484020/19835757/fe9312ce-9e97-11e6-8960-cf0c6723a120.png)

VTM:
![vtm](https://cloud.githubusercontent.com/assets/3484020/19835758/041a1972-9e98-11e6-966d-e1459c1051b9.png)

**Comment by Klaus-Tockloth** [comment]
Continuous zooming? The usage of the plus/minus button in Cruiser GL leads for me to an increment or decrement by one zoomlevel.

Let me explain the issue by an example. Buildings are introduced in zoomlevel 14:

```
    <m e="way" k="building" v="gebaeude_allgemein" closed="yes" zoom-min="14">
      <area fill="#c1b0af" stroke="#aa94a4" stroke-width="0.1" />
    </m>
```

Zoomlevel 14 in Cruiser (mapsforge):
![screenshot_2016-10-30-13-12-25](https://cloud.githubusercontent.com/assets/5493128/19836559/cb5f4730-9ea4-11e6-889e-c20b116f7f89.png)

Zoomlevel 14 in Cruiser GL (vtm):
![screenshot_2016-10-30-13-14-30](https://cloud.githubusercontent.com/assets/5493128/19836563/068adec8-9ea5-11e6-86d4-d109266dd2a1.png)

As you can by the width (geometry) of the river (rhine), the vtm rendering of the map is one zoomlevel higher as the rendering of mapsforge. In both cases buildings are introduced in zoomlevel 14. Under vtm this is one level to late and not what the map designer intended. 

Zoomlevel 15 in Cruiser (mapsforge, only for comparison):
![screenshot_2016-10-30-13-12-45](https://cloud.githubusercontent.com/assets/5493128/19836610/0579adc4-9ea6-11e6-95d9-a90f4f14586d.png)

**Comment by devemux86** [comment]
>Continuous zooming?

Yes, try to zoom with pinch touch gesture on Android or with `N`, `M` keys on Desktop.

>The usage of the plus/minus button in Cruiser GL leads for me to an increment or decrement by one zoomlevel.

Zoom buttons can perform level zoom `+1` or `-1`, I could adjust them better so that they end to the "fixed" zoom levels.

Above in "Zoomlevel 14 in Cruiser GL (vtm)" screenshot is the end of zoom 14 level, essentially zoom a little more and you'll see the 15 in tile grid.

**Comment by devemux86** [comment]
@Klaus-Tockloth is there still a problem with the zoom levels?

An easy way to compare the same zoom in both libraries is to use the "Go to" tool and select same settings.

**Comment by Klaus-Tockloth** [comment]
> @Klaus-Tockloth is there still a problem with the zoom levels?

Yes, the issue with the zoomlevel is not solved. For me this defect is cruicial because it breaks compatibility between mapsforge and vtm.

Let me try to explain it:

The rendering of a map object (e.g. a landuse=water) is defined:
- primary in the map data (map-writer, e.g. zoomlevel 10)
- secondary in the theme (e.g. zoomlevel 12)

Result in mapsforge: rendering starts at zoomlevel 12
Result in vtm: rendering starts at zoomlevel 13 (!)
Expectation for vtm: rendering should also start at zoomlevel 12

BTW: As a "quick hack" in the theme which I have provided for testing, I have decreased all zoomlevel entries (min, max) by one (e.g. 12 -> 11). But this could not be the solution, because for a lot of objects the zoomlevel is defined within the map data (map-writer) and can not be changed.

**Comment by devemux86** [comment]
Unless I'm missing something obvious here, probably you didn't understood my explanation? :slightly_smiling_face: 

Could you do a quick test?
Open Cruiser and Cruiser GL (Android or Desktop) on same device, so that tile size is the same.
Then use the "Go to" tool and go to the same coordinates and zoom level.
You should see the exact same area (and zoom), at least that's what I see in below screenshots.

Note that in Mapsforge the zoom levels are fixed, i.e. ..., 11, 12, 13, ...
In VTM there are not zoom levels, only a continuous scale and the zoom levels are "derived" from it.
Try pinch zoom on Android or Shift + mouse drag on Desktop to see it.

Don't be confused by the debug tile grid in VTM and its mentioned zoom.
Each zoom number starts appearing at corresponding Mapsforge's fixed one.
So you should compare the zoom interval start and not intermediate scale (e.g. between 12 and 13).

Cruiser:
![cruiser](https://cloud.githubusercontent.com/assets/3484020/19939938/a07bb1fc-a133-11e6-8a87-20c7c393ddef.png)

Cruiser GL:
![cruiser_gl](https://cloud.githubusercontent.com/assets/3484020/19939945/a86ea158-a133-11e6-8e2d-c2c98945d6c0.png)

**Comment by Klaus-Tockloth** [comment]
Hmm, it seems that this issue is hard to explain ... only look at the blue icon for the filling station:

The first zoomlevel were the icon is visible in mapsforge:
![bildschirmfoto 2016-11-02 um 19 57 28](https://cloud.githubusercontent.com/assets/5493128/19943329/3809bcfa-a137-11e6-8900-ab4d8542559f.jpg)

The first zoomlevel were the icon is visible in vtm:
![bildschirmfoto 2016-11-02 um 19 57 37](https://cloud.githubusercontent.com/assets/5493128/19943351/4fcdddee-a137-11e6-990c-850d7103b12d.jpg)

In both cases the icon is rendered starting with zoomlevel 15 (this is correct). But at this point the vtm map looks different (enlarged) compared with the mapsforge map.

```
      <m cat="tankstelle" e="node"  v="fuel" zoom-min="15" zoom-max="16">
        <symbol id="tankstelle"  src="file:/symbols/amenity_fuel.svg"  symbol-width="14" />
      </m>
```

```
      <rule cat="tankstelle" e="node" k="*" v="fuel" zoom-min="15" zoom-max="16">
        <symbol id="tankstelle" display="always" src="file:/symbols/amenity_fuel.svg" symbol-scaling="size" symbol-width="14" />
      </rule>
```

**Comment by devemux86** [comment]
VTM screenshot (looking also at scale bar) is clearly more zoomed than Mapsforge, so you are not in zoom 15 interval start but between 15 and 16.

How do you go to that zoom in VTM, with mouse wheel?
Can you try with N, M buttons or with Shift + mouse drag slowly?
Or with "Go to" tool set zoom 15 to go straight to that.

I changed in your theme just the above rule and at zoom 15 start the symbol appears and the map is the same with Mapsforge:

![cruiser_gl](https://cloud.githubusercontent.com/assets/3484020/19944344/302dbbaa-a144-11e6-9dd7-ce5ef77d6a38.png)

**Comment by Klaus-Tockloth** [comment]
Great ... your last screenshot shows exactly what I expect.

> How did you go to that zoom in VTM, with mouse wheel?

Yes, I switch the zoomlevels with the mouse wheel (btw: I'm on OS X).

> Can you try with N, M buttons or with Shift + mouse drag slowly?

With the N and M keys it works as expected (see screenshots).
Very peculiar: After that, also zooming with the mouse wheel works as expected.

But this reproduces the defect for me:
- loading map AAA
- loading map BBB
- loading map AAA

Maybe an initialization problem.

![bildschirmfoto 2016-11-03 um 17 30 45]
(https://cloud.githubusercontent.com/assets/5493128/19976175/fcbcf6e0-a1ee-11e6-8a78-78424a3f533a.jpg)

![bildschirmfoto 2016-11-03 um 17 30 53](https://cloud.githubusercontent.com/assets/5493128/19976186/0819e638-a1ef-11e6-8748-e2898031f72c.jpg)

**Comment by devemux86** [comment]
Desktop mouse wheel or Android zoom buttons or any other control performing zoom in large steps, progress from current scale by a fixed percentage, so the start clearly affects the result.

_BTW check Cruiser GL keyboard shortcuts in Help menu, they're quite handy!_

Are maps AAA and BBB from different regions?
Then after loading, the map zooms appropriately to show most of it and probably ends somewhere in between levels.
So subsequent zooms via the controls are not guaranteed to end to fixed levels.

**Comment by Klaus-Tockloth** [comment]
> Are maps AAA and BBB from different regions?
Yes.

**Comment by devemux86** [comment]
@Klaus-Tockloth can we close this?

I don't see VTM zoom having anything wrong, the fixed zoom levels are the same with Mapsforge.

**Comment by Klaus-Tockloth** [comment]
Yes I agree, this issue can be closed. The VTM library is working compatible with the Mapsforge lib. The point here was an issue within the app (which uses VTM): The app must ensure the correct handling of the continous zoomlevel feature.

**Comment by devemux86** [comment]
Ok I'm closing this, thanks @Klaus-Tockloth for the useful conversation!
Regarding the app will need to think a little for future improvements.
