### ISSUE TITLE
Semi-transparent SVG icons

### ISSUE THREAD

**Issue by Klaus-Tockloth** [mapsforge/vtm#218]
It seems that transparency for SVG objects isn't working the same way in VTM as in Mapsforge.

Mapsforge (semi-transparent green dots (icons for trees)):
![bildschirmfoto 2016-10-30 um 07 16 31](https://cloud.githubusercontent.com/assets/5493128/19834838/3fa2ba16-9e71-11e6-899e-753c8a402790.jpg)

VTM (non-transparent green dots):
![bildschirmfoto 2016-10-30 um 07 15 03](https://cloud.githubusercontent.com/assets/5493128/19834840/4afc337e-9e71-11e6-991a-3608baa46383.jpg)

**Comment by devemux86** [comment]
It seems that semi-transparent SVG can be seen, but not always..
At the start of a zoom level they appear solid and as we zoom in they become semi-transparent.
Also they appear fine in large zooms like 18+?

Start of zoom 17:
![1](https://cloud.githubusercontent.com/assets/3484020/19835577/d8ec6b50-9e93-11e6-9c6c-5ee555b4cd9f.png)

End of zoom 17:
![2](https://cloud.githubusercontent.com/assets/3484020/19835578/dca14b62-9e93-11e6-93f4-61636416fb2e.png)

**Comment by devemux86** [comment]
Can discuss in [forum](https://groups.google.com/group/mapsforge-dev) and if there is interest from community to contribute.
