### ISSUE TITLE
MapFileTileSource zoom level improvements

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#219]
`MapFileTileSource` has a max zoom level 17 for tiles rendering, which can be limited to users.
We could make that optional and think about increasing default max zoom to 18?

Note: this has nothing to do with map zoom limits, as map view can zoom to our will using that data, e.g. zoom 20 and beyond.

Related zoom conversation in https://github.com/opensciencemap/vtm/issues/122.

**Comment by devemux86** [comment]
I added parameters for the zoom levels but didn't increase the default max zoom to 18, as then we have artifacts at tile seams (see https://github.com/opensciencemap/vtm/issues/122 for details).

**Comment by andreynovikov** [comment]
I have read that having separate zoom levels beyond 14 for vector tiles has little sense. What should be done to address these issues is separation of data extraction and rendering. Currently if zoom level is beyond max data source zoom level the rules for max zoom level are applied, but not for current zoom. I propose to make it use the data from max data source zoom level but to apply rendering rules for current zoom level.

**Comment by devemux86** [comment]
Actually 14 is the last default base zoom level in Mapsforge maps, so what you propose is valid.
Though online vector tiles (`.vtm` or `.mvt`) extract data from larger zooms too?

And indeed current VTM data read & render zooms are not independent, so we have #216.
@hjanetzek can confirm that.

BTW theme creators should be allowed to work as before and set min zoom in tag-mapping >14, right?

**Comment by andreynovikov** [comment]
Yes, this is what I propose. For instance I have a base map data source (in separate layer) with max zoom level of only 8. It renders nicely on zoom 20 but relevant theme rules are not applied - VTM just scales what was set for zoom level 8.

**Comment by andreynovikov** [comment]
I'm currently implementing a new data source for my app. It will be limited with zoom 14. So this issue becomes important to me. I want to address it shortly. Any ideas and recommendations on how to separate data extraction and rendering?

**Comment by devemux86** [comment]
Do you mean only for Mapsforge map files or generally for all vector map sources?

**Comment by andreynovikov** [comment]
For all vector tile sources. But it looks like it's very complicated...
