### ISSUE TITLE
PathLayer (regular) reverses

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#220]
[PathLayer](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/layers/PathLayer.java) (regular) with a directed texture (e.g. arrow) shows reversed line segments at large zooms.
Probably `LineClipper` plays a role to that?

Note that JTS [PathLayer](https://github.com/mapsforge/vtm/blob/master/vtm-jts/src/org/oscim/layers/vector/PathLayer.java) works without issues.

**Comment by devemux86** [comment]
Can use `LineTexTest` replacing with regular `PathLayer` and `LineStyle`.
Depending on latitude, the directed textures are reversed from around zoom 10.

Correct direction:
![1](https://user-images.githubusercontent.com/3484020/38794752-c7b4fb58-415e-11e8-9c23-f23a4f1eda59.png)

Reversed direction:
![2](https://user-images.githubusercontent.com/3484020/38794753-c7e7ac92-415e-11e8-823e-d5527f9d9842.png)

**Comment by Gustl22** [comment]
Problem seems to be that [line length](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/renderer/bucket/LineTexBucket.java#L171) in LineTexBucket is out of range of Short.MAX_VALUE at higher zoom levels.

Thus problem can happen in jts `PathLayer`, too, but never would, cause of smaller clipping.

I did not find out why there's need of `lineLength` or where the rendering calculations take place. But theoretically this param is redundant.

**Comment by devemux86** [comment]
Note that line stipples and textures didn't exist in master VTM.
They were introduced in #105 based on work by @hjanetzek.

**Comment by Gustl22** [comment]
@devemux86: As I can see you're much more experienced in OpenGL programming than me. Can you give me a hint where the [`lineLength`](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/renderer/bucket/LineTexBucket.java#L171) is used in GL render code (or attribute in shaders) after adding it to vertex items. I spent hours (also in Googles gapid) and didn't catch the concept.

**Comment by devemux86** [comment]
@hjanetzek wrote that part of VTM, so I need also to search first to find out that. :slightly_smiling_face:

**Comment by Gustl22** [comment]
No sweat. Thought you might have an idea :slightly_smiling_face:

**Comment by devemux86** [comment]
Fixed via #529.
