### ISSUE TITLE
Geometry simplification in zoomlevel 11 and below

### ISSUE THREAD

**Issue by Klaus-Tockloth** [mapsforge/vtm#223]
It seems that in zoomlevel 11 and below a geometry simplification takes place:

![bildschirmfoto 2016-11-01 um 14 25 26](https://cloud.githubusercontent.com/assets/5493128/19891263/9cff5eba-a03f-11e6-93f3-33aa8a68088e.jpg)

![bildschirmfoto 2016-11-01 um 14 25 58](https://cloud.githubusercontent.com/assets/5493128/19891270/a39f3d9e-a03f-11e6-8d67-d48881d399cd.jpg)

Is this a (performance?) optimization feature or a defect?

**Comment by devemux86** [comment]
Mapsforge maps (created with default map-writer options) have simplified geometries for zoom levels <12.
That can be seen also via regular software rendering with Mapsforge clients.
Or do you see something different here?

For reference VTM had enabled extra simplification, which I have already disabled it in #39.

**Comment by Klaus-Tockloth** [comment]
You are right, mapsforge also simplifies geometry. This leads to a "poor" looking map. 

Questions:
- Is it possible to reduce the starting level of simplification in vtm (e.g. to zl 10)?
- Is it possible to reduce the simplification (smoothing) effect in vtm?
- Is there a simplification factor which can be controlled by the theme (e.g. as header option)?

The challenge is to find a good balance between simplification and performance.

**Comment by devemux86** [comment]
I'm afraid simplification can be controlled with map writer, not in map readers.
Both libraries read unmodified what's inside the map files, they cannot improve a geometry if it's already stored simplified.

Regarding map-writer, a new option was added recently to control simplification max zoom, see https://github.com/mapsforge/mapsforge/issues/892.
Or do you mean we make VTM to read only the unsimplified 3rd zoom interval from map files?

An alternative could be omitting the first 2 simplified zoom intervals 0-7 and 8-11 in map building. Though performance needs to be checked here too.

BTW I can see worse rendering with VTM in 1st zoom interval 0-7, simply because OpenGL cannot use stroke width to fill voids, like Mapsforge does with software rendering.

**Comment by Klaus-Tockloth** [comment]
> Regarding map-writer, a new option was added recently to control simplification max zoom, see mapsforge/mapsforge#892.

I think that the brand new map-writer option "simplification-max-zoom=zoomlevel" will do the job. Where can I find a map-writer 0.7 jar file (with dependencies) for some experiments with the new option?

And I see in the docs that there is an option for controlling the simplification (default: simplification-factor=2.5) too. If I want to decrease smoothing, in which direction do I have to change the factor?

> An alternative could be omitting the first 2 simplified zoom intervals 0-7 and 8-11 in map building. Though performance needs to be checked here too.

How to achieve this? And what are the expected consequences?

**Comment by devemux86** [comment]
Mapsforge and VTM snapshots are now published automatically with every commit at [Sonatype OSS Repository Hosting](https://oss.sonatype.org/content/repositories/snapshots/org/mapsforge/). Just take the latest jar with dependencies.

Regarding `simplification-factor` try larger values for more simplification.

To use a different zoom interval configuration use the map-writer option: `zoom-interval-conf=14,12,21`. Performance would be hit as in small zoom levels many high detailed geometries will be processed.

**Comment by Klaus-Tockloth** [comment]
> Regarding simplification-factor try larger values for more simplification.

The map-writer option "simplification-factor" did the job for me:

Before (simplification-factor=2.5):
![bildschirmfoto 2016-11-01 um 20 57 54](https://cloud.githubusercontent.com/assets/5493128/19905288/5818f180-a076-11e6-8547-79b17d9b4a5f.jpg)

After (simplification-factor=0.5):
![bildschirmfoto 2016-11-01 um 20 58 36](https://cloud.githubusercontent.com/assets/5493128/19905293/6060d9c0-a076-11e6-8438-0f0b629c93b1.jpg)

I think this issue can be closed.

**Comment by devemux86** [comment]
So do you think producing Freizeitkarte maps from now with `simplification-factor=0.5`?

**Comment by Klaus-Tockloth** [comment]
> So do you think producing Freizeitkarte maps from now with simplification-factor=0.5?

Yes, in the future I will change the simplification-factor. Finding a good value requires further testing. We have to approach a good balance between rendering more details and increasing the map file size only slightly.

**Comment by devemux86** [comment]
@Klaus-Tockloth thanks for the info, when you have some results please inform us, as your experience in map building is valuable. :slightly_smiling_face:
