### ISSUE TITLE
Intel(R) HD Graphics 3000 renders only names and icon

### ISSUE THREAD

**Issue by Klaus-Tockloth** [mapsforge/vtm#228]
Cruiser GL 1.2.13 only renders names (cities, streets, ...) and poi icons but no other map element:

![cruiser-gl-only-citynames](https://cloud.githubusercontent.com/assets/5493128/20005980/983cd314-a295-11e6-9242-56c1c40972b8.PNG)

System details:
```
C:\Downloads\cruiser>java -version
java version "1.7.0_111"
Java(TM) SE Runtime Environment (build 1.7.0_111-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.111-b13, mixed mode)

C:\Downloads\cruiser>systeminfo
Betriebssystemname:                            Microsoft Windows 7 Enterprise
Betriebssystemversion:                         6.1.7601 Service Pack 1 Build 7601
Systemhersteller:                              LENOVO
Systemmodell:                                  4242BT8
Systemtyp:                                     x64-based PC
Prozessor(en):                                 1 Prozessor(en) installiert.
                                               [01]: Intel64 Family 6 Model 42 Stepping 7 GenuineIntel ~2501 MHz
BIOS-Version:                                  LENOVO 8AET33WW (1.13 ), 24.02.2011
Gesamter physikalischer Speicher:              8.079 MB
```
![graphics-hardware](https://cloud.githubusercontent.com/assets/5493128/20006016/d942ddcc-a295-11e6-95b1-68df6f2595da.png)

**Comment by devemux86** [comment]
Discussion from [forum](https://groups.google.com/forum/#!topic/cruiser-users/Fxmzt6m4LkU).

It's worth mentioning that I use VTM with Intel(R) HD Graphics 3000 on Linux and Mesa 11.2.0 without problems.

**Comment by Klaus-Tockloth** [comment]
Driver version (maybe helpful):

![driver](https://cloud.githubusercontent.com/assets/5493128/20007522/eae7303a-a29c-11e6-89f4-c80d08f0c007.PNG)

**Comment by devemux86** [comment]
I think there is newer driver at [Intel](https://downloadcenter.intel.com/product/81500/Intel-HD-Graphics-3000) worth trying.

**Comment by devemux86** [comment]
@Klaus-Tockloth any news, probably with newer driver?

**Comment by printmaps** [comment]
Sorry - no news yet and no news in the future. I don't have the system with HD Graphics anymore.

**Comment by devemux86** [comment]
Closing, please reopen if needed.
