### ISSUE TITLE
Eclipse: import javax.annotation.CheckReturnValue cannot be resolved

### ISSUE THREAD

**Issue by wolfgang-ch** [mapsforge/vtm#229]
This is the procedure to get the errors in Eclipse 4.6.1 with Gradle 2.14.1 plugins:

* Clone VTM git
* Create Eclipse general project with the VTM folder as root
* Add a Gradle nature to this project -> this will automatically
  - Create all .settings .classpath and .project files for all folders which contain a build.gradle file
  - Download all dependencies
  - Rename the VTM root project to vtm-parent

When this has finished then the above error will occure

This issue is discussed in https://github.com/mapsforge/vtm/pull/227

**Comment by devemux86** [comment]
I built VTM with Eclipse successfully with Gradle Tasks view, which recognizes the `providedCompile` configuration.
But Eclipse does not seem to add that dependency in its classpath so its own build fails.

I would like to not fill build scripts with IDE specific custom code, preferably we could remove the annotations.

**Comment by devemux86** [comment]
From [Gradle 2.12](https://docs.gradle.org/2.12/release-notes#support-for-declaring-compile-time-only-dependencies-with-java-plugin) there is support for declaring compile time only dependencies with Java plugin, we could check that.

**Comment by devemux86** [comment]
I pushed the change with the new Gradle configuration, works here with AS / Eclipse.

@wolfgang-ch please try it too in your environment.

**Comment by devemux86** [comment]
BTW an easier procedure to open a Gradle project (like VTM) in Eclipse is to use the Import wizard and select the project folder, using also the default Gradle wrapper option.

**Comment by wolfgang-ch** [comment]
- I created a new workspace in Eclipse
- Cloned VTM git
- Imported as Gradle Project with the import wizard
- 0 errors occured :+1:
