### ISSUE TITLE
Mapsforge map artifacts for zoom >17

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#231]
When we use a Mapsforge map with max rendering zoom >17, like `new MapFileTileSource(0, 18)`, we have artifacts at tile grid lines.

![artifacts](https://cloud.githubusercontent.com/assets/3484020/20068875/0c6ac1ee-a523-11e6-89c0-d12235651c65.png)

**Comment by devemux86** [comment]
Reference https://github.com/opensciencemap/vtm/issues/122

**Comment by devemux86** [comment]
After @hjanetzek 's [comment](https://github.com/mapsforge/vtm/pull/230#issuecomment-258860414), possible cause seems to be the `TileClipper` used in `MapDatabase`.

Now wondering what's its benefit specifically for Mapsforge maps, e.g. if we disable it, the artifacts disappear.
Also just below we have additional map element simplification.

**Comment by devemux86** [comment]
@andreynovikov can you test all these also from your side?

**Comment by devemux86** [comment]
I changed `TileClipper` buffer to half the tile size, like most tile buffers.
Nicely also described in [TileMill Metatiles](https://tilemill-project.github.io/tilemill/docs/guides/metatiles/), hoping it isn't too much. :slightly_smiling_face: 

Rendering in zoom >17 with `new MapFileTileSource(0, 18)` seems fine now, need good testing by all.

**Comment by devemux86** [comment]
There are still artifacts (1) at very large zooms >20 and elements disappear (2) if most of tile is outside screen.

Artifacts:
![1](https://cloud.githubusercontent.com/assets/3484020/20075567/5d2ebeae-a53d-11e6-9802-7e4135de8a4d.png)

Disappearance:
![2](https://cloud.githubusercontent.com/assets/3484020/20075571/605367ba-a53d-11e6-8f89-701e0e07498f.png)

**Comment by devemux86** [comment]
Having half tile size as `TileClipper` buffer clearly hurts performance! :slightly_frowning_face:

**Comment by devemux86** [comment]
I changed `TileClipper` buffer to be scaled on dpi.

**Comment by andreynovikov** [comment]
Sorry, didn't catch, what should I test?

**Comment by devemux86** [comment]
@andreynovikov do you use `MapFileTileSource` with default max zoom or >17 and see any artifacts?

I wonder of the purpose of tile clipping [here](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/tiling/source/mapfile/MapDatabase.java#L889-L892) and changed it to have a scaled buffer.

Also in next [line](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/tiling/source/mapfile/MapDatabase.java#L893) we have a simplify call, seems a bit redundant in Mapsforge maps?

**Comment by devemux86** [comment]
Also in Mapsforge we had added extra checks in [processPOIs](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-reader/src/main/java/org/mapsforge/map/reader/MapFile.java#L642-L647) and [processWays](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-reader/src/main/java/org/mapsforge/map/reader/MapFile.java#L783-L793) for include only the elements in the requested tiles.

**Comment by andreynovikov** [comment]
No, I use default and do not have such issues.

**Comment by devemux86** [comment]
Large query zoom levels have also polygon artifacts as reported in #391.

The buildings cause that issue (as seen in urban areas), e.g. disabling them in the theme eliminates any artifacts.

Reason is in `MapDatabase.processWays` there is a check to not use `TileClipper` for buildings, probably due to https://github.com/opensciencemap/vtm/issues/124.

**Comment by devemux86** [comment]
Pushed in `MapDatabase` at large query zoom levels:
- Clip everything (also buildings)
- Use enlarged clip buffer
