### ISSUE TITLE
MarkerItem label rendering

### ISSUE THREAD

**Issue by NikosSkouteris** [mapsforge/vtm#237]
(Great work!)

Is it possible to add a label under a MarkerItem? I'd like to add bullets as millestones to a track/path and put a label under each bullet.

Thanks in advance!

**Comment by devemux86** [comment]
I'm afraid there is no currently such functionality.
That would need enhancements probably in marker renderer.

**Comment by NikosSkouteris** [comment]
I see. Any advice to make it in another way?

**Comment by devemux86** [comment]
An intermediate solution could be adding text on marker symbol, e.g. with an info bubble.

**Comment by NikosSkouteris** [comment]
Yes, I think about it but it's too difficult for the user to guess that a bullet has info.

Anyway, thanks a lot!

**Comment by devemux86** [comment]
Let's leave it open, as it's a feature asked before and we could implement it in the future.

**Comment by ocsike** [comment]
+1

**Comment by saturngod** [comment]
+1

**Comment by Longri** [comment]
I will try it!

**Comment by telemaxx** [comment]
+1
