### ISSUE TITLE
Problems with drawing Polygones

### ISSUE THREAD

**Issue by braandl** [mapsforge/vtm#239]
I am trying to draw filled polygons in a VectorLayer but it fails.

```
VectorLayer gl = new VectorLayer(vtmMapReference.get().getMap());
Style style = (Style.builder()
                                .buffer(0.5)
                                .fillColor(Color.RED)
                                .fillAlpha(0.8f)
                                .strokeColor(Color.RED)
                                .strokeWidth(10f)).build();

... adding Points as LatLngs ...

PolygonDrawable pd = new PolygonDrawable(gp, style);
gl.add(pd);
gl.update();
getMap().layers().add(gl);
```

The result are the boundary lines of my polygones and a little artifact in the middle of the map.
Any Ideas why filling the Polygon does not work as expected?

Thanks for your help!

**Comment by devemux86** [comment]
For questions please use the forum:
https://groups.google.com/group/mapsforge-dev

**Comment by braandl** [comment]
Ok, I will. I concidered this to be a bug in the VectorLayer, so I did post it here.
