### ISSUE TITLE
Render themes new SVG resources

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#251]
Review SVG symbols opting for "positive + white glow" variant.

**Comment by devemux86** [comment]
Should be done in parallel with https://github.com/mapsforge/mapsforge/issues/904.

**Comment by andreynovikov** [comment]
When I try to open new SVGs with Inkscape (SVG editor I've always used) it silently closes. I've checked, files are ok. Any idea on what's wrong with Inkscape or what other SVG editor to use?

**Comment by devemux86** [comment]
Interesting and here Inkscape crashes too!

Seems it doesn't like the new "white glow" rules.. :slightly_frowning_face: 
For example if we remove the [4th line](https://github.com/mapsforge/vtm/blob/master/vtm-themes/resources/assets/symbols/transport/parking.svg?short_path=e290e60#L4) from `parking.svg` then it opens.

Note that svg are also cleaned with [SVG Cleaner](https://github.com/RazrFalcon/svgcleaner-gui) for better compatibility with svg libraries.

@eartrumpet any hint on this?

**Comment by andreynovikov** [comment]
Also, some symbols missing that are referenced in default style. For instance `hairdresser`.

**Comment by devemux86** [comment]
I double checked only the active symbols in the themes (e.g. this is commented).
But we could add more now as we process them.

Regarding Inkscape, could you mention it also in relevant forum [topic](https://groups.google.com/forum/#!topic/mapsforge-dev/zKUqwp5-K8w)?
(forum is usually watched more by theme creators)

**Comment by eartrumpet** [comment]
I'm aware of it. This happens with some files after using SVG cleaner. I have the original soure files which were created/edited in Inkscape, but I only use cleaned versions in themes, for compatibility and size reasons. In my experience they work well with all enviroments I tested (mapsforge on Android/Java, Locus own SVG engine).

**Comment by andreynovikov** [comment]
May be put a reference to the source files then? (May be in wiki?) Sometimes I want to modify/add something in the icons but no I can not do it.

**Comment by devemux86** [comment]
- The original source of SJJB icons is always their [site](http://www.sjjb.co.uk/mapicons/)
- In themes module we maintain a cleaned collection (made a long time ago when Mapsforge migrated to SVG)

That time we saw with other theme creators (like @eartrumpet mentioned), that svg files as produced by Inkscape or Illustrator contain too much "noise" data, making them not compatible with usual svg readers.

Indeed we could mention all these somewhere (BTW we don't have yet a theme wiki in VTM). :slightly_smiling_face:

**Comment by eartrumpet** [comment]
It's also possible to make those SVG files work with Inkscape again by removing the "white glow" with a text editor (every path with opacity="0.8" stroke="#ffffff"  stroke-width="64")

**Comment by devemux86** [comment]
@eartrumpet indeed that's what I [saw](https://github.com/mapsforge/vtm/issues/251#issuecomment-263211893) too.
Maybe Inkscape doesn't like some tag from "white glow"?

**Comment by eartrumpet** [comment]
> Maybe Inkscape doesn't like some tag from "white glow"?
Strange thing is, that I created the "white glow" with Inkscape in the first place.
Maybe SVG Cleaner removes/adds something Inkscape misses. But I didn't investigate further, as I can live with it as long as everything renders fine on the maps.

**Comment by andreynovikov** [comment]
@eartrumpet Can you process all the icons or share the script you did it with?

**Comment by eartrumpet** [comment]
> Can you process all the icons or share the script you did it with?

Sorry, no script as a lot of the original SJJB icons are not well constructed and needed clean up/simplification by hand, so manually adding of the white glow was quicker than making a script.

**Comment by devemux86** [comment]
A quick guide (with a text editor):
- Take already clean icon from [collection](https://github.com/mapsforge/vtm/tree/master/vtm-themes/icons/symbols)
- Remove the background color rule
- Change the symbol fill color
- Duplicate its geometries, adding first all "white glow" rules (like [this](https://github.com/mapsforge/vtm/blob/master/vtm-themes/resources/assets/symbols/transport/parking.svg?short_path=e290e60#L4))
