### ISSUE TITLE
Improved gestures

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#253]
Integrate an improved gestures system:
- fixes gesture handling like the problem with long press still firing on drag zoom
- lets adding new gestures
- introduces triple tap gesture
- introduce two finger tap gesture for zoom out

Since it involves core gesture changes and needs thorough testing by all, I'll add it as an additional option, keeping also the default gestures system for safety.

EDIT: You need to set `Map.NEW_GESTURES = true;` before map view initialization for the new gestures system to be used.

**Comment by devemux86** [comment]
See PR #249 by @andreynovikov.

**Comment by devemux86** [comment]
I added new samples in `vtm-android-example` and `vtm-playground` for testing the improved gestures.

@Longri could you test them in iOS too?

**Comment by devemux86** [comment]
@andreynovikov I see that the "double tap zoom" and the "quick scale (double tap + swipe)" gestures often fail to be recognized.

**Comment by andreynovikov** [comment]
You have disabled logging for some reason, so are you sure they are not recognized? May be they are not processed? See: https://github.com/mapsforge/vtm/pull/261
With that fix I do not have any problems with zooming at all.

**Comment by devemux86** [comment]
>You have disabled logging for some reason

Sorry about that, I had seen your [Remove extra logging](https://github.com/mapsforge/vtm/pull/249/commits/a371f338a27e72ece590bc316b12bba61652860e) commit and removed the rest too.
Do we need it beyond development? (please enable it again if you wish)

**Comment by andreynovikov** [comment]
No, we don't. I have removed it completely in last PR.

**Comment by devemux86** [comment]
(I have not debugged the new code so far)
I merged also #261, situation may be improved but the missed gestures still happen (for reference with default gestures, I don't have any missed).

Something else if may helps:
I notice that in new gestures system, we cannot any more perform consecutive "double tap zoom" very quickly. The map doesn't zoom in between and when we stop all the double taps then the map zooms one time for the last double tap.
In default gestures system, when we continuously "double tap" the zoom happens all the times and just the animations stop for the new one to begin.

**Comment by devemux86** [comment]
I created a topic in the [forum](https://groups.google.com/forum/#!topic/mapsforge-dev/YHnj6ebQE0A) about the improved gestures implementation for broader visibility by users and testing.

**Comment by andreynovikov** [comment]
We definitely have to turn logging back on. :) Looks like you face triple-tap gesture. We may make it configurable (turn on|off with off by default, I agree that it's not a common practice to use it).

**Comment by devemux86** [comment]
>We definitely have to turn logging back on. :)

You're right, you want to add again your previous logging?

>Looks like you face triple-tap gesture.

That could explain also the missed "quick scale" if it has kept a tap from previous gesture.

>We may make it configurable (turn on|off with off by default, I agree that it's not a common practice to use it).

:+1: 

BTW triple tap does not have a result in VTM, is it for external use only?

**Comment by andreynovikov** [comment]
> You want to add again your previous logging?

I will.

>  Triple tap does not have a result in VTM, is it for external use only?

Yes.

**Comment by Longri** [comment]
I have tested the new gestures under iOS and it works properly only if I execute a this.updateMap (true) in the Map.handleGesture (Gesture g, MotionEvent e) method.

**Comment by devemux86** [comment]
@Longri thanks for the feedback!

Have you checked my comments above, [here](https://github.com/mapsforge/vtm/issues/253#issuecomment-263264010) and [here](https://github.com/mapsforge/vtm/issues/253#issuecomment-263275989)?

**Comment by devemux86** [comment]
And be sure to use the improved gestures and not the default ones (see my 1st post for how to enable them, where you'll have also "two finger tap" zoom out).

**Comment by Longri** [comment]
Yes, I am sure I have switched on the new Gesture.
Map.NEW_GESTURES = true; Called before the map is created.

But double tab does not work, neither on iOS nor on Android!

I use only GDX! So android-gdx!

**Comment by devemux86** [comment]
On GDX the double tap was not implemented from the start.

**Comment by Longri** [comment]
Ok, can you give me a hint, so I will look at it

**Comment by devemux86** [comment]
See #263. :slightly_smiling_face:

**Comment by Longri** [comment]
👍 I will check later!

**Comment by devemux86** [comment]
@andreynovikov any plans to make the triple tap optional?
(to not mix with other tap gestures and make them not working properly)

**Comment by devemux86** [comment]
Closing here, I opened #280 for the tap problems.
