### ISSUE TITLE
If symbol is applied to area it is tinted

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#254]
Symbol is tinted (colors are multiplied) by area fill color. As most areas are light applied symbols look like semitransparent. But I have tested it with solid red color and have found out that colors are multiplied. I consider this to be a bug, not a feature, symbols applied to point and area should look identical.

**Comment by devemux86** [comment]
Can you provide some screenshots to understand better the issue?

**Comment by andreynovikov** [comment]
Hotel applied to point and to area (building)
![screenshot_20161125-141404](https://cloud.githubusercontent.com/assets/2943625/20623720/679343f4-b322-11e6-9e80-9ac7b1060e17.png)

Playground (with red as a area fill Colorado test)
![screenshot_20161125-141338](https://cloud.githubusercontent.com/assets/2943625/20623758/9fb37a6a-b322-11e6-8092-6860d3bdebd3.png)

**Comment by devemux86** [comment]
Thanks for the images, indeed this shouldn't be happening.

And probably related with #218.

**Comment by devemux86** [comment]
Can discuss in [forum](https://groups.google.com/group/mapsforge-dev) and if there is interest from community to contribute.
