### ISSUE TITLE
Missing Android example for selectable map styles

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#255]
It would be nice to have an Android example to see map styles in action. Like https://github.com/mapsforge/vtm/commit/afd03809e8bd060bde9421276f94934fb2f87008

**Comment by devemux86** [comment]
I agree, it was just easier to implement it on desktop using keyboard for selecting the styles. :slightly_smiling_face:

**Comment by devemux86** [comment]
Related to #93.
