### ISSUE TITLE
vtm-desktop decouple libGDX backends

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#259]
Decouple libGDX backends from `vtm-desktop` in order to allow use of other alternatives.

**Comment by Longri** [comment]
-1

**Comment by devemux86** [comment]
@Longri -1 or +1 ?

**Comment by Longri** [comment]
-1!
LibGdx is a nice active developed library.

**Comment by devemux86** [comment]
I never said to remove libGDX!
Just to make changing libGDX desktop backends more flexible and not tied to a single one.

e.g. try LWJGL3 or JGLFW backend along with LWJGL

**Comment by Longri** [comment]
Ok

**Comment by devemux86** [comment]
Implemented via #714.
