### ISSUE TITLE
VTM clips Mapsforge map at zoom level 8

### ISSUE THREAD

**Issue by vk45** [mapsforge/vtm#264]
I testet a self build map around Kalskrona in south sweden.

On zoom 8 only a small part of the map is shown in Cruiser-GL with the default and osmarender renderer,
no problems with Cruiser on zoom 8.

I add two screenshots.
![cruiser-gl-west_ostsee_2016_12_04_07_05_20161206_112843](https://cloud.githubusercontent.com/assets/5665521/20924086/f1e8d3e4-bbaf-11e6-8e6c-0d17dc5f1e04.png)
![cruiser-west-ostesee_2016_12_04_07_07_20161206_113105](https://cloud.githubusercontent.com/assets/5665521/20924087/f58053a6-bbaf-11e6-89f4-0a1a4b5375a0.png)

the map is available at http://osm.franken.de/offline-maps/VTM_Testmap_2016_12_04/
regards
Victor

**Comment by devemux86** [comment]
Thanks for the sample.
I think I have seen that behavior before.

**Comment by devemux86** [comment]
Fixed via #526.
