### ISSUE TITLE
vtm-web-app crashes with building layer

### ISSUE THREAD

**Issue by schedul-xor** [mapsforge/vtm#266]
Conditions

Browser | Windows | OSX | Linux
---|---|---|---
Chrome | **Crashes** | **Crashes** | No problem
Firefox | No problem | Not checked yet | No problem
Safari | - | No problem | -
IE | No problem | - | -
Edge | Not checked yet | - | -

It seems that the problem is in the building layer rendering, because it doesn't crash when disabling the building layer.

**Comment by devemux86** [comment]
What graphics cards and drivers have the devices of those tests?

**Comment by schedul-xor** [comment]
Running vtm-web-app on the latest Chrome won't crash anymore.
