### ISSUE TITLE
Cache rendered map tile to framebuffer

### ISSUE THREAD

**Issue by schedul-xor** [mapsforge/vtm#267]
Vector map tile rendering costs 3000-4000 GL operations (60-70% CPU power). This was not a problem when maps were not rendered per frame, only rendered when MapView is modified (by setting `isContinuousRendering` to false). But how about when you want to animate something on the field?

It's better to cache the rendered vector tiles if possible. How about using FrameBuffer?

**Comment by devemux86** [comment]
Do you mean on browser?

**Comment by schedul-xor** [comment]
Of course on browsers, but for other platforms too.

**Comment by devemux86** [comment]
Not all platforms require a libGDX backend, e.g. on Android it's optional, as we can use directly the OpenGL ES.

BTW for continuous rendering on Android see also #141, which can be caused from a layer refreshing, like the location layer.

**Comment by devemux86** [comment]
Additionally only on Android we have implemented a tile cache (see `ITileCache`) using the platform SQLite.

**Comment by schedul-xor** [comment]
I've looked in vtm-android/src/org/oscim/android/cache/TileCache.java . To my understanding, this `TileCache` caches the downloaded binary data (ex. .vtm binary format), which prevents downloading the same data again from server. I'm sure this is useful, but I'm talking about something different.

What I'm searching is the way to decrease GL calls per frame. I want to draw something that's moving in the map time by time, so continuous rendering is a must. In most cases the showing tiles don't change so much, so caching the rendered tile image to some texture buffer should save calling too much GL calls.

**Comment by devemux86** [comment]
Let's have such discussions in [forum](https://groups.google.com/group/mapsforge-dev) first to not fill the repository with abandoned issues, unless a feature or problem appears. :slightly_smiling_face:
