### ISSUE TITLE
Circle map style (GL points)

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#268]
OpenGL circles via GL points, enabled via `GLAdapter.CIRCLE_QUADS = false;`.

- [x] Anti-aliasing
- [x] Stroke
- [ ] Scale radius
- [ ] Billboards

**Comment by devemux86** [comment]
Current implementation:
![circle_points](https://cloud.githubusercontent.com/assets/3484020/21092168/7633fee2-c053-11e6-94bf-3fc76c342c24.png)

**Comment by devemux86** [comment]
I pushed the anti-aliasing:
![circle_points](https://cloud.githubusercontent.com/assets/3484020/21153328/a94a2b1a-c172-11e6-9456-0e56f4f81b52.png)

**Comment by devemux86** [comment]
I pushed the stroke implementation:
![cricle_points](https://cloud.githubusercontent.com/assets/3484020/21179644/a269f358-c1fd-11e6-8590-9b98109c9134.png)

**Comment by mpelesh** [comment]
Hi @devemux86, I set have a question regarding circle radius. I set my circle radius to 400 in CircleStyle (half of my screen width), but CircleBucket renders a circle with diameter of approx 500 pixels (~0.63 ratio) vs expected 800. GLViewport ratio is 0.73. However circle center seems to be in a correct location. What is a proper way to have CircleBucket render a circle with a radius I need?

**Comment by devemux86** [comment]
This is still work in progress, like there isn't currently radius scaling. So exact radius is not fixed yet and appears smaller than normal.

**Comment by devemux86** [comment]
Note: for OpenGL circles via GL points, usually the *max* size is limited by GPU.
OpenGL circles via GL quads (#269) are more suitable, but still need work.

**Comment by mpelesh** [comment]
@devemux86, thank you for the explanation.

**Comment by Gustl22** [comment]
I don't see circles rendered in playgrounds `CircleTest` with `GLAdapter.CIRCLE_QUADS = false;`. Quads work.

**Comment by devemux86** [comment]
`CircleTest` declares in its `main` method the `GLAdapter.CIRCLE_QUADS` parameter.
With `false` works, with `true` not as it's not fully implemented.

**Comment by Gustl22** [comment]
Ok can you check that? In my tests with `false` it shows only a blank black canvas. With `true` it shows some quads.

**Comment by devemux86** [comment]
Checked already and still works fine, like above [3rd image](https://github.com/mapsforge/vtm/issues/268#issuecomment-267007026).
Seems like GPU / driver problem?
GL points have their [issues](https://github.com/mapsforge/vtm/issues/268#issuecomment-358055101), a proper solution is more with quads.

**Comment by Gustl22** [comment]
Ok tested on Laptop, too and still see nothing. Seems to be an incompatibility with shader calculations / commands, as when I rewrite it to simply output the gl color, I can see some quads. When I understand more the shader, I'll try to fix.

**Comment by devemux86** [comment]
That's strange, because it works with me on all different machines / GPU / drivers have tested so far.

**Comment by Gustl22** [comment]
> I don't see circles rendered in playgrounds CircleTest

Problem fixed in #716.
