### ISSUE TITLE
get position when click on map

### ISSUE THREAD

**Issue by saturngod** [mapsforge/vtm#273]
How can I get the geo position (lat, long) from map view when I click on the map ?

**Comment by saturngod** [comment]
I found it https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/MarkerOverlayActivity.java

**Comment by devemux86** [comment]
That's right. :slightly_smiling_face: 

Also for questions please use our forum:
https://groups.google.com/group/mapsforge-dev

**Comment by anonym24** [comment]
How to do it with?

```
        val vectorTileLayer = map.setBaseMap(tileSource)
        map.setTheme(VtmThemes.DEFAULT)
        map.layers().add(BuildingLayer(map, vectorTileLayer))
        map.layers().add(LabelLayer(map, vectorTileLayer))
```
