### ISSUE TITLE
MapEventLayer2: taps not always work

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#280]
Improved gestures implementation (#253) has some problems:
- The "double tap zoom" and the "quick scale (double tap + swipe)" gestures often fail to be recognized
- The consecutive "double tap zoom" doesn't work, the map doesn't zoom for all but only for the last double tap

The cause of these seems to be the new "triple tap" gesture, we could make it configurable.

**Comment by andreynovikov** [comment]
Will make it configurable then...

**Comment by Gustl22** [comment]
Info: First part should have been solved via #493.
