### ISSUE TITLE
Map renders with black street labels, stops rendering, using two map instances on Android

### ISSUE THREAD

**Issue by bcg-alex** [mapsforge/vtm#281]
Hi, I'm currently integrating mapsforge-vtm to our app. It works quite straight forward and fulfills our needs mostly. But I discovered a rendering issue, working with two map instances (not in the same layout, but within the app context) and using a mapsforge tile source.
Screen:
![render_issue_nexus6](https://cloud.githubusercontent.com/assets/10597255/22012020/4dda4126-dc92-11e6-8bb8-dfa21efa36e5.png)
As you see on the topper left corner, the map renders badly too.

Implementation context:
One map located in a fragments layout, other in another activity layout, started by the fragments parent activity.

The issue appears if you navigate back from the scnd activity map  to the fragments map. (Can be reproduced with your demo app). It seems that removing the fragment, after starting the scnd activity, solves this issue (I guess the map instance gets gc'ed and frees some static members), which I use as a workaround so far, but removing the fragment (and re-adding it afterwards) might not be the intended implementation workflow for using two map instances ;)

Cheers, 
Alex

**Comment by devemux86** [comment]
I'm afraid it's a known issue, monitored in #194.

**Comment by bcg-alex** [comment]
Thanks, didn't see that.

**Comment by devemux86** [comment]
There is also the `MultiMapActivity` sample in `vtm-android-example` to test this behavior.
