### ISSUE TITLE
Leaflet and opensciencemap

### ISSUE THREAD

**Issue by sumrakx** [mapsforge/vtm#289]
Hi I learn the different tools to build 3D maps, and this library really like. I can rotate the map freely. Is it possible to link this library and js library Leaflet for further overlay markers and objects?

**Comment by devemux86** [comment]
There is HTML5/WebGL (using libGDX/GWT) support, check the various vtm-web modules.
I'm not aware for any other implementations using VTM..

For questions please use our [forum](https://groups.google.com/group/mapsforge-dev).
