### ISSUE TITLE
Carto CSS Support

### ISSUE THREAD

**Issue by ye-lin-aung** [mapsforge/vtm#291]
Is there any way to use Carto css rather than the default theme?

**Comment by devemux86** [comment]
There is [ThemeTest](https://github.com/mapsforge/vtm/blob/master/vtm-playground/src/org/oscim/test/ThemeTest.java) in `vtm-playground` using [RenderTheme](https://github.com/mapsforge/vtm/blob/master/vtm-jeo/src/org/oscim/theme/carto/RenderTheme.java) with CartoCSS styling.

For questions please use our [forum](https://groups.google.com/group/mapsforge-dev).
