### ISSUE TITLE
too many tile Loader process

### ISSUE THREAD

**Issue by ye-lin-aung** [mapsforge/vtm#292]
The TileLoader process increases after using for a long time.Is there any way to limit the number of threads ? 

<img width="771" alt="screen shot 2017-02-13 at 10 23 45" src="https://cloud.githubusercontent.com/assets/11737664/22870648/8ddd56f0-f1d7-11e6-9286-8e32a20684c1.png">

After using for a few hours and clicks the dialog fragment this error occurs.

https://code.google.com/p/android/issues/detail?id=32470  .

**Comment by devemux86** [comment]
You can set the number of loader threads (before adding the tile layer on map) via [setNumLoaders](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/layers/tile/TileLayer.java#L89) (default 4).

> After using for a few hours and clicks the dialog fragment this error occurs.

Do you use the proper resume / pause / destroy calls in app life cycle?
(check Android [MapActivity](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/MapActivity.java) sample)

**Comment by ye-lin-aung** [comment]
@devemux86  yes i use proper calls in app life cycle.I am loading offline files for  maps in fragment and preventing recreation of views via  configuration changes  with 
``` android:configChanges="screenSize|orientation" ```
but still happens

**Comment by ye-lin-aung** [comment]
@devemux86 The device restarts more frequent if I make more zoom in and zoom out frequently

**Comment by devemux86** [comment]
> The device restarts

Which device?
I have not seen such behavior so far.

Can you try `vtm-android-samples`, it has a fragment example to see what happens with it too or how it's different to your implementation?

**Comment by ye-lin-aung** [comment]
@devemux86  Its on Samsung Tab A  ( SMP - 355 ) and OPPO F1

**Comment by ye-lin-aung** [comment]
@devemux86  any updates for this issue

**Comment by devemux86** [comment]
Have you checked `vtm-android-example` in your devices to see if happens with that too?
Need to somehow reproduce the behavior in order to debug it.

**Comment by ye-lin-aung** [comment]
I am closing the issue since its working in example
