### ISSUE TITLE
Y Shape Style Bridge is not working

### ISSUE THREAD

**Issue by saturngod** [mapsforge/vtm#293]
In our city, Yangon, there is Y shape style over pass bridge. It's not showing well on Cruiser GL Android App.

![20170213_155805](https://cloud.githubusercontent.com/assets/135177/22877780/5f04a9e0-f205-11e6-8330-b1cd72dfa40c.png)

In OSM website, it's showing like below

<img width="221" alt="screen shot 2017-02-13 at 3 59 46 pm" src="https://cloud.githubusercontent.com/assets/135177/22877799/7ac98a4c-f205-11e6-97ba-bd9e0b8e2a14.png">

**Comment by devemux86** [comment]
Could you post also the OpenStreetMap link?

**Comment by saturngod** [comment]
https://www.openstreetmap.org/#map=18/16.81146/96.17088

**Comment by saturngod** [comment]
@devemux86 is there any update info about this issues ? Is it bug ?

**Comment by devemux86** [comment]
Probably need some improvement in render theme rules?

**Comment by devemux86** [comment]
What map do you use?
e.g. checking the OpenScienceMap tiles rendering seems normal:

![y](https://cloud.githubusercontent.com/assets/3484020/23116604/090d8bac-f754-11e6-94a2-086b1ed1d68e.png)

**Comment by saturngod** [comment]
@devemux86 , I am using .map file. OpenScienceMap tiles rendering image look like wrong , too. It's missing the bridge. There is Y Shape bridge in there.

!()[https://cloud.githubusercontent.com/assets/135177/22877799/7ac98a4c-f205-11e6-97ba-bd9e0b8e2a14.png]

**Comment by devemux86** [comment]
OpenScienceMap tiles could not be updated.
Need to check what happens with Mapsforge map, because Mapzen tiles appear good too (having similar theme):

![y](https://cloud.githubusercontent.com/assets/3484020/23116816/4b05b27c-f755-11e6-850b-b302b393db22.png)

**Comment by saturngod** [comment]
But it look missing bridge style like OSM

**Comment by devemux86** [comment]
Hmm Mapsforge has similar rendering, need to check what happens with map files and render theme.

Mapsforge:
![mapsforge](https://cloud.githubusercontent.com/assets/3484020/23117457/8725f688-f758-11e6-8fc1-d7d7cd45ce8d.png)

VTM:
![vtm](https://cloud.githubusercontent.com/assets/3484020/23117464/8d49ed44-f758-11e6-91a1-3f7dd49d14a2.png)

**Comment by andreynovikov** [comment]
No problems with this junction for me (VTM):
![screenshot_20171013-175347](https://user-images.githubusercontent.com/2943625/31552461-4282afd4-b040-11e7-9854-120ae85f870e.png)

**Comment by devemux86** [comment]
The bridge existence is handled via the map data quality, Mapsforge maps, online vector tiles, etc.
The bridge rendering depends on the render themes and how their highway rules are defined.

Closing, if there is something else please reopen.
