### ISSUE TITLE
GrayScale theme

### ISSUE THREAD

**Issue by nebular** [mapsforge/vtm#300]
I have created a new style "Osmagray" based on osmarender but translating all colors to their grayscale equivalent. It looks pretty nice. Fancy a PR?

![screenshot_20170222-231314](https://cloud.githubusercontent.com/assets/1264021/23235130/988b8e44-f954-11e6-994d-6bdb9c5b50fb.png)

**Comment by devemux86** [comment]
Yes that would be great!

BTW why didn't you used the `default.xml` as base for your modifications?

**Comment by nebular** [comment]
hmm good question, no specific reason but I like osmarender the most, probably because default.xml is the typical everybody uses

**Comment by devemux86** [comment]
> default.xml is the typical everybody uses

Because of that `default.xml` is usually better improved / maintained.

Of course you can use whatever you like most. :slightly_smiling_face:

**Comment by devemux86** [comment]
See PR #306 by @nebular.
