### ISSUE TITLE
Wrong Texture binding 

### ISSUE THREAD

**Issue by Longri** [mapsforge/vtm#301]
I found a bug while drawing with a TextureAtlas.
If an Atlas has several Textures, the correct Texture is not always selected when drawing. The region is drawn correctly, but from a false texture.

Or otherwise described, when a symbol is drawn, the correct region is drawn, but from the wrong Texture.

So here the Texture binding does not seem to work properly.

I will try to find the bug. I have written a test and am looking.

![bildschirmfoto 2017-02-23 um 19 05 16](https://cloud.githubusercontent.com/assets/2542295/23272800/f0d20f58-f9fc-11e6-85f5-372cb2cb51d1.png)
![bildschirmfoto 2017-02-23 um 19 04 53](https://cloud.githubusercontent.com/assets/2542295/23272801/f0d2dfaa-f9fc-11e6-9baf-83ba0c2544eb.png)

**Comment by devemux86** [comment]
Some issue in latest texture atlas pull request code?

**Comment by Longri** [comment]
No, not at my code. Is deeper. I will check the buckets and the gl texture binding.

**Comment by Longri** [comment]
The problem is Android and Mac desktop. On Windows I have no problems.
This means, however, that I can only look for the error on the weekend when I am sitting on the Mac!

**Comment by devemux86** [comment]
We need a test sample anyway in order to check what actually happens, have not seen any texture problems so far (besides those in issues list).

If it involves changes in VTM core we should probably proceed on VTM 0.7.0 release as with SVG themes less users actually use a texture atlas.
WDYT

**Comment by Longri** [comment]
My Testcase:

[AtlasMultiTextureTest.zip](https://github.com/mapsforge/vtm/files/798642/AtlasMultiTextureTest.zip)

Put into Playground, start, zoom in, and move map! Texture will change with move!
Maybe is SymbolBucket line 85 : /* FIXME This work only with one TextureAtlas per SymbolBucket */

On Windows I have the Problem not evry map move, but somtime!
I will loog.

**Comment by Longri** [comment]
> If it involves changes in VTM core we should probably proceed on VTM 0.7.0 release as with SVG themes less users actually use a texture atlas.

👍

**Comment by devemux86** [comment]
> FIXME This work only with one TextureAtlas per SymbolBucket

Possibly and that's a quite old comment.

BTW that's a nice test case, you could post a PR to include it for testing. :slightly_smiling_face: 

Tested on Linux, things can get worse on pan / zoom:
![atlas](https://cloud.githubusercontent.com/assets/3484020/23298385/1fd2e410-fa86-11e6-9eb7-123d10433dd2.png)

**Comment by Longri** [comment]
> BTW that's a nice test case, you could post a PR to include it for testing. 🙂

Yes I will upload it with a PR!
But only if I have extensively tested the changes!
Because I think I have fixed the bug, but I want to make sure that the changes have no side effect!

**Comment by devemux86** [comment]
>But only if I have extensively tested the changes!
Because I think I have fixed the bug, but I want to make sure that the changes have no side effect!

:+1:

**Comment by Longri** [comment]
Too early.
When I move the map, the textures are drawn correctly and changed!
But when I change a symbol with a click, the textures are thrown again. Probably I have to re-initialize all items with a symbol change !?

I'll stay!

**Comment by devemux86** [comment]
>Probably I have to re-initialize all items with a symbol change !?

You mean with each tap? That would not be good for memory / performance.

I've not debugged further, but is it indeed the problem with the >1 created texture atlases?
Could you increase the coordinates step in the 2 for loops so that only 1 texture atlas is created and then see if the problem persists?

**Comment by Longri** [comment]
No not at every touch event!

Only if I click on a symbol and then with item.setMarker () a Symbol exchange! But that only makes problems if the old marker is not in the same atlas as the new marker!

**Comment by Longri** [comment]
> I've not debugged further, but is it indeed the problem with the >1 created texture atlases?
Could you increase the coordinates step in the 2 for loops so that only 1 texture atlas is created and then see if the problem persists?

ONLY with more then one TextureAtlas!

**Comment by devemux86** [comment]
Fixed via #303.
