### ISSUE TITLE
License

### ISSUE THREAD

**Issue by charlenni** [mapsforge/vtm#31]
Is this project still part of the OpenScienceMap project? The license says this.

**Comment by devemux86** [comment]
Original VTM was developed within the OpenScienceMap project.
This is a fork, following the same LGPL license, for continue development and make it compatible with latest Mapsforge.

Which license do you mean?

**Comment by charlenni** [comment]
Ok, than all files are under LGPL license and all files are part of the OpenScienceMap project.

My problem is, that I don't know very much about the OpenScienceMap? :)

**Comment by devemux86** [comment]
I updated the readme, for questions please use our forum:
https://groups.google.com/group/mapsforge-dev
