### ISSUE TITLE
BitmapPacker$PackerAtlasItem.drawBitmap recycled bitmap

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#319]
Running the `AtlasMultiTextureActivity` two consecutive times, the 2nd one we have a crash with the following exception:

```java
Caused by: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@cc83f23
   at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1271)
   at android.graphics.Canvas.drawBitmap(Canvas.java:1336)
   at org.oscim.android.canvas.AndroidCanvas.drawBitmap(AndroidCanvas.java:63)
   at org.oscim.utils.BitmapPacker$PackerAtlasItem.drawBitmap(BitmapPacker.java:108)
   at org.oscim.utils.BitmapPacker.add(BitmapPacker.java:71)
   at org.oscim.utils.TextureAtlasUtils.createTextureRegions(TextureAtlasUtils.java:70)
   at org.oscim.android.test.AtlasMultiTextureActivity.createLayers(AtlasMultiTextureActivity.java:104)
   at org.oscim.android.test.SimpleMapActivity.onCreate(SimpleMapActivity.java:45)
```

**Comment by devemux86** [comment]
cc @Longri

**Comment by Longri** [comment]
Have you run, at the first time, with the flag disposeBitmap?

**Comment by Longri** [comment]
Sorry, of course! 
I will try and look

**Comment by devemux86** [comment]
Check the [AtlasMultiTextureActivity](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/AtlasMultiTextureActivity.java) code, we have always the `disposeBitmaps` true.

**Comment by devemux86** [comment]
Anyway at each run the layers are supposed to be created again.
Unless we have some issue in example's life cycle..

**Comment by Longri** [comment]
I hate Android!
Why does Android give me a Recycled Instance back?
![bildschirmfoto 2017-03-05 um 10 14 21](https://cloud.githubusercontent.com/assets/2542295/23586016/fae567d2-018c-11e7-896b-9e45add908d3.png)

**Comment by devemux86** [comment]
Drawables are considered recycled from activity's previous run.
It could depend on how an application life cycle is structured.
So in our example a solution would be to omit the dispose?

**Comment by Longri** [comment]
I've followed the error up to one, followed by Android, deprecated method!
![bildschirmfoto 2017-03-05 um 10 39 50](https://cloud.githubusercontent.com/assets/2542295/23586201/a37ab64c-0190-11e7-8d4a-7271d626ddc8.png)

I could solve the problem by using a copy!
![bildschirmfoto 2017-03-05 um 10 40 25](https://cloud.githubusercontent.com/assets/2542295/23586199/9d4cc102-0190-11e7-880c-6a1fe0eedda2.png)



What do you think about this solution?

**Comment by devemux86** [comment]
That way we make copies, recycle the copies and still maintain the original bitmaps.
Kind of invalidate the recycle process idea, doesn't it?

BTW making drawables mutable is not Android default, so if we need that we should add it as additional API for users to select, not change current behavior.

**Comment by Longri** [comment]
Ok, we can let mutable by default(false) !

Two possible ways!

First: we do not dispose the bitmaps!

Secondly: we use a copy which we can dispose!

or you have another solution/ idea?

**Comment by devemux86** [comment]
Unfortunately both ideas leads eventually to out of memory, after 2 or more `AtlasMultiTextureActivity` consecutive starts.
What have you seen?

Perhaps need to do some cleanup at activity `onDestroy`, as with cold start the example works.

**Comment by Longri** [comment]
or we identify a Android resource on AndroidBitmap and never recycle a resource Bitmap (maybe only onDestroy())

**Comment by devemux86** [comment]
I pushed a simpler implementation in samples which seems working without issues.
@Longri could you have a check too?

**Comment by devemux86** [comment]
Closing, please report any findings.
