### ISSUE TITLE
iOS Line with Texture not drawn 

### ISSUE THREAD

**Issue by Longri** [mapsforge/vtm#325]
Desktop:
![bildschirmfoto 2017-03-06 um 12 03 17](https://cloud.githubusercontent.com/assets/2542295/23607399/24dcb1f2-0265-11e7-8e39-545c9a98ef0d.png)

iOS:
![screen shot 2017-03-06 at 12 01 20](https://cloud.githubusercontent.com/assets/2542295/23607422/4013170e-0265-11e7-930a-707f5c275ca0.png)

**Comment by devemux86** [comment]
Is it on actual iOS device or iOS emulator?

Line textures have issues on some Android devices too.
And depending on pc GPU, the Android emulator often fails completely to render them.

**Comment by Longri** [comment]
its real device (iPhone 6)

**Comment by devemux86** [comment]
Which `PathLayer` did you use on iOS, is this from `vtm-jts` module like in the Android / Desktop examples?

**Comment by Longri** [comment]
no , vtm-project => org.oscim.layers.PathLayer

**Comment by Longri** [comment]
what is the difference

**Comment by devemux86** [comment]
`vtm-jts` requires JTS and its layers are more robust in their rendering.

**Comment by Longri** [comment]
Ok, I will try JTS on iOS

**Comment by Longri** [comment]
JTS will not fix this problem!

**Comment by devemux86** [comment]
Hmm if it's OpenGL related it wouldn't, we just had to try..

**Comment by Longri** [comment]
Before I search, which PathLayer do you prefer, or better asked, which uses the MapRenderer to draw the arrows of a one-way street?

**Comment by devemux86** [comment]
Path layers are for overlays, like lines.
The oneway arrows are embedded in the themes, so they use directly the VTM rendering.

In any case the `vtm-jts` is usually recommended as it solves (via JTS too) many difficult cases (#108 #220).

**Comment by devemux86** [comment]
Hint: maybe some directive in line texture shader or bucket does not play well on iOS?

**Comment by Longri** [comment]
The Shader are ok, they have only a non used u_scale! But this is not the problem. 

I think that is a POT and a mipmap problem. 

http://stackoverflow.com/a/11620336

**Comment by devemux86** [comment]
Hmm and since the image resources can be external by various sources, the solution as described is to add some padding to the image programmatically when loading the texture data?

**Comment by Longri** [comment]
Add padding is not good. 
I think scale the src image up to the next POT and with drawing scale down, is a better solution.

**Comment by Longri** [comment]
Or with padding (transparent) cahnage the line with and stipple to overlapping the padding size!

**Comment by devemux86** [comment]
Since with `CanvasAdapter.platform` there can be platform check, we can have slightly different implementation if needed for iOS.

**Comment by Longri** [comment]
For test I have changed the /paterns/pike.png to POT (32*32) and it works on iOS!

Ok, before I work, I have a lot of questions!

Scale is not posible with repeat so the only way is to ues padding and set stipple and with to overlap!
So I wold add a static flag on TextureItem (USE_ONLY_POT) that we can set on iOS!? 
And I need also padding infos on TextureItem (PadLeft, PadTop) for create correct Style with overlapping!?

I will test with Desktop to see the right implementation! It's faster to compile and test run. I will create a LineTexTest_POT at playground!?

**Comment by devemux86** [comment]
> For test I have changed the /paterns/pike.png to POT (32*32) and it works on iOS!

Good finding!

Eventually the work should be done in code without modifying the resources?
As we cannot force theme resources to be POT and also they need to be universal for all platforms.
Besides that the svg -> bitmap conversion based on density could produce various sizes.

> So I wold add a static flag on TextureItem (USE_ONLY_POT) that we can set on iOS!?

Wise decision! :slightly_smiling_face: 

> And I need also padding infos on TextureItem (PadLeft, PadTop) for create correct Style with overlapping!?

Which should be used only on iOS?

> I will test with Desktop to see the right implementation! It's faster to compile and test run. I will create a LineTexTest_POT at playground!?

Sure!

**Comment by Longri** [comment]
Which should be used only on iOS?

Only use with USE_ONLY_POT=true

**Comment by Longri** [comment]
Please can you explain the LineStyle values?

![explain](https://cloud.githubusercontent.com/assets/2542295/23664288/75540234-0355-11e7-9829-6e97bf926393.png)

**Comment by devemux86** [comment]
- **stippleColor** stipple color
- **stipple** stipple repeat step
- **stippleWidth** stipple width relative to line width, i.e. 0.0-1.0
- **strokeWidth** line width
- **strokeColor** line color
- **fixed** fixed width on zoom (advanced [LineRenderTest](https://github.com/mapsforge/vtm/blob/master/vtm-playground/src/org/oscim/test/LineRenderTest.java) keys 1-4)
- **texture** texture resource
- **randomOffset** false for steady pattern on map move (not perfect)

**Comment by Longri** [comment]
Thanks! 
I tried many ways and I think I need many Time for a solution. 

At the moment I try with TexturRegion and and draw a region multiple times on the path/line. But I don't know if it use to match performance. 
But advantages of this way is we can put the Texture in to the same Atlas like symbols.

**Comment by devemux86** [comment]
All options should play inside VTM core e.g. via [line rule](https://github.com/mapsforge/vtm/blob/master/resources/rendertheme.xsd#L169-L200) in themes.
Exotic options `fixed` and `randomOffset` perhaps not perfectly in two `PathLayer`(s).
For example the aforementioned `LineRenderTest` uses directly the GL buckets. :slightly_smiling_face:

**Comment by Longri** [comment]
My aim is to implement it at core for using with Theme

**Comment by Longri** [comment]
Can you create a simple map file with one Street (only this one) with one way symbols? It will help to test. The smallest map I have created have 20 ways and many areas!

**Comment by Longri** [comment]
fix with #334

**Comment by devemux86** [comment]
Fixed via #334.
