### ISSUE TITLE
VTM Breaks SpriteBatch

### ISSUE THREAD

**Issue by glorantq** [mapsforge/vtm#336]
VTM Breaks SpriteBatch rendering. More info here: [Mapsforge Google Groups](https://groups.google.com/forum/#!topic/mapsforge-dev/XaUsq_apUQE)

**Comment by devemux86** [comment]
Can you create a self-contained example / class for [vtm-playground](https://github.com/mapsforge/vtm/tree/master/vtm-playground) (you can post a pull request), so we can more easily test what happens?

cc @Longri

**Comment by glorantq** [comment]
Made the pull request #337

**Comment by devemux86** [comment]
Thanks, I merged the PR with the [GdxSpriteBatchTest](https://github.com/mapsforge/vtm/blob/master/vtm-playground/src/org/oscim/test/GdxSpriteBatchTest.java), now being easier to debug it.

**Comment by glorantq** [comment]
@devemux86 just an update, this seems to do something with text rendering. I normally init my layers like this:
`initDefaultLayers(tileSource, false, true, false, 2000 << mapScale);`
With labels enabled. If I set the labels to `false` the error happens. Maybe it has to do something with VTM's text rendering method, because when the error first occured, it did in an area where there were no labels near.

**Comment by devemux86** [comment]
What is `2000 << mapScale` for?
The last parameter is for device dpi scaling (not map scale).
e.g. `context.getResources().getDisplayMetrics().density` on Android.
You can use `1` on Desktop.

**Comment by glorantq** [comment]
I changed it to the device's DPI. Is it okay if I use that scale with `map.setMapPosition();`?

**Comment by devemux86** [comment]
Don't be confused with the parameters name similarity.
Device dpi [density](https://developer.android.com/reference/android/util/DisplayMetrics.html#density) and VTM map scale are different concepts.

**Comment by glorantq** [comment]
I now changed my init method to use `Gdx.graphics.getDensity()`. Is moving my map like this correct?
`map.setMapPosition(lat, lon, 2000 << mapScale);`

**Comment by devemux86** [comment]
To set conveniently the map position scale could use `1 << zoomLevel`.
I fixed that also in `GdxSpriteBatchTest`, see 4bf27bc91073c3e72e7d5632033ca3f00b27153c.

**Comment by glorantq** [comment]
Thanks, just making sure it's not me who's breaking things.

**Comment by glorantq** [comment]
It breaks when there are no labels to render. By removing these XML lines from the default rendertheme  

    <style-text fill="#000000" id="road" k="name" priority="2" size="0" stroke="#000000"
        stroke-width="0" />

    <style-text style="bold" fill="#000000" id="major-road" k="name" priority="1" size="0"
        stroke="#000000" stroke-width="0" />

    <style-text caption="true" dy="16" fill="#777744" id="poi" k="name" size="0" stroke="#aaffffff"
        stroke-width="2.0" />

I can get rid of labels, and SpriteBatch will break.

**Comment by devemux86** [comment]
> It breaks when there are no labels to render.

Indeed, if skip label layer with `initDefaultLayers(tileSource, false, false, false)` then the sprite doesn't appear.
When pressing `G` (on desktop) to show debug tile grid with its labels then the sprite appears.

**Comment by glorantq** [comment]
Anything happening with this?
