### ISSUE TITLE
Multiple map sources

### ISSUE THREAD

**Issue by mathieudebrito** [mapsforge/vtm#339]
Hi guys,

I think it would be interesting to be able to use multiple tilesources (online, offline, etc) at the same time, called depending on multiple factors (bounding box, zoom, priority, etc).

One issue would be to be able to merge the different map styles in one : when, for example, we use Mapzen as online map and Mapsforge as offline map.

Cheers

**Comment by braandl** [comment]
Hi @mathieudebrito . 

You can already do this by adding multiple layers to your map. You can set a Theme for every single layer, so you can create yourself themes that match your needs and bring all the different components together.

Greetings

**Comment by mathieudebrito** [comment]
Hi @braandl !

Thank you very much for you quick and very interesting answer, thank you : I just looked a bit more at the setBaseMap and saw that the function I was using will be deprecated in the future : `setBaseMap(TileSource)`. 

So I could do something like : 
``` java
VectorTileLayer onlineLayer = new OsmTileLayer(mapView);
onlineLayer.setTileSource(onlineTileSource);
mLayers.add(someOrder, onlineTileSource);

VectorTileLayer offlineLayer = new OsmTileLayer(mapView);
offlineLayer.setTileSource(offlineTileSource);
mLayers.add(someOtherOrder, offlineTileSource);
```

But a question remain : how would the different layers know when to be displayed or not / and manage priorities ?

Thank you again

**Comment by braandl** [comment]
Hi @mathieudebrito,

you can defined min and maxZoomLevel on layers or enable/disable the layers on other events you implement into your app-business-logic, also you could set up Boundingboxes or whatever fits your needs.

The Ordering of the Layers is by the Order in the List in map.layers(). In my fork of this I did implement zIndexing for Layers, because I wanted to have a little more dynamics on layered rendering. 

Greetings

**Comment by mathieudebrito** [comment]
Hi @braandl,

Thank you again, I will give it a try :)

**Comment by mathieudebrito** [comment]
Just to be sure :

**Comment by devemux86** [comment]
Playing with separate layers, as mentioned in the [forum](https://groups.google.com/forum/#!topic/mapsforge-dev/Z0FATLPuzeU) too, can work (as it could work with multiple map files).

The interesting would be if we can combine different map sources in one layer (like we do now for multiple map files #208) helping also performance.

**Comment by mathieudebrito** [comment]
It's actually a bit more complicated than what I first thought.
`mLayers` in Map is actually private and since there is no `add(Tile)Layer(TileLayer)` function, I can't do this : 

```java
VectorTileLayer offlineTileLayer = new OsmTileLayer(mMap);
offlineTileLayer.setTileSource(offlineTileSource);
mMap.addLayer(offlineTileLayer);        
        
VectorTileLayer onlineTileLayer = new OsmTileLayer(mMap);
onlineTileLayer.setTileSource(onlineTileSource);
mMap.addLayer(onlineTileLayer);
```
Is that possible to add a function for this ?
Should we still call `setBaseMap()` ?

**Comment by devemux86** [comment]
`Map.setBaseMap` are just a convenient methods for setting a tile layer at the bottom (above event layer), shouldn't be considered as mandatory.

Proper way to handle layers is taking from `Map` their `List` and use it for addition / removal / z-order e.g.:
```java
map.layers().add(1, Layer);
```

**Comment by mathieudebrito** [comment]
Works Perfectly thanks :D
