### ISSUE TITLE
SVG Salamander is out of date!

### ISSUE THREAD

**Issue by Longri** [mapsforge/vtm#340]
Unfortunately, I can not find the right GroupID, ArtefactId.
The version "com.metsci.ext.com.kitfox.svg: svg-salamander: 0.1.19"
Has an error in the representation of RadialGradiant!
![compaswrong](https://cloud.githubusercontent.com/assets/2542295/24191355/db849964-0eeb-11e7-90d5-4d639ab6b5e5.png)

As a remedy I have the code of https://github.com/blackears/svgSalamander loaded into my project and here is then correctly rendered!
![compasright](https://cloud.githubusercontent.com/assets/2542295/24191362/e20f45fe-0eeb-11e7-830b-b17bff1165fb.png)

**Comment by devemux86** [comment]
SVG Salamander new official home page is [here](https://github.com/blackears/svgSalamander/wiki), but is not published on Maven yet.

At Maven Central there are currently 2 artifacts:
- The older [official](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.kitfox.svg%22), which misses some classes (filling the log, but it works).
- A newer [here](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.metsci.ext.com.kitfox.svg%22), which has the missing classes.

So far we have seen problems on all readers (like AndroidSVG or SVG Salamander) with theme resources that contain much "noise" from their creators (Inkscape, Illustrator, etc), so they need first to be cleaned with e.g. [SVG Cleaner](https://github.com/RazrFalcon/svgcleaner-gui).

It'd be nice to use the newer SVG Salamander code, but how we can provide that to Mapsforge / VTM users, if it's maintainers haven't published it yet on Maven?

**Comment by Longri** [comment]
https://github.com/blackears/svgSalamander/issues/14

**Comment by devemux86** [comment]
@Longri there is already the https://github.com/blackears/svgSalamander/issues/9

**Comment by devemux86** [comment]
Closing, if newer svg library gets into Maven then we can update it.
