### ISSUE TITLE
Mapzen MVT OOM crash

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#341]
Using Mapzen MVT map source and zooming in dense areas like Edinburgh (Scotland) we have crash and OOM errors.

The issue is reproducible and note that OpenScienceMap tiles work fine at those areas.

**Comment by devemux86** [comment]
(on Desktop seems working)

On Android some of the crash OOM errors coming from [TileDecoder](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/tiling/source/mvt/TileDecoder.java):

```java
java.lang.OutOfMemoryError: Failed to allocate a 44 byte allocation with 2240 free bytes and 2240B until OOM
    at org.oscim.tiling.source.PbfDecoder.decodeUnsignedVarintArray(PbfDecoder.java:412)
    at org.oscim.tiling.source.mvt.TileDecoder.decodeFeature(TileDecoder.java:346)
    at org.oscim.tiling.source.mvt.TileDecoder.decodeLayer(TileDecoder.java:153)
    at org.oscim.tiling.source.mvt.TileDecoder.decode(TileDecoder.java:103)
    at org.oscim.tiling.source.UrlTileDataSource.query(UrlTileDataSource.java:86)
    at org.oscim.layers.tile.vector.VectorTileLoader.loadTile(VectorTileLoader.java:136)
    at org.oscim.layers.tile.TileLoader.doWork(TileLoader.java:66)
    at org.oscim.utils.PausableThread.run(PausableThread.java:141)
```
```java
java.lang.OutOfMemoryError: Failed to allocate a 8204 byte allocation with 5184 free bytes and 5KB until OOM
    at org.oscim.core.GeometryBuffer.<init>(GeometryBuffer.java:0)
    at org.oscim.core.MapElement.<init>(MapElement.java:0)
    at org.oscim.tiling.source.mvt.TileDecoder$Feature.<init>(TileDecoder.java:296)
    at org.oscim.tiling.source.mvt.TileDecoder$1.createItem(TileDecoder.java:268)
    at org.oscim.tiling.source.mvt.TileDecoder$1.createItem(TileDecoder.java:262)
    at org.oscim.utils.pool.Pool.get(Pool.java:98)
    at org.oscim.tiling.source.mvt.TileDecoder.decodeFeature(TileDecoder.java:370)
    at org.oscim.tiling.source.mvt.TileDecoder.decodeLayer(TileDecoder.java:153)
    at org.oscim.tiling.source.mvt.TileDecoder.decode(TileDecoder.java:103)
    at org.oscim.tiling.source.UrlTileDataSource.query(UrlTileDataSource.java:86)
    at org.oscim.layers.tile.vector.VectorTileLoader.loadTile(VectorTileLoader.java:136)
    at org.oscim.layers.tile.TileLoader.doWork(TileLoader.java:66)
    at org.oscim.utils.PausableThread.run(PausableThread.java:141)
```

**Comment by devemux86** [comment]
While in `TileDecoder` feature pool we have usually some hundred items, at that area on zoom 12 the number reaches 20K!

**Comment by devemux86** [comment]
For reference the relevant Mapzen [pbfParser.cpp](https://github.com/tangrams/tangram-es/blob/master/core/src/util/pbfParser.cpp).

**Comment by devemux86** [comment]
Looks like the Mapzen layer that causes the trouble is the `pois` of all [9 available](https://mapzen.com/documentation/vector-tiles/layers/#layer-reference).

So if remove the `pois` and use in [MapboxTileSource](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/tiling/source/mvt/MapboxTileSource.java#L26) for url the:
```java
"https://tile.mapzen.com/mapzen/vector/v1/boundaries,buildings,earth,landuse,places,roads,transit,water"
```
then the map works again, but without POIs. :slightly_frowning_face:

**Comment by mathieudebrito** [comment]
Very interesting !!
Thank you :)

**Comment by devemux86** [comment]
My thought is that we need to improve .mvt [TileDecoder](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/tiling/source/mvt/TileDecoder.java) somehow.

**Comment by nvkelso** [comment]
Hello! What tile coordinate (z/x/y) are you having problems with?

**Comment by devemux86** [comment]
Hi @nvkelso, thanks for asking!
Right on Edinburgh, Scotland at zoom 12, e.g.: 12/2011/1276.

**Comment by nvkelso** [comment]
Thanks, I'll have a look. 20k features is certainly too many for a vector tile!

**Comment by nvkelso** [comment]
This is a bug in Mapzen's vector tile generation logic, tracking the fix with https://github.com/tilezen/vector-datasource/issues/1185.

**Comment by devemux86** [comment]
Thanks @nvkelso for the feedback!

I have probably seen that problem also in some other areas. Don't know if it's the same cause as you describe in https://github.com/tilezen/vector-datasource/issues/1185, if see them again I'll inform about the locations.

**Comment by devemux86** [comment]
Mapzen vector tiles seem to be fixed now at aforementioned area, so no errors happen and can close here.

**Comment by devemux86** [comment]
Reopening as there are more areas causing OOM.

Now see them at Athens (Greece) around tile coordinates 12/2318/1580.

cc @nvkelso

**Comment by mathieudebrito** [comment]
Just wanted to add that when we leave the app, and after a GC, the Java Heap says that the TileDecoder still retains a lot of features instances.

<img width="1109" alt="capture d ecran 2017-05-23 a 4 27 11 pm" src="https://cloud.githubusercontent.com/assets/1231274/26359097/d1503128-3fd4-11e7-8dcf-b7af5b11eb13.png">

**Comment by nvkelso** [comment]
@devemux86 I don't see 1000s of `garden` **pois** in Athens in that tile. Is there a different problem you're experiencing?

**Comment by devemux86** [comment]
@nvkelso I need to debug it further, but I see the same behavior as was with Edinburgh.
I think that have zoomed in Athens before without issues, has something changed lately in tiles?

**Comment by devemux86** [comment]
@mathieudebrito I agree that `TileDecoder` could use some work.
If you have any improvements, please post a PR to check them. :slightly_smiling_face:

**Comment by devemux86** [comment]
@nvkelso further debugging I see that in 12/2317/1580 tile we have over 2.5K features.
Decoding that on desktop works, but on Android with limited VM heap it often leads to OOM.

**Comment by nvkelso** [comment]
Nope, nothing new for Mapzen tiles since our last build few weeks ago. Doesn't mean data hasn't changed since, but I'd need more to go on - I don't see anything funky in that tile.

**Comment by boldtrn** [comment]
I just took a quick look at the TileDecoder.

As a workaround for the current OOM crashes I would like to propose a [max features value](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/tiling/source/mvt/TileDecoder.java#L130) . So we could try setting it to 1000 features, if the decoder exceeds 1000 features for one layer it just skips all other features for this layer. Not sure if this breaks anything, but this could be at least a quick workaround. As this only happens for very few tiles, we might render some tiles incorrect, but at least there are no crashes.

Without debugging this I would also propose to put the declaration of some of the variables into the Class name space. For example the feature [here](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/tiling/source/mvt/TileDecoder.java#L327). Since we instantiate the object very often it sometimes happens that the JVM optimizes the code wrong, which leads to a GC overhead more easily.

**Comment by devemux86** [comment]
[Mapzen shutdown](https://mapzen.com/blog/shutdown/)
