### ISSUE TITLE
Short-overflow with Maprenderer.COORD_SCALE = 8

### ISSUE THREAD

**Issue by Longri** [mapsforge/vtm#343]
I do not know exactly how I should describe it, but there is a problem with devices that have a high resolution.

I've been looking for a long time until I find the cause.
My Galaxy Note 4 has a resolution of 2240 * 1440 pixels.
For a tilt view (tilt >30), the function mMarkerLayer.map().viewport().getMapExtents(mBox, mExtents);  returns a  BoundingBox of
0 = 497.63928
1 = 1762.7147
2 = -497.63928
3 = 1762.7147
4 = -1560.3398
5 = -5526.964
6 = 1560.3398
7 = -5526.964
These values are also correct, but too large to multiply them with a COORD_SCALE and then cast them to a short.
(-5526.964 * 8 = -44215.712 (short) = 21321)

Now I see two possibilities.
1. Clamp to Short.Max_Value! But that leads to that some things are not represented correctly.
2. Decrease the value Maprenderer.COORD_SCALE = 8. This will break the API.

I would prefer 2. But I know you have something against with break the API.

A simple change of the one value does not help, however, because this scale factor (8) is also hard-coded at other places.
eg. In the SymbolBucket (private final static float SCALE = 8.0f;)

I think however that it is the cleanest way, if this change is properly documented and the users, with an update, are informed about this.

Another point would be to ask @hjanetzek why this scale factor is so high, or for which he is there at all.

I once made a video of my Note4 (with Cruiser-GL) to illustrate the problem!
https://youtu.be/eaSmttPiBh4

**Comment by devemux86** [comment]
Interesting report!
Problem appears only with overlays or could be related with their implementation?
Do you mean if replace everywhere with e.g. `4.0f` then the problem disappears and the library continues to function properly with ALL its features?

We could have a public constant in e.g. `GLAdapter` to be used internally and can be changed by users.

BTW I'd like also @hjanetzek's opinion.

**Comment by Longri** [comment]
Ok, changing the COORD_SCALE did not have as many effects as I thought.
I just needed to scale the icons, symbol labels, and bitmaps back, and already fit the rendering
I have compared the two representations and the result convinces me!
As comparison tool I have => http://huddle.github.io/Resemble.js/ used.


I'll create a PR immediately.
But please not yet merge, since I have not tested all the examples!
And I could use a little help, four eyes see more! ;-)

COORD_SCALE=8 
![androidoriginal](https://cloud.githubusercontent.com/assets/2542295/24455808/36fed232-1491-11e7-8e72-8f6bea3cdda6.png)


COORD_SCALE=4 
![androidscaled](https://cloud.githubusercontent.com/assets/2542295/24455829/4f2b85da-1491-11e7-9df6-ddba7129a579.png)
 
DIV
![div](https://cloud.githubusercontent.com/assets/2542295/24455859/63cb309e-1491-11e7-94f6-c46a6f9f28b8.png)

**Comment by Longri** [comment]
I will also try to set COORD_SCALE to 1!

If this ok, so we can remove all COORD_SCALE calculations for increase performance! Maybe!

**Comment by devemux86** [comment]
Such core changes always require extensive testing and understand the "why" of initial implementation.
e.g. 4.0f or 1.0f or DPI dependent like tile size, etc.

Above all having it as user controllable variable is a fail safe way until things are clarified.

**Comment by Longri** [comment]
You mean I should delete the 'final' from COORD_SCALE?
I can do this!

**Comment by hjanetzek** [comment]
Hey - At least for tile rendering I recall the reason for using 8 as scaling factor: The oscimap (and mvt) tiles use a default extent of 4096. During tile building the coordinates where scaled to Tile.SIZE 256 floating point. To have the original precision in vertex buffers (using shorts) the tile coordinates need to be scaled up again. Depending Tile.SIZE and how much tiles get overzoomed using 4 or 2 as COORD_SCALE sounds sensible.

Or you could pass it as variable to the Renderers (and uniform to shaders), with scale 1 for text and overlay rendering while keeping 8 for tile rendering.

**Comment by devemux86** [comment]
> You mean I should delete the 'final' from COORD_SCALE?

Something like that, leaving default value for users and allow changes for testing.

**Comment by devemux86** [comment]
@hjanetzek thanks for the feedback!

Εxpected it wouldn't be so straightforward, we need to test absolutely everything with such core changes.

Also everyone should be aware that now we use variable tile size (#183) based on device dpi (#236).

**Comment by Longri** [comment]
@hjanetzek thank you very much!

> Edit: I think COORD_SCALE was hardcoded in some shaders. It needs to be passed as uniform in this case.

That was the right hint. I passed the COORD_SCALE as uniform to the shader and I was able to take back my scaling from the last change.
Now the value for COORD_SCALE can be changed as desired and everything is drawn correctly. BitmapTileLayer also works with it.

Thank you very much!

**Comment by Longri** [comment]
btw. COORD_SCALE value '1' also work fine!

**Comment by devemux86** [comment]
@Longri are you testing on all platforms and preferably on high + low dpi screens?

**Comment by Longri** [comment]
IOS is still out! Probably tomorrow!
Web I'll try

**Comment by Longri** [comment]
I have tested Android all exemple Activitys (on Galaxy Note4), Desktop all Playground exemple's,
iOS BitmapLayer and VectorLayer, and WEB project!

All tested with COORD_SCALE 1 and 8!

All seems ok 

With the last commit I have revert the COORD_SCALE to 8, so user can chaged self!

**Comment by devemux86** [comment]
Fixed via #344.

You need to change the `MapRenderer.COORD_SCALE` to `4` or `2` or even `1`.
(For now and until further testing we keep as default the current `8` coord scale)
