### ISSUE TITLE
S3DB Offline-Layer

### ISSUE THREAD

**Issue by Gustl22** [mapsforge/vtm#346]
Is there any possibility to implement an offline S3DB-Layer?
I thought of an extension of Building-Layer in .map file.
Can anyone explain me, how the S3DB-Tiles are generated? Then i would do it myself.
My fear is, that i break the conventions of Mapserver files. May it's better to store that in an extra file.
Thx ;D

**Comment by devemux86** [comment]
Vector / raster tiles could be stored offline in a DB structure, like we do on [Android](https://github.com/mapsforge/vtm/blob/master/vtm-android/src/org/oscim/android/cache/TileCache.java) with SQLite.

No need to break compatibility with Mapsforge vector map format which has a different concept and implementation.

**Comment by Gustl22** [comment]
Ok, but how could i predownload tiles of country bounds (which aren't in a rectangle, more a multipolygon)?

**Comment by devemux86** [comment]
For further questions please use our [forum](https://groups.google.com/group/mapsforge-dev).
