### ISSUE TITLE
Tunnels are under areas, using Oscim or Mapsforge maps, with default.xml

### ISSUE THREAD

**Issue by boldtrn** [mapsforge/vtm#348]
Something I saw with the [Kurviger App](https://play.google.com/store/apps/details?id=gr.talent.kurviger.pro), which uses VTM and Mapsforge offline maps, is that tunnels are rendered under areas, if the tunnel is associated with a negative layer value. This happens for Oscim and Mapsforge maps but not for Mapzen. This is [one example](http://www.openstreetmap.org/way/37348198) where this happens. I played around with the render theme, but I am not sure if there is a way to change the behavior in the render theme?

Maybe we could enforce that ways with existing highway tag, are always rendered on top? We could then adjust the render theme so it get's clear that the road is a tunnel?

See attached screenshot.
![tunnel_bug_offline](https://cloud.githubusercontent.com/assets/1553525/25568657/e04b4172-2e4a-11e7-9b19-03087cb8eaf0.png)

**Comment by devemux86** [comment]
Related Mapsforge issue https://github.com/mapsforge/mapsforge/issues/786 and [forum topic](https://groups.google.com/forum/#!topic/mapsforge-dev/97bAnv0KYHo) with valuable info.

Mapsforge maps keep original OSM tunnel `layer` negative values, so in both Mapsforge / VTM libraries tunnels are rendered below other elements (unless semi-transparency).
OpenAndroMaps prefer to tag tunnels with a `layer` positive value to show them on top.

So we have a different rendering based on how Mapsforge .map files are built (OSciM could be similar).

**Comment by boldtrn** [comment]
Is there a way to change this in the render theme or do I need to change the source itself (hard for OSciM).

**Comment by devemux86** [comment]
Probably with semi-transparent above elements, the tunnels could be visible (see [forum](https://groups.google.com/d/msg/mapsforge-dev/97bAnv0KYHo/T-hIjGtdFwAJ)).
Though that solution can alter completely map appearance, also semi-transparency often leads to undesirable results. See [here](https://groups.google.com/forum/#!topic/mapsforge-dev/GadiGI5iQNU) for the problem, the [solution](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md#known-pitfalls) requires different maps creation.

OpenAndroMaps changes the `layer` tag on map creation to place tunnels on top (see [forum](https://groups.google.com/d/msg/mapsforge-dev/97bAnv0KYHo/P6u2fDFdFwAJ)).

**Comment by hjanetzek** [comment]
@boldtrn completely untested, but this might work:
```
vectorTileLayer.addHook(new TileLoaderProcessHook() {
        public boolean process(MapTile tile, RenderBuckets layers, MapElement element) {
            if (element.layer < 0) { element.layer = 0; }
        }
        public void complete(MapTile tile, boolean success){}
}); 
```

**Comment by devemux86** [comment]
Thanks @hjanetzek that is an idea via code.
And would need some tag filter, as tunnels are not the only elements with layer<0.
e.g. in [Mapsforge maps](https://github.com/mapsforge/mapsforge/blob/master/docs/MapCreation.md) there are also the sea and the land polygons.

**Comment by boldtrn** [comment]
> @boldtrn completely untested, but this might work:

This sounds good, thanks

@devemux86 Should we add this to VTM including a tag check for tunnel=yes? I think this would further improve VTM.

**Comment by devemux86** [comment]
> Should we add this to VTM including a tag check for tunnel=yes? I think this would further improve VTM.

@boldtrn if added could be optional as it alters map definitions and many won't like a library to perform such automatic modifications.
Also @hjanetzek 's example can be handled in app level, without pushing a change to all users?

**Comment by boldtrn** [comment]
> Also @hjanetzek 's example can be handled in app level, without pushing a change to all users?

If that would work without modifying VTM I agree with you :).

**Comment by devemux86** [comment]
@boldtrn I cannot confirm the issue with OpenScienceMap vector tiles.
Only appears with [Mapsforge](http://download.mapsforge.org/) maps.

**Comment by boldtrn** [comment]
@devemux86 I just rechecked OpenScienceMap. The issue still exists, I attached a screenshot from the [Kurviger App](https://play.google.com/store/apps/details?id=gr.talent.kurviger.pro).

![16095](https://cloud.githubusercontent.com/assets/1553525/26765846/d2e0ea26-49c7-11e7-8a2d-cbcf2e844542.png)

**Comment by devemux86** [comment]
Strange (same app and map source), the tunnel test case in Berlin seems working:

![tunnels](https://cloud.githubusercontent.com/assets/3484020/26775400/755b098e-49dd-11e7-9379-34cade5e503e.png)

**Comment by devemux86** [comment]
Well debugging OpenScienceMap tiles is not easy, as server most of the time does not work... :slightly_frowning_face: 
Nevertheless some tunnels appear on top (e.g. a bit NE at Switzerland) and some below (your example), so cannot answer how OSciM tiles are structured.

**Comment by devemux86** [comment]
Closing as aforementioned solutions work, either on map files creation or in code transforming the tags.
