### ISSUE TITLE
missing app in vtm/docs/Applications.md

### ISSUE THREAD

**Issue by stleusc** [mapsforge/vtm#352]
Below app was actually the first app using VTM. I worked with the original developer to get some early kinks sorted out.
Please add it to the above list.
Thanks!

GCDroid (https://play.google.com/store/apps/details?id=com.gcdroid)
Geocaching App
Proprietary/Free and Commercial
Android
Closed

**Comment by devemux86** [comment]
Thanks, I updated applications list via 7b7b5a923afee05bdcf1bb0b5509ae10e900519d.
