### ISSUE TITLE
Mapzen renders parts of roads in high zoom-level

### ISSUE THREAD

**Issue by boldtrn** [mapsforge/vtm#353]
When playing around with Mapzen tiles, I saw that parts of roads get rendered in high zoom-levels where most parts are not rendered. If you zoom closer the whole road gets rendered. The screenshot was taken in the area around Stuttgart. Not sure if this is an issue of Mapzen or VTM.

![mapzen_weird](https://cloud.githubusercontent.com/assets/1553525/26430599/e3976208-4131-11e7-8966-f1ccf93ab7f6.png)

**Comment by devemux86** [comment]
Wondering at that zoom level what road data the Mapzen tiles have in them.

**Comment by boldtrn** [comment]
> Wondering at that zoom level what road data the Mapzen tiles have in them.

Yeah, it looks a bit like Mapzen would simply provide the wrong data, but I am not sure, haven't checked it.

**Comment by devemux86** [comment]
[Mapzen shutdown](https://mapzen.com/blog/shutdown/)
