### ISSUE TITLE
Embedding GL window in swing/canvas

### ISSUE THREAD

**Issue by jbk123456** [mapsforge/vtm#354]
Hi,

with the latest switch to LWJGL, LWJGL3's dependency on glfw and Camilla's refusal to add an API to pass the parent window ID to GLFW (see https://github.com/glfw/glfw/issues/25), is there any chance to embed a VTM GL window in a swing java desktop application, as it was in previous releases?

Regards,
Jost Bökemeier

**Comment by devemux86** [comment]
VTM uses LWJGL 2 for libGDX backend on Desktop, so it's possible to embed it in a Java Swing application.
You can check [vtm-playground](https://github.com/mapsforge/vtm/tree/master/vtm-playground) which has many examples of VTM use on Desktop.

**Comment by devemux86** [comment]
We have #258 for LWJGL 3 which needs #259 first.

For further VTM questions please use our [forum](https://groups.google.com/group/mapsforge-dev).
