### ISSUE TITLE
Unable to see labels for the geojson file in JeoIndoorMapActivity.java

### ISSUE THREAD

**Issue by akarsh** [mapsforge/vtm#355]
Hallo,

I am using the JeoIndoorMapActivity.java from the android-example for displaying the geojson file.
I used the [default overpass geojson file](https://gist.githubusercontent.com/anonymous/8960337/raw/overpass.geojson) and also our own test map [raw geojson file](https://gist.githubusercontent.com/akarsh/cbdeaa31f647e2851ba9bdb70a0f1ad1/raw/2477b1041297aa4abdc5688276a9bc5d5ac36183/testmap.geojson).

I am unable to show room names i.e. labels in the map.
You can see the video demonstration [here 
]( osmdroid-sample-android-studio-app/device-2017-06-02-152504.mp4 )
> e.g.  "name": "Saal 11" 

Here is the default code from the original [vtm-android-example file ](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/JeoIndoorMapActivity.java)
Here is  my [code gist file ](https://gist.github.com/1ffc64674b58beb0ea2e8a924b567ed5.git)

Help is appreciated.

Thank you

**Comment by devemux86** [comment]
Seems that the parsing in `vtm-jeo` does not consider any `CartoCSS.TEXT_*` elements which can be used for labeling and so the `JeoVectorLayer` draws only the geometries.

**Comment by akarsh** [comment]
How to move forward ?
We need to add any style in [RenderTheme.java](https://github.com/mapsforge/vtm/blob/master/vtm-jeo/src/org/oscim/theme/carto/RenderTheme.java) file to make sure that they consider text to be rendered or anything else ?

**Comment by devemux86** [comment]
The features passed in the aforementioned layers contain all data (also labels).
But `OSMIndoorLayer` `processFeatures` & `addPolygon` do not render them correctly.

The `RenderTheme` is used differently as styler in `ThemeTest`.
Useful is also the [CartoCSS](https://tilemill-project.github.io/tilemill/docs/guides/styling-labels/) reference.

**Comment by akarsh** [comment]
The CartoCSS reference was useful. 
Thanks @devemux86 

I tried by adding the following in the String STYLE 
`            "[room = 'toilet'] {"+
            " text-name: [NAME];" +
            " text-face-name: 'Droid Sans Regular';" +
            " text-fill: #036;" +
            " text-size: 20;"+

            "[room = 'office'] {"+
            " text-name: [NAME];" +
            " text-face-name: 'Droid Sans Regular';" +
            " text-fill: #036;" +
            " text-size: 20;"+

            "[room = 'laboratory'] {"+
            " text-name: [NAME];" +
            " text-face-name: 'Droid Sans Regular';" +
            " text-fill: #036;" +
            " text-size: 20;"+  `

of [RenderTheme.java](https://github.com/mapsforge/vtm/blob/master/vtm-jeo/src/org/oscim/theme/carto/RenderTheme.java)
But i am not able to see the name 2058
` {
            "type":"Feature",
            "properties":{
                "level":"2",
                "name":"2058",
                "ref":"491058905",
                "room":"printer"
            } `

Should i need to add anything more in other class file for rendering i.e. OSMIndoorLayer.java ?

**Comment by devemux86** [comment]
I pushed the fix, have a look how all work.

**Comment by devemux86** [comment]
The `RenderTheme` is not used anywhere in `OSMIndoorLayer` but in `ThemeTest` to render the `OSciMap4TileSource` vector tiles.
