### ISSUE TITLE
Vtm Location Renderer: Zoom in causes circle to suddenly increase

### ISSUE THREAD

**Issue by hacky86** [mapsforge/vtm#358]
There seems to be a bug in the calculation of the radius for the circle showing the accuracy of the current location. When zooming in (especially with GPS turned of and low location accuracy) both in the vtm-app as well as the Cruiser App, the radius will at some point suddenly increase. 

I think the problem is in lines 203-205 of the location renderer
`if (v.pos.zoomLevel >= mShowAccuracyZoom)   radius = (float) (mRadius * v.pos.scale);`
`radius = Math.max(CIRCLE_SIZE, radius);`

The mShowAccuracyZoom is set to 16, but the value `mRadius * v.pos.scale` may be larger than `CIRCLE_SIZE` already on a lower zoom level. I think this could be fixed by setting `mShowAccuracyZoom` to a lower value or by dropping the if clause, i.e., just replacing the above code by
`radius = Math.max(CIRCLE_SIZE, (float) (mRadius * v.pos.scale));`

[https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/renderer/LocationRenderer.java](url)

**Comment by devemux86** [comment]
Actually that's by design, by default:
- zoom < 16: accuracy does not participate in location marker
- zoom ≥ 16: if accuracy is larger than marker default size, then its radius increases

You can use `LocationRenderer.setShowAccuracyZoom` to change the zoom when want the accuracy to appear.

**Comment by hacky86** [comment]
Thank you very much for the fast reply. Then this was a misunderstanding from my side. For the default value 16, I found it quite unintuitive for the user that for low accuracy the circle first is quite small and then jumps to being larger than the screen size.
