### ISSUE TITLE
Reuse OkHttp cache files

### ISSUE THREAD

**Issue by wolfgang-ch** [mapsforge/vtm#359]
This is my understanding how tiles are loaded from a tile server.

For each tile a request is submitted to the tile server to check if a newer version is available. When the OkHttpCache is used then the meta cache control is checked.

To avoid every time a http request, an existing and cached tile file could be used instead.

**This is the solution I've found but is not yet perfect**

- A cache  is set in the [UrlTileSource](https://github.com/wolfgang-ch/vtm-with-rcp/blob/master/VTM_RCP_App/src/vtm/rcp/app/CustomTileSource.java#L29)

- With [TileReader.getInputStream()](https://github.com/wolfgang-ch/vtm-with-rcp/blob/master/VTM_RCP_App/src/vtm/rcp/app/OkHttpTileCache.java#L70) the cached tile file can be delivered.

- The cache also needs a TileWriter with a valid [getOutputStream()](https://github.com/wolfgang-ch/vtm-with-rcp/blob/master/VTM_RCP_App/src/vtm/rcp/app/OkHttpTileCache.java#L101) otherwise an exception is thrown. In my implementation I return a valid output stream but this is a stupid solution.

- The exception could be omitted when the [cacheWriter.getOutputStream()](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/tiling/source/UrlTileDataSource.java#L85) in UrlTileDataSource is checked for null. Maybe there is another and better solution but this implementation works.

**Comment by devemux86** [comment]
OkHttp provides its own [response cache](https://github.com/square/okhttp/wiki/Recipes#response-caching) in #138, can see it in action at [OkHttpEngineTest.shouldUseTileSourceCache](https://github.com/mapsforge/vtm/blob/master/vtm-tests/test/org/oscim/tiling/source/OkHttpEngineTest.java#L93).
There's even support for external cache hook, like VTM `TileCache`, in #135.
i.e. when being offline then the map works fine with the cached tiles

Or there is need for something different?

**Comment by devemux86** [comment]
With 3f959a3b46a46393bdb1173afcfaa05d16658532 I improved `OkHttpEngine` cache API and added an example in [MapboxTest](https://github.com/mapsforge/vtm/blob/master/vtm-playground/src/org/oscim/test/MapboxTest.java).

**Comment by wolfgang-ch** [comment]
The OkHttp cache is using the http header tag `Cache-Control: max-age`.
For the mapzen tiles this is set to `Cache-Control: max-age=43200` = 30 days.

When using this http tag then the server controls how long the tile is cached but I would like to control it by myself how long a tile is being used from the tile cache. 

How could this be implemented?


When using the own [tile server](https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service) then the cache-control tag is not set. This is the reason why I tried to reused the cached tiles.

How could I set the cache-control tag into my own tile server?

**Comment by devemux86** [comment]
So your question is not how to use OkHttp cache (which is supported), like the issue was created for, but something else?

I suggest then to close here, discuss the matter in [forum](https://groups.google.com/group/mapsforge-dev) and if needed implementation to decide how proceed and open issue for that.

**Comment by devemux86** [comment]
BTW OkHttp support `max-stale`, `max-age` settings via interceptors.
We could improve VTM API to allow more flexibility for such cases.

**Comment by devemux86** [comment]
I pushed an improved API for `OkHttpEngine` which permits external `OkHttpClient.Builder`, allowing for a wide range of customizations for OkHttp client used in VTM.

**Comment by devemux86** [comment]
Furthermore can also study OkHttp [interceptors](https://github.com/square/okhttp/wiki/Interceptors) which can "rewrite" requests, like apply cache control via extra headers.
They are now usable via the external `OkHttpClient.Builder`.

**Comment by wolfgang-ch** [comment]
With the accessable `OkHttpClient.Builder` the API is now more flexible and subclassing is not needed anymore, so I will close this issue.
