### ISSUE TITLE
Height offset in render styles

### ISSUE THREAD

**Issue by akarsh** [mapsforge/vtm#368]
Using the PathLayer class from vtm-jts; i was able to draw paths from location a to b. the line drawn is on the ground floor. But it does not appear on the other levels. 

Here is my sample code
> // Color of the path is magenta
> // path width is 6
> PathLayer pathLayer = new PathLayer(mMap, Color.MAGENTA, 6);
> // the value is 4 because we are adding 6 values
> double[] packedCoordinates = new double[6];
> int countValue = 0;
> // starting coordinate
> packedCoordinates[countValue++] = 13.31405180788;
> packedCoordinates[countValue++] = 52.52597938168;
> // middle coordinate
> packedCoordinates[countValue++] = 13.31439480788;
> packedCoordinates[countValue++] = 52.52597938168;
> // destination coordinate
> packedCoordinates[countValue++] = 13.31439480788;
> packedCoordinates[countValue++] = 52.52609938168;
> 
> pathLayer.setLineString(packedCoordinates);
> mMap.layers().add(pathLayer); 

![pathoverlay on ground floor](https://lh3.googleusercontent.com/-o3JNYnYINmM/WUvPdrZ89HI/AAAAAAAAFE4/rE6QRNnLRC0rim4og5AM59elyzn1viDKACLcBGAs/s320/path-0verlay-1.png)

thank & help appreciated.

**Comment by devemux86** [comment]
I added height offset in render styles.

e.g. can use `PathLayer` with its `Style` builder and see how it works.

**Comment by akarsh** [comment]
I used this code
`        pathLayer.setStyle(org.oscim.layers.vector.geometries.Style.builder().heightOffset(5).build());
`
to see if it works.
But, setStyle for pathLayer overrides the line colour and size.
![heightoffsetoverrideslinecolour](https://user-images.githubusercontent.com/845598/27512257-fc577780-593a-11e7-9635-36dc411310be.png)

**Comment by devemux86** [comment]
You need to use the builder to create your style with all needed parameters and then use it:
```java
Style.builder()
        .fixed(true)
        .heightOffset(heightOffset)
        .strokeColor(lineColor)
        .strokeWidth(lineWidth)
        .build();
```

**Comment by akarsh** [comment]
thank you @devemux86 
it works
