### ISSUE TITLE
OkHttp close threading issue

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#369]
Sometimes OkHttp throws the following exception:

```java
java.lang.IllegalStateException: Unbalanced enter/exit
    at okio.AsyncTimeout.enter(SourceFile:73)
    at okio.AsyncTimeout$2.read(SourceFile:235)
    at okio.RealBufferedSource.read(SourceFile:46)
    at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(SourceFile:384)
    at okhttp3.internal.Util.skipAll(SourceFile:171)
    at okhttp3.internal.Util.discard(SourceFile:153)
    at okhttp3.internal.http1.Http1Codec$FixedLengthSource.close(SourceFile:400)
    at okio.RealBufferedSource.close(SourceFile:455)
    at okio.RealBufferedSource.close(SourceFile:455)
    at okio.InflaterSource.close(SourceFile:126)
    at okio.GzipSource.close(SourceFile:182)
    at okio.RealBufferedSource.close(SourceFile:455)
    at okio.RealBufferedSource$1.close(SourceFile:443)
    at org.oscim.utils.IOUtils.closeQuietly(SourceFile:44)
    at org.oscim.tiling.source.OkHttpEngine$1.run(SourceFile:108)
    at java.lang.Thread.run(Thread.java:761)
```

**Comment by devemux86** [comment]
See also https://github.com/square/okhttp/issues/1842.

**Comment by devemux86** [comment]
Current fix could cause `android.os.NetworkOnMainThreadException`.
Though threaded solution by @hjanetzek had issues too (see above).
So we need to think something better.

**Comment by carlos-mg89** [comment]
Hi @devemux86 ,

Usually I'm very keen to use the Google forum, however I'm unable to write posts although I'm subscribed to it. So this is the only place I've left to communicate with you.

I'm receiving some crashes on Firebase for my Android app. And it looks to me very similar to this one.

Here's the error trace:

```
Caused by android.os.NetworkOnMainThreadException

okio.InputStreamSource.read (InputStreamSource.java:93)
okio.AsyncTimeout$source$1.read (AsyncTimeout.java:125)
okio.internal.RealBufferedSourceKt.commonRead (RealBufferedSourceKt.java:39)
okio.RealBufferedSource.read (RealBufferedSource.java:189)
okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read (Http1ExchangeCodec.java:331)
okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read (Http1ExchangeCodec.java:368)
okhttp3.internal.Util.skipAll (Util.java:337)
okhttp3.internal.Util.discard (Util.java:358)
okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.close (Http1ExchangeCodec.java:387)
okio.ForwardingSource.close (ForwardingSource.java:34)
okhttp3.internal.connection.Exchange$ResponseBodySource.close (Exchange.java:309)
okio.internal.RealBufferedSourceKt.commonClose (RealBufferedSourceKt.java:392)
okio.RealBufferedSource.close (RealBufferedSource.java:477)
okio.RealBufferedSource$inputStream$1.close (RealBufferedSource.java:170)
org.oscim.utils.IOUtils.closeQuietly (IOUtils.java:44)
org.oscim.tiling.source.OkHttpEngine.close (OkHttpEngine.java:103)
org.oscim.tiling.source.UrlTileDataSource.cancel (UrlTileDataSource.java:120)
org.oscim.layers.tile.bitmap.BitmapTileLoader.dispose (BitmapTileLoader.java:73)
org.oscim.layers.tile.TileLayer.onDetach (TileLayer.java:114)
org.oscim.layers.tile.bitmap.BitmapTileLayer.onDetach (BitmapTileLayer.java:156)
org.oscim.map.Layers.destroy (Layers.java:229)
org.oscim.map.Map.destroy (Map.java:231)
org.oscim.android.MapView.onDestroy (MapView.java:173)
com.walkaholic.hikeapp.framework.ui.activities.MapActivity.onDestroy (MapActivity.java:276) 
```

This is how I'm destroying the activity (which is based on code of the [VTM example project](https://github.com/mapsforge/vtm/blob/12a58e5827703e3b062fd001024195919255d313/vtm-android-example/src/org/oscim/android/test/MapActivity.java#L70)):

```
override fun onDestroy() {
        binding.mapView.onDestroy()
        super.onDestroy()
}
```

I think [some other people described it](https://groups.google.com/g/mapsforge-dev/c/q0vl5eE9yH0/m/eQryeYCcDwAJ), even yourself in your last response, but I'm unsure if it's the same problem or not.

I could try to put some time into this matter and try to fix it. But would prefer to ask you first if you find it suitable or not.

Cheers

**Comment by devemux86** [comment]
[Mapsforge forum](https://groups.google.com/g/mapsforge-dev) was closed because of spamming.

Please use the **Discussions** in each repository.

---

After https://github.com/mapsforge/vtm/commit/2dbad2b16a80ed8c64a7dda8194b9ad87ccd003b I have not seen any exceptions.
You can also check the [getting started example](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/GettingStarted.java).

About your question, see https://github.com/mapsforge/vtm/commit/2dbad2b16a80ed8c64a7dda8194b9ad87ccd003b and check if the old code helps your case.

**Comment by carlos-mg89** [comment]
This exception has been logged a few days ago on an Android 10 device (Xiaomi Redmi Note 7) with the VTM 0.16 release.

I understand that it might not happened to everyone, I'm just spotting that it happened to me, using the same `onDestroy()` procedure you have described in the examples.

I've checked the code both of `OkHttpEngine.java` and of `IOUtils.java`. The exception that is caught is an `IOException`, which is not compatible with the `NetworkOnMainThreadException` as I see [here](https://developer.android.com/reference/android/os/NetworkOnMainThreadException) it's inherited from `Exception` and `RuntimeException`.

Perhaps if we change the code to catch an Exception it would fix the issue.

I can definitely send you a PR. But I'm unsure on how to proceed to test it myself before sending you the PR.

**Comment by devemux86** [comment]
We cannot change the `IOUtils.closeQuietly`.

As it is a special case, we can replace it with a try / catch using `Exception`.

**Comment by devemux86** [comment]
Implemented in https://github.com/mapsforge/vtm/pull/873.

**Comment by carlos-mg89** [comment]
That looks great @devemux86 ! Looking forward to see it live, perhaps in a 0.16.1 release.

**Comment by devemux86** [comment]
> perhaps in a 0.16.1 release

You can build locally the library and include it in your app.
For instructions see the [integration guide](https://github.com/mapsforge/vtm/blob/master/docs/Integration.md#snapshots).
