### ISSUE TITLE
animateTo BoundingBox rotates / tilts to default

### ISSUE THREAD

**Issue by wolfgang-ch** [mapsforge/vtm#372]
I would like to keep tilt and rotation when doing an amimation with https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/map/Animator.java#L73

When removing `| ANIM_ROTATE | ANIM_TILT` in https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/map/Animator.java#L100 then it's working as I want it

Can the `state` be an optional parameter for this method?

**Comment by devemux86** [comment]
We can add in every final `animateTo` method (with `Easing.Type`) the `state` parameter too.

Do you want to create a pull request with all these?

**Comment by devemux86** [comment]
Closed via PR #373 by @wolfgang-ch.
