### ISSUE TITLE
jeo

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#375]
`vtm-jeo` uses a very old `jeo` version via a third party repository, which often does not work breaking all modules building.

~~So disabling `vtm-jeo` module until~~ advance it to use the modern `jeo` library: https://github.com/jeo/jeo

**Comment by gruelfin** [comment]
I cannot build vtm-android-example any more, because vtm-jeo is disabled.

**Comment by devemux86** [comment]
`vtm-android-example` doesn't have now active the jeo sample, so it should run / build without it.
i.e. VTM repository continuous building on Travis CI works fine.

What exactly do you see and do you use latest VTM?

**Comment by gruelfin** [comment]
Maybe it is something else, but i need the jeo sample ;). 

With the latest code the latest Android Studio tells me:

> Information:Gradle tasks [:vtm-android-example:assembleDebug]
> Error:Error converting bytecode to dex:
> Cause: java.lang.RuntimeException: Exception parsing classes
> Error:1 error; aborting
> Error:Execution failed for task ':vtm-android-example:transformClassesWithDexForDebug'.
> > com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
> Information:BUILD FAILED
> Information:Total time: 16.5 secs
> Information:3 errors

I thought disabling jeo might be the cause..

**Comment by devemux86** [comment]
> Maybe it is something else, but i need the jeo sample ;).

You can still use it from Maven, or enable its repository and module in VTM.
(BTW see issue description for the reasons - until it's updated)

For the `vtm-android-example` build let's discuss it in [forum](https://groups.google.com/group/mapsforge-dev) providing more details, to not fill this issue. :slightly_smiling_face:

**Comment by devemux86** [comment]
Closing due to lack of interest.
