### ISSUE TITLE
glCreateProgram error 1280

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#376]
I have updated VTM library in my application after 6 months. :-) After that I've started getting GL error during application initialization. I've checked with VTM sample app and got the same error:

```
D/org.oscim.renderer.GLShader: missing uniform: u_scale
E/org.oscim.renderer.GLUtils: glCreateProgram: glError 1280
```

It happens on any Map initialization, even in raster map example.

**Comment by devemux86** [comment]
Seems coming from `LineTexBucket`, though its [history](https://github.com/mapsforge/vtm/commits/master/vtm/src/org/oscim/renderer/bucket/LineTexBucket.java) has only a minor change in that release.

**Comment by Longri** [comment]
yes! At LineTexBucket will load GlShader 'linetex_layer_tex.glsl'!
And this shader has a no uniform float u_scale!

The expected changes comms with 8861125 on 07.08.2016-19:01

I hav not tryed, but I think you can delete the Line 228 on LineTexBucket.java! u_ucale is never used on inner Class Shader!

**Comment by Longri** [comment]
Sorry wrong commit!
Right is: 88611257f1ba310258b1c5aaf8edd72653c81cda on 29.07.2016-21:41

**Comment by andreynovikov** [comment]
Still getting `glError 1280` in logs but without any meaningful debug message before it.

**Comment by devemux86** [comment]
You can go to `GLShader.createProgramVersioned` where the `glCreateProgram` debug message happens and print the vertex / fragment shader sources, to see what causes it?

**Comment by andreynovikov** [comment]
Uncommented exception, something in circle_point.glsl:

```
java.lang.RuntimeException: glCreateProgram: glError 1280
   at org.oscim.renderer.GLUtils.checkGlError(GLUtils.java:116)
   at org.oscim.renderer.GLShader.createProgramVersioned(GLShader.java:142)
   at org.oscim.renderer.GLShader.loadShaderVersioned(GLShader.java:90)
   at org.oscim.renderer.GLShader.createVersioned(GLShader.java:49)
   at org.oscim.renderer.bucket.CircleBucket$Renderer$Shader.<init>(CircleBucket.java:106)
   at org.oscim.renderer.bucket.CircleBucket$Renderer.init(CircleBucket.java:89)
```

**Comment by devemux86** [comment]
Circle shaders need additional improvements and could not work correctly on all GPU (have seen issues on Mali).
