### ISSUE TITLE
Mapsforge: Reverse Geocoding

### ISSUE THREAD

**Issue by jvoyatz** [mapsforge/vtm#383]
Hello,

It is already implemented in Mapsforge. [Here](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/ReverseGeocodeViewer.java) you can found the sample code.

This feature gives the user the ability to see info regarding POI or Ways in a radius.

**Comment by devemux86** [comment]
That would be a nice addition in VTM, regarding Mapsforge maps.
We'd probably need to enhance first the reader API.

For reference the Mapsforge issue is https://github.com/mapsforge/mapsforge/issues/727.

Its sample has Reverse Geocoding at touch, reading the map data for the area and returning:
- POI(s) in specified touch radius
- Way(s) containing touch point

**Comment by devemux86** [comment]
See [ReverseGeocodeActivity](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/ReverseGeocodeActivity.java).
