### ISSUE TITLE
Map tiles disappear after some time

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#384]
Using `MapsforgeMapActivity` from `vtm-android-example` on Eco 1300 tablet (Android 4.4.2).

Discussion in [forum](https://groups.google.com/forum/#!topic/mapsforge-dev/036jFPLU6Is).

**Comment by omartaha1003** [comment]
Anything new??? I'm still stuck with this problem

**Comment by devemux86** [comment]
Can discuss in [forum](https://groups.google.com/group/mapsforge-dev) and if there is interest from community to contribute.
