### ISSUE TITLE
Mapsforge: avoid additional simplification

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#39]
Avoid additional simplification in `MapDatabase` besides that existed in Mapsforge maps.
As it seems causing render artifacts and lesser detail on map elements.

**Comment by devemux86** [comment]
I reopen this as we have other cases, like artifacts on lakes due to the additional simplification in code.

See commit 13fd8c4e3c0dede1a2c6471c645a14890ab7880f in `issue_39` branch for the change.
In screenshots, besides the artifacts fix, we have also more detail in the map.

With the additional simplification:
![1](https://cloud.githubusercontent.com/assets/3484020/17615113/84426d5a-6074-11e6-983c-60a1d34f224b.png)

Without the additional simplification:
![2](https://cloud.githubusercontent.com/assets/3484020/17615119/9135831c-6074-11e6-88ff-b1d779f93a9c.png)

@hjanetzek why the need for extra simplification besides that already existed in Mapsforge maps?

**Comment by stleusc** [comment]
I still see artifacts in water just above the road crossing at the bottom of the map. And also one further up (about 1.5 tiles higher).
Are they fixed now too?

**Comment by devemux86** [comment]
Those artifacts appear also due to OpenGL - completely different than Mapsforge's software rendering.

For example there was need for tessellation in `nosea` land 'split' polygons, implemented in #37 and #38.
Maybe additional work need in more areas, please open a new issue for that.
