### ISSUE TITLE
AssetsRenderTheme and StreamRenderTheme fail to open themes

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#392]
Because of the Mapsforge themes compatibility changes, `AssetsRenderTheme` and `StreamRenderTheme` fail to open themes.

Report by @mathieudebrito in https://github.com/mapsforge/vtm/pull/388#issuecomment-327116483.

**Comment by devemux86** [comment]
Issue was due to `ThemeUtils.isMapsforgeTheme` uses the `theme.getRenderThemeAsStream()` before the theme parser, causing some theme types to fail to use it again.

@mathieudebrito can you check if your implementation works ok now?

**Comment by mathieudebrito** [comment]
I just checked and still the same :  
 ```
org.oscim.theme.IRenderTheme$ThemeException: stream closed
09-05 14:36:25.183 23365-23365/? W/System.err:     at org.oscim.theme.XmlThemeBuilder.read(XmlThemeBuilder.java:114)
09-05 14:36:25.183 23365-23365/? W/System.err:     at org.oscim.theme.ThemeLoader.load(ThemeLoader.java:54)
09-05 14:36:25.183 23365-23365/? W/System.err:     at org.oscim.theme.ThemeLoader.load(ThemeLoader.java:46)
09-05 14:36:25.183 23365-23365/? W/System.err:     at org.oscim.map.Map.setTheme(Map.java:203)
09-05 14:36:25.184 23365-23365/? W/System.err:     at org.oscim.map.Map.setTheme(Map.java:195)
```

**Comment by devemux86** [comment]
Build had failed due to web modules, now should be ok and the snapshot artifacts are published.

The samples `MapsforgeStyleActivity` with `AssetsRenderTheme` and `MapsforgeStyleTest` with `StreamRenderTheme` work again.

@mathieudebrito can you check?
BTW your example had `StreamRenderTheme` with assets folder. If being on Android better use the `AssetsRenderTheme`.

**Comment by mathieudebrito** [comment]
I tried many times using `AssetsRenderTheme` but I get :  

```
org.oscim.theme.IRenderTheme$ThemeException: asset
09-05 15:26:02.537 26862-26862/? W/System.err:     at org.oscim.theme.XmlThemeBuilder.read(XmlThemeBuilder.java:114)
09-05 15:26:02.537 26862-26862/? W/System.err:     at org.oscim.theme.ThemeLoader.load(ThemeLoader.java:54)
09-05 15:26:02.537 26862-26862/? W/System.err:     at org.oscim.theme.ThemeLoader.load(ThemeLoader.java:46)
09-05 15:26:02.537 26862-26862/? W/System.err:     at org.oscim.map.Map.setTheme(Map.java:203)
09-05 15:26:02.537 26862-26862/? W/System.err:     at org.oscim.map.Map.setTheme(Map.java:195)
```

calling :  

`new AssetsRenderTheme(context, "renderthemes/","my_very_awesome_theme.xml", callback);`

**Comment by devemux86** [comment]
`AssetsRenderTheme` parameters have changed, you're using older cached snapshot.
See the [integration guide](https://github.com/mapsforge/vtm/blob/master/docs/Integration.md#snapshots) for how can force latest snapshot and `MapsforgeStyleActivity` for the use.

**Comment by mathieudebrito** [comment]
I added the force latest snapshot, still the same :p

**Comment by devemux86** [comment]
How you read the theme?

**Comment by devemux86** [comment]
On Android?
Like mentioned above, better use `AssetsRenderTheme`, that's its purpose. :slightly_smiling_face: 
`StreamRenderTheme` is suitable other streams, also `InputStream` in Android assets is limited.

**Comment by devemux86** [comment]
BTW if `CustomVtmThemes` is like [VtmThemes](https://github.com/mapsforge/vtm/blob/master/vtm-themes/src/org/oscim/theme/VtmThemes.java) then can use it directly.

**Comment by mathieudebrito** [comment]
Weird, I was sure I answered it at the moment...
It works perfectly after your changes !
Thanks again :)
