### ISSUE TITLE
Overzoom: separation of data extraction and rendering

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#393]
Overzoom implementation, i.e. separation of data extraction and rendering.

**Comment by boldtrn** [comment]
I had a brief look at this issue. How would this be approached?

I was able to track down the MaxZoom usage to `TileManager#update`.

If I understand this correctly at this point we would add the "over zooming", forcing the map to re render? I tried this, but it did not change anything, probably we have to somehow propagate this or tell the renderer about it?

**Comment by boldtrn** [comment]
I thought about somehow adding it to the jobs in the TileManager?

**Comment by boldtrn** [comment]
I just stumbled over a related thread here https://github.com/mapbox/vector-tiles/issues/21

**Comment by devemux86** [comment]
Thanks for the search and the extra info!
Will have to check it and at some time push that feature forward. :slightly_smiling_face:

**Comment by devemux86** [comment]
> I thought about somehow adding it to the jobs in the TileManager?

Could use position zoom instead of tile zoom at visible tiles scan, i.e. change [TileManager:308](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/layers/tile/TileManager.java#L308):
```java
mScanBox.scan(pos.x, pos.y, pos.scale, pos.zoomLevel, mMapPlane);
```

But then other things happen, like buildings which are fixed in min/max zoom 17.

**Comment by devemux86** [comment]
Map overzoom implementation:
- All vector tile sources (also Mapsforge) have a new overzoom parameter.
- It defines up to which zoom level the data extraction happens.
That level can be used then for the next ones (until map max zoom).
- The render theme rules can be applied now also on >overzoom levels.
i.e. for the whole zoom range [min...overzoom...max].
- The overzoom parameter is optional. If not set then it's same as max zoom and map works like now.

A fine example of the new overzoom exists in OpenMapTiles samples.
Their vector tiles stop at zoom 14, but now we can render the map with theme rules for all map zoom levels (>14).

There is still work with 3D buildings overzoom, if anyone is interested.
If apply max zoom >17 then the 3D buildings are rendered again as new at zooms >17. As then the tiles >17 are considered "new", though they now come from overzoom level's data.

**Comment by devemux86** [comment]
Now that vector tile layers overzoom is ready, see:
- #503 for building layers overzoom
- #504 for label layer overzoom
