### ISSUE TITLE
Rendering street names in abbreviated form.

### ISSUE THREAD

**Issue by Zoetrophy** [mapsforge/vtm#395]
Things like "Avenue" to "Ave", "Southeast" to "SE", etc.

Nearly every street name in my city, for example, is terminated by an intermediate direction, and not only does it make for a large waste of space in rendering them all in unabbreviated form, it can prevent the street names from rendering at lower zoom levels entirely.

Here's a particularly egregious example:
![screenshot_20170907-050000](https://user-images.githubusercontent.com/16235330/30155041-ce5679ce-9389-11e7-87fb-dbf8963283cb.png)

There's already a list of abbreviations that could potentially be used on the OSM wiki: http://wiki.openstreetmap.org/wiki/Name_finder:Abbreviations

**Comment by devemux86** [comment]
The element names come from the tile source. They're not post-processed in any way. That would require after all doing that in each language as maps have multiple locales.

BTW is it with an offline Mapsforge map file?

**Comment by Zoetrophy** [comment]
Yes, it is with an offline Mapsforge file, and what I meant to say was that post-processing should be added in the first place, at least as an option (though I may not have conveyed that very well).

Speaking to the necessity of doing it for each potential language, the wiki page I linked does include multiple languages already.

**Comment by devemux86** [comment]
> I meant to say was that post-processing should be added in the first place, at least as an option

That would be indeed useful (as option) and increase map readability.

**Comment by andreynovikov** [comment]
You can write your own [TileLoaderProcessHook](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/layers/tile/vector/VectorTileLayer.java#L136) and rewrite values for name tags.

**Comment by devemux86** [comment]
That's more work for map-writer or pre-processors like [TagTransform](https://wiki.openstreetmap.org/wiki/Osmosis/TagTransform).
