### ISSUE TITLE
3D Height  in render styles

### ISSUE THREAD

**Issue by sunshine0576** [mapsforge/vtm#399]
I use com.vividsolutions.jts.triangulate.ConformingDelaunayTriangulationBuilder to build Triangles.
I want to show Triangles on my map. 	
If you can achieve the drawing of the slope, the 3d data display will be very useful。

    private Geometry getTriangulars(List coorList) {
        Coordinate[] coordinates =new Coordinate[coorList.size()];
        coorList.toArray(coordinates);
        MultiPoint multiPoint=geoFactory.createMultiPoint(coordinates);
        Geometry hull=multiPoint.convexHull();
        ConformingDelaunayTriangulationBuilder conformTriBuilder = new ConformingDelaunayTriangulationBuilder();
        conformTriBuilder.setSites(multiPoint);
        Geometry triangles=conformTriBuilder.getTriangles(geoFactory);
        return triangles;
    }

**Comment by devemux86** [comment]
What exactly do you mean / request with that issue?

BTW can see some use of levels in rendering at [OSMIndoorLayer](https://github.com/mapsforge/vtm/blob/master/vtm-jeo/src/org/oscim/layers/OSMIndoorLayer.java) for building floors.

**Comment by sunshine0576** [comment]
TessJNI:   addContour2D(geom.index, geom.points);
when i draw a Geometry ，VectorLayer does not support 3D operations.
Is there a good way to implement 3d geometry?

**Comment by sunshine0576** [comment]
ExtrusionBucket can render 3D Geometry,but i do not konw  how to use it in VectorLayer
