### ISSUE TITLE
jeo: different style for different polygons does not work

### ISSUE THREAD

**Issue by JonasDaWi** [mapsforge/vtm#400]
In JeoIndoorMapActivity Android example I want to show Saal 11 and Saal 13 and show them with different styles.
So I edited JeoTest.java (around line 75),  like this:
```
            style = Carto.parse("" +
                    "#way {" +
                        "[name='Saal 11']{" +
                        "  line-width: 5;" +
                        "  line-color: #ff000000;" +
                        "  polygon-fill: #ffff0000;" +
                        "}"+
                        "  [name='Saal 13']{" +
                        "  line-width: 5;" +
                        "  line-color: #ffff0000;" +
                        "  polygon-fill: #ff00ff00;" +
                        "}"+
                     "}"
            );
```
The result can be seen in the screenshot:

![device-2017-09-13-175200](https://user-images.githubusercontent.com/5794789/30387343-7220b6f6-98ac-11e7-8d7c-77ab2d3e30df.png)

So the selection using the name parameter works, because only Saal 11 and Saal 13 are shown. 

What does not work is the different style for Saal 13: the polygon of Saal 13 should have a green filling. Instead, it shares its style with Saal 11.

**Comment by devemux86** [comment]
Can discuss in [forum](https://groups.google.com/group/mapsforge-dev) and if there is interest from community to contribute.
