### ISSUE TITLE
Texture atlas GL error 1285 OUT_OF_MEMORY

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#404]
Testing texture atlas on Android via [AtlasThemeActivity](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/AtlasThemeActivity.java) at some devices we have out of memory errors, making the map unusable:
```java
org.oscim.android.test E/org.oscim.renderer.GLUtils: finish: glError 1285
```

**Comment by devemux86** [comment]
cc @Longri

**Comment by Longri** [comment]
Which devices?
maybe texture are to big and wie must check max TextureSize

**Comment by devemux86** [comment]
Tested on some available devices [Samsung I9100 Galaxy S II](http://www.gsmarena.com/samsung_i9100_galaxy_s_ii-3621.php) and [Samsung Galaxy Tab 4 7.0 LTE](http://www.gsmarena.com/samsung_galaxy_tab_4_7_0_lte-6241.php), both with Mali-400 GPU.

**Comment by Longri** [comment]
do you have such divices?

Cann you try to set MAX_ATLAS_SIZE to 1024?

![1](https://user-images.githubusercontent.com/2542295/30539742-2a8bbcb6-9c74-11e7-9afc-8e994b6991a8.png)

**Comment by devemux86** [comment]
Already check that, the OOM seem to be much less even with `MAX_ATLAS_SIZE = 128`!

BTW forgot to mention that the issue appears mostly in dense areas around zoom 15 where symbols start appearing.

**Comment by Longri** [comment]
I'm trying to reactivate my old S2, which I found deep in my closet.
Then I'll try to find the mistake.

**Comment by devemux86** [comment]
@Longri have you tested again texture atlas?

**Comment by Longri** [comment]
I'm sorry, I totally forgot.

I wrote a library that queries the maximum size of an OpenGLxture and then, based on this size, creates an atlas.

The positions in the atlas are calculated using Native.

I wanted to test this library thoroughly before creating a PR.

And then I just forgot.

The library I wrote is based on LibGdx. I will rewrite them now and remove all LibGdx dependencies to create a PR.

The advantage of this library is that the maximum size is used. And the pack algorithm is very effective here and comes from : https://github.com/TeamHypersomnia/rectpack2D

**Comment by devemux86** [comment]
> Who compiled the native sources last time?

I did all native builds when forked VTM.
On Linux for all platforms and on Mac.

(If there is need I'll do that again)

But first must understand:

> I tried to repair the JNI module and made the necessary changes in the JinGen.

Why and what needs to be changed?

**Comment by devemux86** [comment]
> But are Linux32 and Win32 really necessary? I would also leave out Mac32.

Since there are users still using 32bit OS, we need to provide support for all.

**Comment by Longri** [comment]
> Why and what needs to be changed?

The'build-ios.xml.template' contains an incorrect path to the iOS SDK!

> Since there are users still using 32bit OS, we need to provide support for all.

I don't think anyone else uses 32Bit, but I will do my best to compile the missing platforms as well.

**Comment by devemux86** [comment]
I didn't build iOS - you maintain it.
You didn't answer why a re-build of the the other platforms is needed.

**Comment by Longri** [comment]
for include https://github.com/TeamHypersomnia/rectpack2D

**Comment by devemux86** [comment]
Hmm and with each needed update of the library we'd need to rebuild the binary natives?

**Comment by Longri** [comment]
Why do we have to update?
The libtess2 was also never updated!

**Comment by Longri** [comment]
> I did all native builds in #14 when forked VTM.
> On Linux for all platforms and on Mac.

Which compiler did you use, on Linux?

**Comment by devemux86** [comment]
That was some years ago on another machine, need to remember.. :slightly_smiling_face:

**Comment by devemux86** [comment]
On some Android devices there was the OOM issue.
Can build just that, test if fixes anything and at the end see the other platforms.

**Comment by Longri** [comment]
Ok, mips/mips64 and armeabi are done, they are no longer supported by the NDK.

```
     [exec] Android NDK: MIPS and MIPS64 are no longer supported.    
     [exec] Android NDK: NDK Application 'local' targets unknown ABI(s): mips mips64    
     [exec] Android NDK: Please fix the APP_ABI definition in /home/default/Dokumente/gits/vtm/jni/jni/Application.mk    
     [exec] /home/default/android-ndk-r17/build/core/setup-app.mk:79: *** Android NDK: Aborting    .  Stop.

```

**Comment by devemux86** [comment]
Did you test the changes with regular architecture so see first if fixes the issue?

**Comment by Longri** [comment]
Not quite so fast, please.

Now I have a point where the old native sources are compiled.

Now it's time for the new changes.

I want to pack the whole thing neatly into a PR that doesn't contain hundreds of commits. So that you can understand the changes!

**Comment by Longri** [comment]
That's right, but I also wanted an easy way to compile the natives.  Maybe I'll do my own PR.



We could also introduce a native version number, which is checked when loading.  This ensures that the correct Native version is loaded.

**Comment by devemux86** [comment]
> We could also introduce a native version number, which is checked when loading. This ensures that the correct Native version is loaded.

The natives are not provided or used separately to need custom version. They're tied to the whole library and are provided conveniently as [regular versioned jars](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.mapsforge%22), following library publish schedule.

**Comment by Longri** [comment]
Hi Emux, is there a function runOnMainThread()?
All platforms are Ok, except Android!
with ask for GL.MAX_TEXTURE_SIZE on non MainThread will return zero!

**Comment by devemux86** [comment]
`Map` has several such helper methods propagating to each platform implementations.

**Comment by Longri** [comment]
Yes, i have seen.
But I have no Map instances on TextureAtlasUtils.
And no Gdx.app.postRunnable(task);

**Comment by devemux86** [comment]
Aren't supposed to be on main thread already?

**Comment by devemux86** [comment]
Can ask that in `Activity` with known methods "before" loading a theme, store the result in a static variable and then use it in `TextureAtlasUtils` class.

**Comment by Longri** [comment]
I think that would be best!
Because yes I am in the MainThread but Android answers the question about GL_MAX_TEXTURE_SIZE only in the UiThread and only when the GLSurfaceView is created.

I'm trying to find a good solution.

So be patient a little longer.

**Comment by Longri** [comment]
Okay, I've found a solution.
When Gl_SurfaceView is created, I fire an event that receives the MapActivity and only then do I call the CreateLayers method.

But I still have an OOM, which will always be possible. 

If a theme has a lot of images/icons, these are completely loaded into memory to create the atlas.
I think it would be better to not load the bitmaps here but to give the BitmapPacker only the path of the bitmaps and to load, draw and destroy one bitmap after another when drawing the atlas.

**Comment by devemux86** [comment]
What's the implementation to discuss? Because many things were mentioned above.

Are there eventually any new native libs involved or we better continue with regular Java for texture atlas (by far the best solution) ?

> When Gl_SurfaceView is created, I fire an event that receives the MapActivity and only then do I call the CreateLayers method.

Why exactly need all that?
e.g. there isn't any createLayers in `MapsforgeActivity` sample where most tests are made.

> If a theme has a lot of images/icons, these are completely loaded into memory to create the atlas.
I think it would be better to not load the bitmaps here but to give the BitmapPacker only the path of the bitmaps and to load, draw and destroy one bitmap after another when drawing the atlas.

So improve `TextureAtlasUtils` implementation, that seems nice idea.

**Comment by Longri** [comment]
> Are there eventually any new native libs involved or we better continue with regular Java for texture atlas (by far the best solution) ?

The native code I introduced calculates only the rectangles of the items in the atlas. Everything else happens in Java.

> Why exactly need all that?
> e.g. there isn't any createLayers in MapsforgeActivity sample where most tests are made.

The CreateLayers() method is currently called in onCreate. The Theme will loaded at this time and on this point is the GL_SerfaceView not created.

I have changed the MapActivity to:

```
 protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(mContentView);

        setTitle(getClass().getSimpleName());

        mMapView = (MapView) findViewById(R.id.mapView);
        mMap = mMapView.map();
        mPrefs = new MapPreferences(MapActivity.class.getName(), this);
        GLState.event.bind(new GLState.Listener() {
            @Override
            public void onGLStateInitEvent(Event event) {
                MapActivity.this.runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        createLayers();
                    }
                });
            }
        });
    }

    public void createLayers(){
    }
```

All Activities derived from MapActivity can then overwrite createLayers() and load the Theme at the right time.

**Comment by devemux86** [comment]
> The native code I introduced calculates only the rectangles of the items in the atlas. Everything else happens in Java.

Why would need native code for that? How it works right now in Java?

> All Activities derived from MapActivity can then overwrite createLayers() and load the Theme at the right time.

I introduced the `createLayers` method as a way for other samples to override, simply for all Samples to work without replicate much code.
Will see the implementation, as most users have their own ways to use the library API and need to be flexible.

**Comment by devemux86** [comment]
> All Activities derived from MapActivity can then overwrite createLayers() and load the Theme at the right time.

BTW such change should only be applied to the specific Sample which demonstrates the texture atlas, that is `AtlasThemeActivity`.
The other samples do not use texture atlas, so shouldn't change anything in them.

**Comment by Longri** [comment]
> BTW such change should only be applied to the specific Sample which demonstrates the texture atlas, that is AtlasThemeActivity.
> The other samples do not use texture atlas, so shouldn't change anything in them.

Ok, then I will take these changes back and put them only on AtlasThemeActivity.

Now the question remains whether we should log a WARNING if a user tries to use the atlas before the GL_SurfaceView was created and fall back to a minimal value (e.g. 512) or throwing a RuntimeException.


> Why would need native code for that? How it works right now in Java?

Because the calculation is time consuming. Similar to the tessellate calculation, which is also used Native.
The code cannot be converted to Java because it has pointer movements, which do not exist under Java.

The C-library, which I found, also has the advantage to do the calculations in such a way, that an atlas really only has the size it needs. All other packers based on Java specify a size and use it. For the C-library, only the maximum size is specified.

**Comment by devemux86** [comment]
Need to see first if it can fix this issue, then can discuss further the implementation.
If it cannot fix this issue, then no native changes are needed in the library. :slightly_smiling_face:

**Comment by Longri** [comment]
PR #542 will fix this
