### ISSUE TITLE
How to setup own tiles server for OSciMap vtm format

### ISSUE THREAD

**Issue by kaythararama** [mapsforge/vtm#406]
Hi,

I am newbie to VTM, the vtm is amazing. 
1.
I would like to setup my own tiles server and publish custom maps with vtm format.
I try 
https://github.com/opensciencemap/TileStache/tree/master/TileStache/OSciMap4
on CentOS 7. Also followed their instructions, but not success.
Is there any instructions or guidelines for own OSciMap vtm tiles server?

2.
Currently I am already running GeoServer. This server supports .geojson, .topojson. .pbf formats.
I try vtm-examples by replacing server url, but not working.
Also mapzen examples not working now with mapzen tiles server.

Pls help me to start vtm over own tiles server.

**Comment by devemux86** [comment]
There is also a forum topic [here](https://groups.google.com/forum/#!topic/mapsforge-dev/phptnh_2JCE).

Some seem to have succeeded in VTM server, would be nice if they share their knowledge with community. :slightly_smiling_face: 

BTW VTM supports also Mapbox .mvt and .geojson vector tiles, e.g. via Mapzen.
See [MapzenMvtMapActivity](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/MapzenMvtMapActivity.java) and [MapzenGeojsonMapActivity](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/MapzenGeojsonMapActivity.java) on Android or [MapzenMvtTest](https://github.com/mapsforge/vtm/blob/master/vtm-playground/src/org/oscim/test/MapzenMvtTest.java) and [MapzenGeojsonTest](https://github.com/mapsforge/vtm/blob/master/vtm-playground/src/org/oscim/test/MapzenGeojsonTest.java) on Desktop (need an api key).

**Comment by andreynovikov** [comment]
There is no much deal to setup the server. There are almost-out-of-the-box solutions like TileStache or Utilery. The problem is with data. You have to define how to get, process and output data. Knowledge of how it is configured on VTM server is "lost", TileStache does not contain ane predefined setups, Utilery provides a basic setup you can start from: https://github.com/tilery/utilery-osm-recipe

**Comment by andreynovikov** [comment]
Just a hint. TileStache looks more powerful but it is much more difficult to setup then Utilery. Utilery (with Imposm as data preparation tool) can be setup in minutes. And if you plan to process full planet you will have to use very powerful server. It can take a week to extract planet file into database. And database will use from 300G to 1.2T of disk space. This is without tiles that you will definitely have to cache...
