### ISSUE TITLE
Render themes

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#41]
Ongoing task for improving render themes.

**Comment by mathieudebrito** [comment]
Hi @devemux86 !

What is the ref tag about ?

**Comment by devemux86** [comment]
See in [OpenStreetMap Wiki](http://wiki.openstreetmap.org/wiki/Key:ref), it's about highway reference numbers or codes.

**Comment by mathieudebrito** [comment]
Ok thank you !!

--
Mathieu de Brito
www.mathieudebrito.fr <http://mathieudebrito.fr>
Fr : +33 6 87 36 74 78
