### ISSUE TITLE
Line symbol can not be generated without gaps

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#412]
Have tried this new feature for cliffs and failed. Looks like `repeat-gap` with value less then 30 does not work. I've thought it's because of `repeat-start`, have set it to 0 but still get too large gaps between symbols. I use [square icon](https://github.com/andreynovikov/maptrek/blob/master/app/src/main/assets/symbols/natural/cliff.svg) with a tick. There is no much space around. But the gap between symbols is about 1 centimeter on smartphone screen.

@devemux86 said (#124):
> Trying even with the oneway symbol which doesn't have empty canvas at its width and with `repeat-gap="0" repeat-start="0"`, we cannot achieve continuous symbols rendering. That seems related to the underlying stipples mechanism and not with line symbols (using it).

**Comment by devemux86** [comment]
Can discuss in [forum](https://groups.google.com/group/mapsforge-dev) and if there is interest from community to contribute.
