### ISSUE TITLE
Rendering scaling is broken

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#416]
After I have updated VTM sources map in my application became 2 times larger. It looks like base zoom level was shifted. I have looked at #401 but it does not seem to be a source of the problem. I tried to set `userScale` but then all text, lines and icons became two times smaller.

I do not want to rework my styles, do not want to redraw the icons, do not want to regenerate all the map data! How can I turn base scale back?

**Comment by devemux86** [comment]
It depends from when the update comes, e.g. see #236.

**Comment by devemux86** [comment]
Can use `CanvasAdapter.userScale` to play with the generic scaling.
Or influence more via `Tile.SIZE`.

**Comment by andreynovikov** [comment]
Not so far. I have reverted back to e1db67f099d2055c388d01285acebf0495d31aa0 and everything is working as intended again.

**Comment by devemux86** [comment]
After that, the scale related changes seem being the https://github.com/mapsforge/vtm/commit/9283b805940dc52440061b118bba66ac0e007d63 (automatic tile size calculation) and #401 (fix strong lines).

**Comment by andreynovikov** [comment]
This is all about `Tile.calculateTileSize()`. This issue can be closed, I will write on that subject in the commit.

**Comment by devemux86** [comment]
We can add a flag in `Parameters` to make tile size calculation non automatic and allow setting fixed values.

**Comment by andreynovikov** [comment]
This would be perfect.

**Comment by devemux86** [comment]
I added via 233f0c4f7edd317b303c2198316f28df66d169ff the boolean `Parameters.CUSTOM_TILE_SIZE` (default false).
If set `true` then can set again the `Tile.SIZE` before `MapView` initialization.
