### ISSUE TITLE
Render themes: tag transform

### ISSUE THREAD

**Issue by Gustl22** [mapsforge/vtm#420]
For each tile source (Mapzen, Mapsforge map, Openmaptiles, ...) a new theme is needed. With a Tag resolver / adapter in an extra xml file, which is separated from the theme, more compatibility is given. And you can use all vtm mapsforge themes for the other sources.

**Comment by devemux86** [comment]
Note that those tile sources (which change OpenStreetMap tags), often require some reorganization in their themes, as their changes are more than simple renamed tags.
And they could also put the labels in separate layers, making their themes more complex.

**Comment by Gustl22** [comment]
Yes, so some kind of resolving logic would be needed. 
My point is, that currently there's no way to use unified tags in code, or look up tags from theme.

**Comment by devemux86** [comment]
Could mean that cannot avoid extra themes for those tile sources changing OSM tags and more importantly their structure.

Also best place for a resolver could be a simple class (as now) instead of an extra xml file (which would require extra parsing).

**Comment by Gustl22** [comment]
Ok so you would prefer a new Resolver Class for each TileSource. If you agree, i'll give it a try.

**Comment by devemux86** [comment]
First need to check if that can work at all.

Like studying layers definition for [Mapzen](https://mapzen.com/documentation/vector-tiles/layers/) and [OpenMapTiles](https://openmaptiles.org/schema/), as their changes are also structural besides renaming.
So eventually could not avoid their own themes.
e.g. they group layers differently, so requires different organization in theme rules structure.
OpenMapTiles has even separate layer for transportation names.

**Comment by Gustl22** [comment]
Oh sorry, i only meant to create a look-up class for several tags, which can be extended over the time. And leave the themes, like they are.

**Comment by devemux86** [comment]
The idea is interesting!
Important is if we cannot avoid the extra themes (due to aforementioned reasons), then such a look-up won't be used by users as eventually they'll need to have specific theme files for greater flexibility.

For example, comparing `default.xml` and current `mapzen.xml` can reveal if their only difference is tag names.

**Comment by Gustl22** [comment]
Yes there's a risk of mistake. Maybe a note in documentation part of methods with a reference to theme prevent users from misapprehension.

**Comment by andreynovikov** [comment]
There is already [TileLoaderProcessHook](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/layers/tile/vector/VectorTileLayer.java#L136) that can rewrite any element. You can just write necessary hooks and add them to the layer according to tile source.

**Comment by devemux86** [comment]
Closing as OpenMapTiles recently proved that the differences among providers and their changes to OSM "structure" are unfortunately major to avoid separate theme per case, which now seems the more safe and simple solution.

**Comment by Gustl22** [comment]
Thanks to @andreynovikov for your proposals.
If I have a reasonable solution, I'll let you know or discuss it. At the moment this is a touchy topic. But somewhere in the future there should be a separation of colors/styles and data interpretation.
But of course can close it for now. :smile:

**Comment by Gustl22** [comment]
@devemux86:
I added an approach to change tags in renderthemes, if necessary (e.g. for S3DB). See [tag_tilesource](https://github.com/Gustl22/vtm/commit/8264323219d601a4b7c586ad5cf50283c9c0290a) branch.
Each tag can handled separately (tag and key only, too) and changed for all processes or only as lookup option.
Example in Nextzen/Mapzen:
`<tag-adaption k="roof_shape" k-osm="roof:shape" replace="false"/>`

**Comment by devemux86** [comment]
Thanks! I had a quick look and have some remarks.
Perhaps you can post a PR & we can discuss there?

**Comment by devemux86** [comment]
Implemented via #587.
