### ISSUE TITLE
Ferries are not rendered

### ISSUE THREAD

**Issue by boldtrn** [mapsforge/vtm#421]
I hope I haven't missed anything, but I think the render themes don't contain a rendering for ferries? I just had a look at the [Kurviger App](https://play.google.com/store/apps/details?id=gr.talent.kurviger.pro) and saw that no ferries are drawn. I searched the render theme, but couldn't find a ferry rule.

**Comment by devemux86** [comment]
Which OSM tags, the `route="ferry`?
I think it exists currently in [osmarender.xml](https://github.com/mapsforge/vtm/blob/master/vtm-themes/resources/assets/vtm/osmarender.xml) theme.

**Comment by boldtrn** [comment]
A yes you are right. I just checked the default render theme.

**Comment by devemux86** [comment]
Let's add it to all themes.
