### ISSUE TITLE
Themes XML pull parser

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#431]
VTM uses XML push parsing (SAX) for themes, which can be slow and with less performance for large map styles, waiting for the whole theme to build up.

We can integrate also [kXML2](http://www.kxml.org/) XML pull parser, which is small / fast and well tested in [Mapsforge](https://github.com/mapsforge/mapsforge), with the XML rules accessible immediately when they are available.

Furthermore it's based on the common XML pull API, so we can plug any platform pull parser (see https://github.com/mapsforge/mapsforge/issues/974).

**NOTE:
Since it's a core change, it should be added as an extra option.
We should keep current classes / implementation unmodified for compatibility.**

**Comment by andreynovikov** [comment]
I have a high demand for a parser that supports `xi:include` instruction. Do you know any? Built-in Android implementation does not support it. It looks like kXML2 does not support it too.

**Comment by devemux86** [comment]
Do you mean the [SAXParserFactory.setXIncludeAware](https://developer.android.com/reference/javax/xml/parsers/SAXParserFactory.html#setXIncludeAware(boolean))?

**Comment by andreynovikov** [comment]
Yes

**Comment by devemux86** [comment]
We could activate XInclude processing, but that only works on Desktop Java, the Android `SAXParserFactoryImpl` doesn't supports it.

**Comment by andreynovikov** [comment]
I know, that's why I would be happy if it will be substituted with anything that supports it.

**Comment by devemux86** [comment]
Can discuss in [forum](https://groups.google.com/group/mapsforge-dev) and if there is interest from community to contribute.

**Comment by devemux86** [comment]
Implemented in #786.
