### ISSUE TITLE
Build fails after upgrading gradle plugin to version 3.0.0

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#432]
I have updated Android Studio to version 3.0 and it updated gradle to 3.0.0. After that it failed to build anything with the following error:

    Error:(72, 1) Could not determine the dependencies of task ':vtm-android-gdx:fatJarRelease'.
    > Could not resolve all files for configuration ':vtm-android-gdx:compile'.
       > Could not resolve project :vtm-android.
         Required by:
             project :vtm-android-gdx
          > Cannot choose between the following configurations of project :vtm-android:
              - debugApiElements
              - debugRuntimeElements
              - releaseApiElements
              - releaseRuntimeElements
            All of them match the consumer attributes:
              - Configuration 'debugApiElements':
                  - Found com.android.build.api.attributes.BuildTypeAttr 'debug' but wasn't required.
                  - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
                  - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
                  - Found org.gradle.api.attributes.Usage 'java-api' but wasn't required.
              - Configuration 'debugRuntimeElements':
                  - Found com.android.build.api.attributes.BuildTypeAttr 'debug' but wasn't required.
                  - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
                  - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
                  - Found org.gradle.api.attributes.Usage 'java-runtime' but wasn't required.
              - Configuration 'releaseApiElements':
                  - Found com.android.build.api.attributes.BuildTypeAttr 'release' but wasn't required.
                  - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
                  - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
                  - Found org.gradle.api.attributes.Usage 'java-api' but wasn't required.
              - Configuration 'releaseRuntimeElements':
                  - Found com.android.build.api.attributes.BuildTypeAttr 'release' but wasn't required.
                  - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
                  - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
                  - Found org.gradle.api.attributes.Usage 'java-runtime' but wasn't required.

After switching back to gradle 2.3.3 it resumed building without errors.

**Comment by devemux86** [comment]
New Gradle and Android plugin have fundamental API changes, which require some work in the scripts.
I'm still doing some tests and will push the new scripts soon.

**Comment by devemux86** [comment]
Closing as will be fixed as part of the several changes in #433.
