### ISSUE TITLE
Gradle 4 and Android plugin 3

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#433]
Gradle 4 and [Android plugin 3](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html) require changes in our Gradle scripts for the build process to work again and use all the latest improvements.

**Comment by devemux86** [comment]
Gradle does not seem to allow `vtm-playground` or `vtm-theme-comparator` to run via Android Studio.
So I enabled in their [build.gradle](https://github.com/mapsforge/vtm/blob/master/vtm-playground/build.gradle) the application plugin.

For `vtm-playground` can change the `mainClassName` to run each example and can pass args, e.g.:
```groovy
./gradlew :vtm-playground:run -Pargs=/path/to/map
```

**Comment by devemux86** [comment]
@Longri could you check iOS?

**Comment by Longri** [comment]
Sorry, but I can't check right now.

RoboVm is currently only running with IntelliJ 2017.2!

But here I have again the dependency problem that I could only solve with the Android-Studio.

I'll stay here, but I don't expect any problems!

same for #464

**Comment by devemux86** [comment]
Asking to make a minor release for the transitive dependencies.

BTW why not using Android Studio with VTM to solve all those problems?
IDEA usually merges AS updates in next versions.

**Comment by Longri** [comment]
> RoboVm is currently only running with IntelliJ 2017.2!

**Comment by devemux86** [comment]
With latest Android Studio 3.2 the Desktop samples seem to run again directly from inside the IDE.
