### ISSUE TITLE
org.oscim.tiling.source.PbfDecoder$ProtobufException:  invalid type for feature: 6

### ISSUE THREAD

**Issue by sunshine0576** [mapsforge/vtm#445]
org.oscim.tiling.source.PbfDecoder$ProtobufException: [X:1687, Y:873, Z:11] invalid type for feature: 6

org.oscim.tiling.source.mvt.TileDecoder;
Line:396 
      default:
                    error(mTile + " invalid type for feature: " + tag);
                    break;

Line 350 int tag = (val >>> 3); 
//tag:0  val=1
//tag:0  val=2
//tag:0  val=4
//tag:18  val=151

more： features is not null, features.size()>0

**Comment by sunshine0576** [comment]
I use java-vector-tile-1.1.2  create mvt.

**Comment by devemux86** [comment]
MVT `TileDecoder` was contributed by @hjanetzek in #57 working with Mapzen MVT vector tiles.

Don't know what MVT data that tool produces or if the decoder could need updates.

**Comment by andreynovikov** [comment]
Have you changed anything in java-vector-tile? It does not contain feature type with value 6:
https://github.com/ElectronicChartCentre/java-vector-tile/blob/master/src/main/resources/vector_tile.proto#L31
So this error could not happen.

Another option is that your pbf file is broken. Try to validate it with some tool.

**Comment by sunshine0576** [comment]
@andreynovikov
@devemux86 
 I dependencies "java-vector-tile " in my module. 
VectorTileDecoder.decode(byte[] bytes), No decoding failure occurred。
I guess the possible reason is that geometry can not be empty 。
when geometry==null||geometry.isEmpty()||!geometry.isSimple()||!geometry.isValid(),
PbfDecoder may be Crash。


 compile group: 'no.ecc.vectortile', name: 'java-vector-tile', version: '1.0.9'

@Override
    public boolean decode(Tile tile, ITileDataSink sink, InputStream inputStream) throws IOException {
        mTileDataSink = sink;
        mTileScale = 1 << tile.zoomLevel;
        mTileX = tile.tileX / mTileScale;
        mTileY = tile.tileY / mTileScale;
        mTileScale *= Tile.SIZE;

        VectorTileDecoder vectorTileDecoder = new VectorTileDecoder();
        byte[] bytes = new byte[inputStream.available()];
        inputStream.read(bytes);
        VectorTileDecoder.FeatureIterable features;
        Geometry geometry=null;
        int  count=0;
        System.out.print("Tile:"+tile.tileX+";"+tile.tileY+";"+";"+tile.zoomLevel);
        try {
            features = vectorTileDecoder.decode(bytes);
            for (VectorTileDecoder.Feature feature : features) {
                if(count++>500)
                    break;
                geometry = feature.getGeometry();
                System.out.print("Geometry:"+geometry.toString());
                 if(geometry==null||geometry.isEmpty()
                        ||!geometry.isSimple()||!geometry.isValid()
                        ||geometry.getCoordinates().length>500)
                    continue;
                MapElement mapElement= processFeature(feature);
                if(mapElement!=null){
                    sink.process(mapElement);
                }
            }
        }catch (Exception e){
            System.out.print(e.getMessage());
            return false;
        }
        return true;
    }

**Comment by devemux86** [comment]
Can try [vtm-mvt](https://github.com/mapsforge/vtm/tree/master/vtm-mvt) module with new MVT decoder and report if see any issues.
It is already tested with popular tile providers like Mapzen, Nextzen, OpenMapTiles and works fine.
