### ISSUE TITLE
Web app not working

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#449]
Trying to run is as described https://github.com/mapsforge/vtm/blob/master/docs/web.md produces no errors but browser shows black screen. It works (as url changes on mouse interaction) but nothing is displayed.

**Comment by devemux86** [comment]
It works, need to zoom and wait the (slow) VTM server to respond:

![vtm-web-app](https://user-images.githubusercontent.com/3484020/33220109-8de983c4-d14e-11e7-986e-55f25c40f382.png)

**Comment by andreynovikov** [comment]
Confirm, fresh clone works. So it's something on my side.
