### ISSUE TITLE
OSciMap not shown

### ISSUE THREAD

**Issue by raya-studio** [mapsforge/vtm#454]
Since Monday, when I'm trying the vtm-android-example, the base map is no longer working (only blank with white color).

Thanks in advance, Cheers . . . .

**Comment by devemux86** [comment]
Probably mean the OSciMap vector tiles, their server often does not respond quickly.

In any case I enabled the use of OkHttp engine in all samples for better performance.

**Comment by raya-studio** [comment]
thanks
