### ISSUE TITLE
LwHttp incorrect HTTP headers

### ISSUE THREAD

**Issue by ale5000-git** [mapsforge/vtm#460]
@devemux86

Hi,
all HTTP header lines must be terminated by a carriage return (\r) and a line feed (\n).

You are using only line feed [here](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/tiling/source/LwHttp.java#L98-L112); could you please fix it?

Ref: [microG #455](https://github.com/microg/android_packages_apps_GmsCore/issues/455)

**Comment by devemux86** [comment]
Thanks for the report!

Indeed after tests it fixes `LwHttp` issues.
@ale5000-git do you want to post a pull request with the change?

**Comment by ale5000-git** [comment]
Done: #461
