### ISSUE TITLE
What makes it technologically difficult to tilt more than 65 degrees?

### ISSUE THREAD

**Issue by schedul-xor** [mapsforge/vtm#472]
Current implementation has 65 degrees limit for tilting range. I'll be good if the tilting limit can be extended to 90 degrees or more, for example integrating with AR cameras.

I rewrote the constant limit to 89 degrees and made a try. I found out that tilting more than 79 degrees will make the far tiles vanish. Tiles near the camera may be shown, but they're not in the view.

Some additional tricks, for example adding fog depths may be needed.

**Comment by devemux86** [comment]
`65°` is just a sane default for map tilt range.
Can use `map.viewport()` setters to change such limits.

About working at max values, needs debugging. :slightly_smiling_face:

**Comment by devemux86** [comment]
Situation is now very much improved via #522 even up to ~80°.

**Comment by Gustl22** [comment]
Note: see #537, #529 as overlays have a limited visible range.

**Comment by Gustl22** [comment]
I now figured out, why map disappears from view, when tilting beyond ~80 degrees.
Obviously world has a horizon. If this horizon falls into the screen, the screen corners couldn't be converted correctly on the map.
So [here's the fix](https://github.com/Gustl22/vtm/tree/tilt_472), which also limits map extends to the maximum reasonable distance (far plane). That also is advantageous to only load / render the viewable tiles.

**Comment by devemux86** [comment]
Interesting, you can post it via PR?

**Comment by Gustl22** [comment]
Sure, see #718.

**Comment by devemux86** [comment]
Implemented via #718.
