### ISSUE TITLE
VTM desktop dll cannot be loaded

### ISSUE THREAD

**Issue by wolfgang-ch** [mapsforge/vtm#473]
When I test the newest vtm with my eclipse rcp app https://github.com/wolfgang-ch/vtm-with-rcp then I get an exception.

I found the problem in the file /vtm-desktop/build.gradle

When I use the newest version fef0557 2018-01-05 ...

```
dependencies {
    api project(':vtm-gdx')
    api "com.badlogicgames.gdx:gdx-backend-lwjgl:$gdxVersion"
    api 'com.metsci.ext.com.kitfox.svg:svg-salamander:0.1.19'
}
```

...then I get this exception

```
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'vtm-jni64.dll' for target: Windows 10, 64-bit
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:125)
	at vtm.rcp.app.GdxMapApp.init(GdxMapApp.java:80)
	at vtm.rcp.app.GdxMapApp.run(GdxMapApp.java:222)
	at vtm.rcp.app.View.createUI_Map(View.java:85)
	at vtm.rcp.app.View.createPartControl(View.java:66)
```

When I adapt to the previous version cbdeb58 2017-10-27 ...

```
dependencies {
    api project(':vtm-gdx')
    file('natives').eachDir() { dir ->
        api files(dir.path)
    }
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl:$gdxVersion"
    implementation 'com.metsci.ext.com.kitfox.svg:svg-salamander:0.1.19'
    implementation "org.slf4j:slf4j-api:$slf4jVersion"
}
```

...with this code, ...

```
dependencies {
    api project(':vtm-gdx')
    file('natives').eachDir() { dir ->
        api files(dir.path)
    }
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl:$gdxVersion"
    api 'com.metsci.ext.com.kitfox.svg:svg-salamander:0.1.19'
}
```

...then it is working. There maybe a better solution to solve this problem but I'm not a gradle expert.

This file https://github.com/wolfgang-ch/vtm-with-rcp/blob/master/VTM_RCP_Externals/build.gradle is the (highly complicated) gradle script which builds the rcp app with all the eclipse plugin stuff.

**Comment by devemux86** [comment]
Carrying implicitly the native dependencies for all platforms, without user option, seems not wise.
e.g. force Linux natives in a Windows application. Now the natives are allowed to be selected explicitly by user (as happens on Android).

When using the [integration guide](https://github.com/mapsforge/vtm/blob/master/docs/Integration.md) to declare the natives per platform, does it work?

**Comment by devemux86** [comment]
Or see [vtm-playground](https://github.com/mapsforge/vtm/blob/master/vtm-playground/build.gradle) gradle natives declaration.

**Comment by wolfgang-ch** [comment]
> Carrying implicitly the native dependencies for all platforms, without user option, seems not wise.
this makes sence, I'll split it up in eclipse plugin fragments for each platform

**Comment by devemux86** [comment]
Closing, please inform if need there are issues.

**Comment by wolfgang-ch** [comment]
I splitted the vtm natives into plugin fragments and it works but I need to improve my gradle skills to do this with gradle, currently it's done manually.
