### ISSUE TITLE
S3DB rendering

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#480]
Seems some wrong(?) rendering of `S3DBLayer` at some cases. (related to #475)

Example is [Parthenon](https://en.wikipedia.org/wiki/Parthenon), see Mapsforge vs OSciMap difference, with reverse triangles at roof.

Mapsforge:
![mapsforge](https://user-images.githubusercontent.com/3484020/34823616-cde1fdb2-f6d3-11e7-9916-8b6c82c71765.png)

OSciMap:
![oscim](https://user-images.githubusercontent.com/3484020/34823620-d35fd476-f6d3-11e7-9ae2-a8780ccb90c4.png)

**Comment by devemux86** [comment]
cc @Gustl22

**Comment by Gustl22** [comment]
In this case this isn't a fault of S3DB layer (don't know if it can appear elsewhere).
As I mentioned in #475 the OSM-tag `roof:slope:direction` isn't supported, cause this isn't an official tag. Instead the [`roof:direction`](https://wiki.openstreetmap.org/wiki/Key:roof:direction) tag should be used as described in [S3DB](https://wiki.openstreetmap.org/wiki/Simple_3D_buildings) wiki. 

In OSM forum is already a [thread](https://forum.openstreetmap.org/viewtopic.php?id=31481).
I already [posted](https://lists.openstreetmap.org/pipermail/tagging/2018-January/034584.html) on tagging mailing list and got some positive response. In near future all skillion roofs should behave as it should be.

Adding `roof:slope:direction` is the wrong approach in my eyes. Or add an implementation to accept `equivalent-keys` as it is for `equivalent-values` in [tag-mapping](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-writer/src/main/config/tag-mapping.xml). But as I said, there shouldn't be such _equivalents_ for keys.

**Comment by devemux86** [comment]
Thanks for the clarification!
So the issue starts with the map-writer which doesn't write that tag. Then reader of course doesn't know it.
But since it's quite in use by the community, we can process that too, in order to avoid such "wrong" renders.

**Comment by Gustl22** [comment]
The [issue](https://lists.openstreetmap.org/pipermail/tagging/2018-February/035191.html) I announced (impure tag `roof:slope:direction`), was now fixed by marc_marc in OSM-Data. Here the [Wiki](https://wiki.openstreetmap.org/wiki/Automated_edits/marc_marc). So no need to implement it.

Further I fixed some issue with standing trianglar shapes in #506.

**Comment by devemux86** [comment]
Indeed, very nice result!

![parthenon](https://user-images.githubusercontent.com/3484020/36423998-92fd01d8-164a-11e8-81fe-68c815f74790.png)
