### ISSUE TITLE
Internal render theme styles order

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#490]
The styles in internal render themes should be ordered according to their inheritance via the `use` attribute.
The current order makes the map render the elements in **no** correct zooms, skipping them.
(related #488)

**Comment by devemux86** [comment]
cc @Gustl22

**Comment by devemux86** [comment]
e.g. for woods to render properly the order should be:
```xml
<style-area id="tex1" src="assets:textures/rough.png" />
<style-area fade="11" fill="#9ac56e" id="park" use="tex1" />
<style-area blend="11" blend-fill="#83aa5b" fade="8" fill="#b3d095" id="wood" use="park" />
```

**Comment by Gustl22** [comment]
Ah ok, didn't know that :) See what I can do.
