### ISSUE TITLE
ReverseGeocoding with mvt tile

### ISSUE THREAD

**Issue by Bezzu** [mapsforge/vtm#491]
Hi,
I would like to develop reverse geocoding with mvt tile. I think to store decoded geometry of a tile in a structured data like a TileManager in the layer class (extending the VectorTileLayer) and picks these data when a click happens. Is it a good idea? Is there a better solution?
Thank you 
Bezzu

**Comment by boldtrn** [comment]
> Is it a good idea?

I don't think so, but please prove me wrong :). It's an interesting idea. I don't think that mvt (from any of the major vector tile providers) will provide you the necessary data to do this, for example have a look at [OMT's inspect tool](https://openmaptiles.org/inspect/#0.72/-0/0) to see what data is available. You would probably need address data for every element or geometries surrounding every element within a certain address range.

> Is there a better solution?

Use a geocoding service like [this](https://graphhopper.com/api/1/docs/geocoding/). You could probably also setup your own MVT server and add the required information to the tiles, but this definitely not easy.

**Comment by devemux86** [comment]
Vector map formats are usually not searchable like spatial databases, which would help greatly in reverse geocoding.
They're designed for efficient storage of geographical information, fast tile-based access and filtering of map objects by zoom level.

Note:
I have implemented reverse geocoding in offline [Mapsforge map file format](https://github.com/mapsforge/mapsforge/blob/master/docs/Specification-Binary-Map-File.md).
You can check it in [ReverseGeocodeActivity](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/ReverseGeocodeActivity.java) at `vtm-android-example` samples.
It can search POIs in a radius or ways containing a point, by retrieving the inspected tile map elements and filter them accordingly. It's not the most optimized solution, just something that "works" with map format features.
