### ISSUE TITLE
Render themes: symbols on lines

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#495]
Allow placing (repeated) symbols on lines, enriching `symbol` rule.

Note: `lineSymbol` rule in #124 can do it with the stipples mechanism via generated textures.

Here we try a another implementation using  the original symbols, when enhanced can be more useful.

**Comment by devemux86** [comment]
Mapsforge has already an implementation we can use.
e.g. testing this rule on oneways produce interesting results!
```xml
<m k="oneway" v="yes|true" zoom-min="16">
    <symbol repeat="true" repeat-gap="50" repeat-start="10" src="assets:symbols/transport/bus_stop.svg" />
</m>
```
![symbol_lines](https://user-images.githubusercontent.com/3484020/35568690-7805d3ba-05d2-11e8-999c-03388a87a77e.png)

**Comment by boldtrn** [comment]
Nice improvement! Would this make road signs easier to implement as well?

**Comment by devemux86** [comment]
> Would this make road signs easier to implement as well?

Precisely, now the infrastructure is ready to render billboard symbols, like implement highway shields in #496!

**Comment by andreynovikov** [comment]
How will it look on lower zooms? (When these four lines will almost collapse into one?)
How will it look in cities? (When roads are often split into many tiny peaces?)

I'm asking it because I have made my own implementation and didn't PR it yet because of these and many other issues. Some of them I have fixed, some not.

**Comment by devemux86** [comment]
Like all other symbol types in render themes, with priorities, overlaps, etc.
It doesn't do anything different, just integrated Mapsforge algorithm to fill the lines.
