### ISSUE TITLE
Render themes: highway shields

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#496]
Provide in themes [highway shields](https://en.wikipedia.org/wiki/Highway_shield) feature, probably via a special rule.

**Comment by andreynovikov** [comment]
I have implemented it via gen:/ prefix in symbol source:

https://github.com/andreynovikov/vtm/blob/dbeca8cbb461b41b88e2d213e9fc72bca6b97611/vtm/src/org/oscim/theme/XmlThemeBuilder.java#L1126

https://github.com/andreynovikov/trekarta/blob/181e9ac59882cf8d2c6cfe9c34ea5b7088640c47/app/src/main/java/mobi/maptrek/maps/maptrek/LabelTileLoaderHook.java#L137

**Comment by devemux86** [comment]
Real time generated bitmaps, like current line symbols and dash arrays?
If it's working, then can post a PR to check it!

**Comment by devemux86** [comment]
Can discuss in [forum](https://groups.google.com/group/mapsforge-dev) and if there is interest from community to contribute.

**Comment by devemux86** [comment]
Simple implementation in #737.
