### ISSUE TITLE
Labels / symbols overzoom

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#504]
Implement overzoom for `LabelLayer`, i.e. render labels / symbols up to a zoom (e.g. 17) and keep them in larger zooms.

The label layer is connected via `TileLoaderThemeHook` on vector tile layer's extraction zoom levels. So if extend them, then labels / symbols are produced again for each larger extraction level (which could be avoided).

**Comment by Gustl22** [comment]
Unfortunately every label is [rendered again](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/layers/tile/vector/labeling/LabelPlacement.java#L307) with each little movement...

This should be reduced: only render when new tiles are available.

Don't know if avoid rendering on higher zooms will be noticeable then... seems more a lag of displaying. But I didn't studied it very well. My current [prototype](https://github.com/Gustl22/vtm/blob/issue_503/vtm/src/org/oscim/layers/tile/vector/labeling/LabelLayer.java) will avoid rendering, when it's over a specific zoom limit. But I didn't note a difference. (Need to set [`ZOOM_LIMIT`](https://github.com/Gustl22/vtm/blob/issue_503/vtm/src/org/oscim/layers/tile/vector/labeling/LabelLayer.java#L41) to 17 or what you want)...

**Comment by devemux86** [comment]
Suppose label rendering could or should be triggered also with movement, since can have available tiles off screen and want to render them when get on screen.

> Don't know if avoid rendering on higher zooms will be noticeable then...

It's not just about noticeable, it's mostly about if happen or not.
The purpose of the issue is to _avoid recreating_ the labels if zoom > 17, so we have better performance and far better appearance since polygon labels won't be multiplied inside polygon.

**Comment by Gustl22** [comment]
I don't really understand..
I think that every Label is recreated on any movement anyway. So it doesn't matter (for performance) to take source of zoom 17 or overzoomed 20. Or did I interpret something wrong?  Or better, where do you concretly mean to avoid double creation ? :)

**Comment by devemux86** [comment]
> Or better, where do you concretly mean to avoid double creation ? :)

Try `new MapFileTileSource(2, 20)` and zoom enough to see the labels for polygon house numbers.
Then can see many times the _same_ number inside the building polygon, created more and more with each zoom. Current default (2, 17) nicely avoids that.

**Comment by Gustl22** [comment]
Ahh now I get it. I wanted to solve that anyway.. Plz ignore above implementation then :)

**Comment by devemux86** [comment]
I think our Mapsforge polygon label / symbol algorithm works better if want to to take some hints. :slightly_smiling_face:

**Comment by Gustl22** [comment]
[`LabelLayer`](https://github.com/Gustl22/vtm/blob/issue_503/vtm/src/org/oscim/layers/tile/vector/labeling/LabelLayer.java) now works with `ZoomLimiter` and simply uses `17` zoom tiles.
That avoids double creation on higher zoom levels especially for areas. 
Info: The doubles at tile borders of zoom 17 further exist (like in current master) and maybe could be solved with your mentioned algos.

**Comment by devemux86** [comment]
@Gustl22 is there the overzoom feature available for `LabelLayer` too, now that `ZoomLimiter` is integrated?

**Comment by Gustl22** [comment]
I'll do some tests :)

**Comment by devemux86** [comment]
I merged #544 but let's keep the issue open, since need improvements to allow render themes to work in all zoom levels.
