### ISSUE TITLE
Enable / update vtm-web modules

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#51]
Enable / update `vtm-web` modules to make them working with latest VTM / libGDX.

**Comment by schedul-xor** [comment]
Are there any updates for this topic?

**Comment by devemux86** [comment]
None so far, community could help, as did in iOS module. :slightly_smiling_face:

**Comment by schedul-xor** [comment]
#240

**Comment by devemux86** [comment]
`vtm-web` and `vtm-web-app` modules were enabled / updated via PR #240 by @schedul-xor.

Remaining tasks could be:
- Update `vtm-web-js` module
- Implement graphics API (see TODO)
- SVG support
- Mapsforge map files support

**Comment by devemux86** [comment]
I created a new [topic](https://groups.google.com/forum/#!topic/mapsforge-dev/Sc-UrrUtJvs) in our forum mentioning the update of `vtm-web` modules.

@schedul-xor maybe you can have a look, we already have feedback with some problems. :slightly_smiling_face:

**Comment by devemux86** [comment]
I added in `vtm-web-app` the old default theme using texture atlas with png icons.

![vtm-web](https://cloud.githubusercontent.com/assets/3484020/22660470/54ed10ce-ecaa-11e6-82df-8cfcc31ac81e.png)

**Comment by devemux86** [comment]
Closing here as `vtm-web` is working again.

New features can open separate issues (see my above [comment](https://github.com/mapsforge/vtm/issues/51#issuecomment-261998057)).
