### ISSUE TITLE
PathLayers Style.builder().cap(...) no difference

### ISSUE THREAD

**Issue by luis901101** [mapsforge/vtm#511]
I don't see any difference between Style.builder().cap(Paint.Cap.ROUND) and Style.builder().cap(Paint.Cap.SQUARE); I expected Round and Square respectively shapes at the beginning and at the end of the PathLayer but instead is always Square...

**Comment by devemux86** [comment]
Closing to be handled in older #107 where the history of changes exists.

**Comment by devemux86** [comment]
Thanks for the report!

**Comment by devemux86** [comment]
Should be fixed in #758.
