### ISSUE TITLE
Labels wrapping in themes

### ISSUE THREAD

**Issue by luis901101** [mapsforge/vtm#512]
It would be great if I could specify in a custom VTM rendertheme style some properties as ems length, lines or maxLines (similarly to a xml TextView definition) for labels, in order to avoid long text in the map, it happens that some POI's has a very long name (8 to 12 words) and this makes the labels from different POI's overlaps making the text unreadable.

**Comment by devemux86** [comment]
There is already #144.

**Comment by luis901101** [comment]
My bad... I didn't read well your comment in my post from Google Groups
