### ISSUE TITLE
Mapsforge: decode geometry of a way

### ISSUE THREAD

**Issue by Bezzu** [mapsforge/vtm#517]
Hi,
I have an error to decode the right geometry (Line or Poly) of some ways. In the class MapDatabase of the vtm project, there is the function decodeWayNodes that collects the geometry and the points of a way. When it collects the last point coordinates of a way, it detects the geometry type. The LINE geomtry is assigned if the following condition is true:

``
boolean line = isLine || (lon != firstLon && lat != firstLat);
``

This condition is not right, because if the last point and the first point have the same longitude or latitude (the last point and the first point arent' the same) the condition results false instead of true.
I resolve this problem replacing the condition with the following one:

``
boolean line = isLine || (lon != firstLon || lat != firstLat);
``

Is my solution right?
Thanks in advanced

Bezzu

**Comment by devemux86** [comment]
Hmm that seems right.
Do you want to post a pull request with the change?

**Comment by Bezzu** [comment]
For me it's the same, proceed as you are more comfortable.

**Comment by devemux86** [comment]
@Bezzu thanks for the report!
