### ISSUE TITLE
Blank tiles with large window and tilt

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#520]
As mentioned in [forum](https://groups.google.com/forum/#!topic/mapsforge-dev/tKzqrE6BWyE) with large window and tilt can have blank tiles in map.

![load](https://user-images.githubusercontent.com/3484020/38016187-ee1213e0-3276-11e8-8249-e0446760b917.png)

**Comment by Gustl22** [comment]
I found out, where the bug crawls:
In `TileManager` the array length of `newTiles` is set to a [fixed value](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/layers/tile/TileManager.java#L220). If resizing the window the array length isn't updated. But more tilt and size need more tiles.
There is already a [method](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/renderer/MapRenderer.java#L166) in `MapRenderer`. I would suggest an interface like `SurfaceListener`. I don't know, what is the best way to connect them?

**Comment by devemux86** [comment]
On mobile where most run VTM the map view size is often unchanged, that's why the issue is not so obvious.
A quick "fix" could be to use instead the screen size to create a `TileSet` large enough to hold all tiles, but how get it globally for all platforms?
That way can avoid messing with already active structures once map is initialized, which each subsequent view resize.

**Comment by Gustl22** [comment]
I'm note quite sure if all objects in an array are allocated, but if it doesn't take too much space, this would be a good choice!

**Comment by devemux86** [comment]
If go that way:
- Android provides screen details via `WindowManager.getDefaultDisplay()`
We use it already in Mapsforge Android cache, see [AndroidUtil.getMinimumCacheSize](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-android/src/main/java/org/mapsforge/map/android/util/AndroidUtil.java#L352)
- On other platforms libGDX has it via `Gdx.graphics.getDisplayMode()`

So can introduce two new `Map` interface methods `getScreenWidth` and `getScreenHeight` with relevant platform implementations.
And could need to increase the calculated tiles number `TileManager.init`, to take account also any possible tilt.

> if it doesn't take too much space

It's more space vs change an active tile set (array) - with all things that could follow.
Probably should be ok, since no much increase is expected and is relevant mostly on Desktop where memory is more generous.

BTW @Gustl22 nice find!

**Comment by Gustl22** [comment]
Ok I try to implement your thougts, if it's ok.
Or if its faster and more comfortable, you can fix yourself.

**Comment by devemux86** [comment]
Sure, you can post a pull request with the changes! :slightly_smiling_face:

**Comment by devemux86** [comment]
Fixed via #522.
