### ISSUE TITLE
Add Info Window

### ISSUE THREAD

**Issue by carlosfferreira** [mapsforge/vtm#535]
Hi guys,

I am having a lot of trouble adding an info window in the "onItemSingleTapUp" event. Is there any open source project that uses vtm that does it? I searched for it but didn't find it. Can anyone point me in the right direction regarding this?

Thanks!

**Comment by devemux86** [comment]
Can check [vtm-app](https://github.com/mapsforge/vtm/tree/master/vtm-app) for an implementation.
Alternatively can use a regular `View`, fill it with content, convert it to `Bitmap` and use it as marker overlay.

For questions please use the [forum](https://groups.google.com/group/mapsforge-dev).
