### ISSUE TITLE
Scale factor for short vertices calculation

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#537]
Can provide some automatic `MapRenderer.COORD_SCALE` in high resolution screens, e.g. in `MapView` initialization, like do currently with `Tile.SIZE`.
Preferably that should be optional via `Parameters`, so that users can use their own in the apps.

Related to #343.

**Comment by devemux86** [comment]
Could use device dpi as guide and set `MapRenderer.COORD_SCALE` after any `CanvasAdapter.dpi` is set.
Probably keep current "8" scale as default and use "4" for high resolution / dpi screens.

**Comment by devemux86** [comment]
Default `COORD_SCALE = 8` seems working on Desktop and Browser.
Full screen tests on 4K or 5K screens would be interesting to check. :slightly_smiling_face: 

On Android the scale `8` seems ok until 420dpi wherever was tested so far.
Above that dpi the high resolution devices require smaller scale and `4` is a sane default as next step.

**Comment by Longri** [comment]
I have only Full HD Devices!

**Comment by devemux86** [comment]
In #343 you mentioned a [Note 4](https://www.gsmarena.com/samsung_galaxy_note_4-6434.php) 1440x2560 px (~518ppi), is it available?
Or else Android emulator at 560dpi clearly shows the improvement with scale 4.

**Comment by Longri** [comment]
You are right! I will check again. But with COORD_SCALE = 1 is all fine. On Note 4!

**Comment by Gustl22** [comment]
I'll test with 4k on Monday.

**Comment by devemux86** [comment]
@Gustl22 mean on Android or Desktop?

**Comment by Longri** [comment]
It looks good on Galaxy Note4 

Also on iOS (as dependency on my own App! iOS-example can't run on AndroidStudio)

**Comment by Longri** [comment]
But I have a scaling problem with my app!
After upgrade my app to the last vtm-snapshot, something happened with the scaling of the map elements.

The scale bar is the right size, but all map elements are too small. (On Galaxy Note4)

Which properties must/can I set?
![1](https://user-images.githubusercontent.com/2542295/39699856-4a9238c2-51fb-11e8-98e8-cc6bbb939600.png)


At the moment I set

```
            float scaleFactor = CB.getScaledFloat(Settings.MapViewDPIFaktor.getValue());
            CanvasAdapter.dpi = CanvasAdapter.DEFAULT_DPI * scaleFactor;
```

**Comment by Longri** [comment]
Debug Breakpoit : CanvasAdapter.dpi = 499.99872

**Comment by devemux86** [comment]
Don't remember changing something related to map scaling lately. :slightly_smiling_face: 

But no need to set `CanvasAdapter.dpi`, it's set automatically on initialization.
As well as the `Tile.SIZE` (see [here](https://github.com/mapsforge/vtm/blob/master/vtm-android/src/org/oscim/android/MapView.java#L93-L95)), unless want to set it explicitly.

**Comment by Gustl22** [comment]
We have to find a workaround to declare `COORD_SCALE` as `final`! There're some (final) constants which are initialized with first `COORD_SCALE = 8.0f` and aren't updated.
See `AbstractVectorLayer.MAX_CLIP`, `LineBucket` -> `Renderer.COORD_SCALE_BY_DIR_SCALE`, `S3DBLayer.TILE_SCALE`, (regular) `PathLayer.MAX_CLIP`.

Or find a way to handle them dynamically. 

_I only mention `S3DBLayer`. Not sure, if I made a fault there._

But `MAX_CLIP` should be updated to profit from the larger clip range.

I tested on 4k, but I only have a PPI of 157. So the clip is not enlarged and wouldn't be updated cause of missing updated values. This especially affects paths (and textures) with tilt up to 80 degree. So paths are cut there with regular PathLayer.

![bildschirmfoto von 2018-05-07 20-40-47](https://user-images.githubusercontent.com/18537755/39718583-09d46314-5237-11e8-89a3-6acfe0530b04.png)

Only as question: is there a reason why low dpi devices cannot use 4 as `COORD_SCALE` ?

**Comment by devemux86** [comment]
`MapRenderer.COORD_SCALE` is a public static variable, could also set it externally before any library initialization, like doing with various `Parameters`.
Just that way the work is transferred to application from the library.
Wouldn't want to complicate all library structure just for that, need to think more the implementation.

> is there a reason why low dpi devices cannot use 4 as COORD_SCALE?

No particular, just usually prefer to not change defaults that are already well / long tested.

**Comment by Longri** [comment]
First: 
The scaling problem was my mistake. I have preload a Theme bevore CanvasAdapter.dpi was calculated. SORRY!

Second:
I use COORDSCALE=1, every time, every  Device!
So don't set FINAL (or set Final to 1)

**Comment by Gustl22** [comment]
I meant `final` in terms of: once set (even if it's set by user) and never should be changed (in app) afterwards. But that's not possible for static vars, I think. So need to think more dynamically for the dependent constants :D

**Comment by devemux86** [comment]
If developer of an app "knows" and changes an "advanced" parameter, why will change it again and possibly break it? It's not logical and we're not here to cover such "strange" workflows.

Just improving things without complicate the library more.
When have more time, all these need more testing..

**Comment by devemux86** [comment]
@Gustl22 after debugging the variable values while the samples are running, I cannot find any issues with current implementation.

`MapRenderer.COORD_SCALE` is initialized properly before any of all those classes, so they use the new calculated scale (if any).
It's the exact same process like `Tile.SIZE`, which works nicely all this time.

Also those variables can be overridden via `Parameters` and user sets its own before library initialization.

**Comment by devemux86** [comment]
Calculation was added on Android: regular + libGDX implementations.
iOS could use probably common dpi check and scale factor.

Desktop or Browser may need another check, due to different dpi / resolution.

**Comment by Gustl22** [comment]
Sorry my bad! I thought it was added to all environments. I changed the values in `calculateCoordScale()` and wondered why they weren't updated in the constants.... on Desktop.

Can we add them this to Desktop, too, with lower dpi values?

**Comment by devemux86** [comment]
Sure, I don't a 4K screen (or similar) available to test, so do we need to use also dpi there and which threshold?

**Comment by Gustl22** [comment]
Ok I made various tests, always with `Viewport.MAX_TILT = 80` and regular PathLayer.

Desktop 1920 × 1080, unknown ppi/dpi , `COORD_SCALE = 8`: works fine (minimal clipped)

Desktop 3840 × 2160, 157 ppi, 96 dpi (software), `COORD_SCALE = 8`: clipped (see above)

Android (Smartphone) 1920 × 1080, 432 ppi, 480 dpi,  `COORD_SCALE = 4`: works fine

Android (Tablet 4:3) 2048 × 1536, 264 ppi, 320 dpi,  **`COORD_SCALE = 8`**: clipped
![screenshot_20180508-160720](https://user-images.githubusercontent.com/18537755/39763715-311447d0-52de-11e8-8783-b0e60a6292fa.png)

Desktop does not provide (the right) software density information, cause screen density couldn't be read by system (so always set to 96). So we have to fall back to screen resolution.

My Android Tablet clips the paths: although it has a very high resolution, the density isn't reached.

So I would propose to make all dependent of screen resolution (or a mixture of both) as this defines the range for later OpenGL calculations. As limit we can use dimension equals and above 1920 × 1080 pixels for `COORD_SCALE = 4.0f`.

**Comment by devemux86** [comment]
Note that tilt 80 is not default and we're talking here about default values.
Or else each user can change tilt limits and scale value as wish according to specific needs.

We just need sane defaults testing with inside default settings.

**Comment by devemux86** [comment]
BTW I tested on an [Nexus 9](https://www.gsmarena.com/htc_nexus_9-5823.php) with above specs and didn't see something strange with default settings.

**Comment by Gustl22** [comment]
That sounds good. 

For current 65 degree I can't see any issues (with all devices).

**Comment by Gustl22** [comment]
Works nice! I noticed some clipping on my Phone (1080 width) with higher tilt, but I think we cannot cover all cases and certainly it's customizable, so it's fine! Thanks :)
