### ISSUE TITLE
iOS documentation

### ISSUE THREAD

**Issue by jerzykiler** [mapsforge/vtm#538]
The documentation for iOS part including the `vtm-ios-example` project is not enough to use `vtm` on iOS.

I have spent last couple of days trying to include a map view as a (in a) separate UIViewController, to be able to show it from another UIViewController in my iOS application, but couldn't figure out how to do it.

Is it possible right now ?

What I've tried:

- I've launched the `vtm-ios-example` project using RoboVM Android Studio plugin from here:
http://robovm.mobidevelop.com/downloads/snapshots/idea/

    It was working fine but there are two things worth noting here:

    - The RoboVM plugin could launch the project only after I manually edited `vtm-ios-example.iml` removing: 
        ```xml
        <component name="FacetManager">
            <facet type="android-gradle" name="Android-Gradle">
              <configuration>
                <option name="GRADLE_PROJECT_PATH" value=":vtm-ios-example" />
              </configuration>
            </facet>
            <facet type="java-gradle" name="Java-Gradle">
              <configuration>
                <option name="BUILD_FOLDER_PATH" value="$MODULE_DIR$/build" />
                <option name="BUILDABLE" value="true" />
              </configuration>
            </facet>
        </component>
        ```
    - The SVGgh.framework has to contain x86 architectures for the example project to work fully on 
simulator so with the commit `update iOS SVGh (exclude x86 native's)` from 13.01.2018 
(`pull request #483`) it doesn't work.

- Created an xcode framework using `MobiDevelop's RoboVM`, included it in my iOS app and tried to launch it from my UIViewController like in this post:
https://github.com/libgdx/libgdx/pull/3816.

    I've successfully `initialised JVM` and 
    called `com.badlogic.gdx.backends.iosrobovm.IOSApplication.didFinishLaunching` 
    in my `UIViewController.viewDidLoad` but when the function `UIViewController.viewDidLoad` ended, somewhere else some memory? exception occurred and I couldn't track it down.
    
    BTW: to create a framework using `gradlew robovmInstall` I had to change 
    `api/implementation` command to `compile` in every gradle file. With `api/implementation` it didn't output jar files to the `framework` file at all.

- I tried to use `Mutli-OS Engine`. It also required `compile` instead of `api/implementation`.
MOE can generate an xcode project so probably (I'm relatively new to iOS) it should be easy to create `xcode workspace` containing this `vtm-ios map project` and user's application and link them without creating any frameworks or anything like that. Libgdx has a special view 
reserved for `MOE` named `IOSGLKView` which makes it possible to show a libgdx game as a
view inside a UIViewController and even make adjustments in a storyboard. 
I used an example from here:
https://discuss.multi-os-engine.org/t/launch-a-libgdx-game-using-moe-from-ios-storyboard/1005
As it turned out vtm-ios requires some UI stuff from robovm backend and I got some weird gradle 
errors like `(Duplicate zip entry [moe-core.jar:SQLite/Callback.class])` so I stopped trying. 

If anyone succeeded in embedding the map view in a separate UIViewController it would be really helpful If we could read a small tutorial in the ios docs. 

Thank you :)

**Comment by devemux86** [comment]
cc @Longri

Regarding Gradle `compile` vs `api` / `implementation` do you use a Gradle release (now `4.4`) as in repository?

**Comment by jerzykiler** [comment]
Yes I use the newest gradle 4.4
