### ISSUE TITLE
Reuse theme issue

### ISSUE THREAD

**Issue by NamtarR** [mapsforge/vtm#545]
Hello, I am using VTM in my project and reusing theme causes some unexpected behavior. Mapsforge theme parsing takes a huge amount of time on some devices so I decided to inject `IRenderTheme` with Dagger and made it `@Singleton`. And to make it load properly I had to make it lazy loaded, so it is parsed only the first time it is used. Hovewer, if it is reused after device rotation or if I go to another screen and then back again, one of the rules become half-ignored.

This is how it is constructed:
```
    @Provides
    @Singleton
    fun provideMapRenderTheme(context: Context): IRenderTheme {
        val renderTheme = AssetsRenderTheme(
                context.assets,
                "",
                "theme.xml",
                null
        )

        return ThemeLoader.load(renderTheme, null)
    }
```

This is the rule:
```
    <rule e="way" k="highway" v="path">
        <line stroke="#779A89" stroke-dasharray="8,6" stroke-linecap="butt" stroke-width="0.5"/>
        <pathText display="always" fill="#555555" font-size="9" font-style="normal" k="name" dy="2"/>
        <rule e="way" k="access" v="private">
            <line stroke="#FFD8E8" stroke-width="0.8"/>
        </rule>
        <rule e="way" k="bridge" v="yes">
            <line stroke="#779A89" stroke-linecap="butt" stroke-width="0.5"/>
        </rule>
    </rule>
```

This is how it renders on first usage:
![image](https://user-images.githubusercontent.com/16237530/40583514-786ca1dc-61ba-11e8-87e4-51f451dcc579.png)

And this is how it renders next times:
![image](https://user-images.githubusercontent.com/16237530/40583519-9e0ef02a-61ba-11e8-8849-ccde9facee75.png)

As I tried to make it work, I have only found that is still respects wtroke-width but not any of other parameters. Removing other sub-rules doesn't help. Somehow it renders everything else properly, this is the only one wrong.

What can I do to resolve this?

**Comment by devemux86** [comment]
The themes are parsed only on first use and the proper work flow is demonstrated in [GettingStarted](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/GettingStarted.java) sample.

So if having the activity to restart at each device orientation change, should follow the procedure and reinitialize the map view without any rendering issues.
Of course this inconvenience can be avoided if not lest the app restart with device rotation, like appears in vtm-android-example [manifest](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/AndroidManifest.xml#L42-L44).

Note that VTM uses XML push parsing (SAX) for themes, which can be slow and with less performance for large map styles, waiting for the whole theme to build up.
There is #431 to implement a XML pull parser, like we have in Mapsforge.

For questions please use the [forum](https://groups.google.com/group/mapsforge-dev).
