### ISSUE TITLE
Change current location image.

### ISSUE THREAD

**Issue by jocieldo** [mapsforge/vtm#546]
Hi, I want to put a new image vector on my current position. How can I do that? A create a new marker? 
Thanks

**Comment by devemux86** [comment]
VTM location renderer uses OpenGL shaders for the location marker.

So can either create your own OpenGL shaders to customize them.
Or make a different implementation which users a regular bitmap as marker.

For questions please use the [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by devemux86** [comment]
I created #547 for supporting bitmap location renderers.
