### ISSUE TITLE
Location texture renderer

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#547]
Implement a new **_separate_** location renderer using a regular bitmap as marker.

That way users can more easily customize location marker in their applications.

**Comment by Longri** [comment]
Maybe I can PR my used LocatioLayer.
It's ready for use with BMP for location and use the original circle layer as accuracy indicator

**Comment by devemux86** [comment]
Sure!

> use the original circle layer as accuracy indicator

Do you mean a GL circle shader or a regular circle overlay?

**Comment by Longri** [comment]
Modified shader without direction

**Comment by Longri** [comment]
![screenshot_2018-05-29-17-31-37](https://user-images.githubusercontent.com/2542295/40669045-4d3ba6ea-6366-11e8-9c88-497339f85cc0.jpg)

**Comment by Longri** [comment]
Status: in process

I will simplify the layer a little bit and add some properties for the color, which I coded in my shader.

**Comment by devemux86** [comment]
Note that should not have any bitmap resources in the library.
User can set it during layer creation (like in https://github.com/mapsforge/mapsforge/issues/1035).

**Comment by devemux86** [comment]
> Status: in process

No need to hurry, have little time to properly review the other pull requests anyway. :slightly_smiling_face:

**Comment by Longri** [comment]
> Note that should not have any bitmap resources in the library.

Of course. Only on example

**Comment by devemux86** [comment]
Implemented via #548.

**Comment by devemux86** [comment]
Further improvements could be:
- Use simpler SVG read implementation in sample with better scaling
(i.e. `AndroidSvgBitmap` and friends are focused on theme svg resources)
- Location marker should tilt following the map movement
- Shaders could need `mediump` precision because of #207

**Comment by Longri** [comment]
> Location marker should tilt following the map movement

I'll have another look, because in my original implementation, in my app, it worked.

Something must have gone wrong when we make the switch.

**Comment by devemux86** [comment]
> Use simpler SVG read implementation in sample with better scaling
> (i.e. `AndroidSvgBitmap` and friends are focused on theme svg resources)

None of these are necessary, just need to scale the size, I pushed the fix.

**Comment by Longri** [comment]
> Location marker should tilt following the map movement

Okay, I looked in again and I realized that it didn't work for me either. It was just an optical illusion.

Symbols are never tilted.
Although it works with texts/labels.

I think a general property for SymbolItems should be created here with a new issue!?

**Comment by devemux86** [comment]
`SymbolItem` already supports billboard rendering or not, I pushed the fix.

**Comment by Longri** [comment]
Thanks for a broad hint!

But I think is better to use a propertie for that,
so the user can decide.

**Comment by devemux86** [comment]
If have the location symbol as billboard how does it work?
e.g. with location bearing=0° the arrow should point to North, even with map rotation.
Without billboard that works (1st image), with billboard is always upright on screen (2nd image)

![location](https://user-images.githubusercontent.com/3484020/40874355-eed3c8c6-6676-11e8-91a4-ad683b23b2a0.png)
