### ISSUE TITLE
Mapzen GeoJSON vector tiles

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#55]
[GeoJSON](http://geojson.org/) uses the `.json` extension.

GeoJSON is easy to get started with, human-readable, and compatible with many tools.

It is one of the [available tile formats](https://mapzen.com/documentation/vector-tiles/use-service/#available-tile-formats) from Mapzen.

**Comment by devemux86** [comment]
Initial implementation can be found in `vtm-extras`.

**Comment by devemux86** [comment]
Tests can be done on Android with `vtm-android-example` and `MapzenGeojsonMapActivity` or on Desktop with `vtm-playground` and `MapzenGeojsonTest`

**Comment by deviousgeek** [comment]
Interesting, is this a much faster alternative to MVT?

**Comment by devemux86** [comment]
Much faster no, since MVT tiles are binary, while GeoJSON tiles are text though with Gzip responses.
TopoJSON tiles #56 would be even better, we just need a tile decoder.

The need of GeoJSON tiles came because of MVT OOM #341 and it's always nice to have alternatives. :slightly_smiling_face:
