### ISSUE TITLE
Fatal error in SimpleMapTest with Java 10 in Win10

### ISSUE THREAD

**Issue by wolfgang-ch** [mapsforge/vtm#568]
Running [SimpleMapTest.java ](https://github.com/mapsforge/vtm/blob/master/vtm-playground/src/org/oscim/test/SimpleMapTest.java) with Java 10 causes a fatal error

 JRE version: Java(TM) SE Runtime Environment (10.0.2+13) (build 10.0.2+13)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (10.0.2+13, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
 **Problematic frame:
 C  [vtm-jni64.dll+0x19fe]**

[hs_err_pid3932.log](https://github.com/mapsforge/vtm/files/2320541/hs_err_pid3932.log)

**Comment by devemux86** [comment]
Does a previous Java **minor** version works?
Do previous Java major versions work?

Note: that Java has problems on [Linux](https://bugs.launchpad.net/ubuntu/+source/openjdk-lts/+bug/1788250) too.

**Comment by wolfgang-ch** [comment]
with Java 8 it is working

**Comment by wolfgang-ch** [comment]
I have not testet it with another Java 10 minor version
I have not testet it with Java 9

prevsiously I use Java 8

**Comment by wolfgang-ch** [comment]
with Ubuntu 18.04 and Oracle Java 10 it is working

**Comment by devemux86** [comment]
Newer Java seems doing things here, like was in Mapsforge https://github.com/mapsforge/mapsforge/issues/1083 where there were missing modules.

_Some friends tested Cruiser GL (with VTM snapshot) on Win 10 and Java 8 and works fine._

**Comment by devemux86** [comment]
Can discuss in [forum](https://groups.google.com/group/mapsforge-dev) and if there is interest from community to contribute.
