### ISSUE TITLE
unmappale character for encoding Cp1252

### ISSUE THREAD

**Issue by wolfgang-ch** [mapsforge/vtm#571]
When I run the gradle build then this warning occurs: **unmappale character for encoding Cp1252**, the build itself is succesful

https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/utils/ScanBox.java#L119

Gradle log
![scanbox-characters-gradle](https://user-images.githubusercontent.com/1283445/44626941-04d94780-a926-11e8-9cde-4fd0f036d1f6.png)

How it is displayed im my Eclipse IDE
![scanbox-characters](https://user-images.githubusercontent.com/1283445/44626942-04d94780-a926-11e8-9d59-db3b63265ca8.png)

**Comment by devemux86** [comment]
Why not set UTF-8, that is the usual default in sources.

**Comment by wolfgang-ch** [comment]
When setting encoding in Eclipse to UTF-8, it do not look better and I was not successfully setting UTF-8 in gradle at different locations.

As long as the gradle build is successful, I can live with this issue

![utf-8-encoding](https://user-images.githubusercontent.com/1283445/44628439-031c7d80-a940-11e8-9adb-5b6cd538412b.png)

**Comment by devemux86** [comment]
Strange, even a common editor with UTF-8 shows them correctly.

We can improve those comments, introduced in commit https://github.com/mapsforge/vtm/commit/a1c5f4aa5ab2745d16a786a9ecb4f7670a414ad8#diff-bd7d06b9e271918fbf0507fadd3d8097, @Gustl22 ?

**Comment by Gustl22** [comment]
My mistake, I used arrows that aren't supported by all fonts (no unicode). _Consolas_ of Eclipse doesn't interpret it, as _DejaVu Sans Mono_ used by my IDE does.
I'll do a PR with these ones: https://www.w3schools.com/charsets/ref_utf_arrows.asp which should work with all fonts...

**Comment by devemux86** [comment]
> Edit: the arrows aren't that important, only good to see. So if this doesn't work, we can simply remove them...

Seems the most convenient solution, the directions are mentioned anyway.

**Comment by wolfgang-ch** [comment]
_Consolas_ looks the same

![scanbox-utf8-consolas](https://user-images.githubusercontent.com/1283445/44657680-ed6d8d80-a9fd-11e8-8fec-38f560f89819.png)

**Comment by Gustl22** [comment]
Ok kind of strange. It's the best to remove these. Thx @wolfgang-ch .

**Comment by devemux86** [comment]
Fixed in #573.
