### ISSUE TITLE
Add shadow to buildings

### ISSUE THREAD

**Issue by schedul-xor** [mapsforge/vtm#575]
Since buildings are a kind of polygons, it should be possible to add shadows by tracing well known techniques (for example "shadow mapping"). It will be nice to add a directional light using the sun's ray.

TL;DR
----
I've tried shadow mapping implementation, but it's not finished. I think I'm almost there, but I need help.

Not-finished product (**INTENSE FLASHING CAUTION**): https://github.com/schedul-xor/vtm/commit/2c6294b91e499bc902145af8640cf7ee7ee2eaab
(To run the product, (1) rewrite vtm-playground/build.gradle `mainClassName = "org.oscim.test.SimpleMapTest"` (2) `./gradlew :vtm-playground:run`)

![image](https://user-images.githubusercontent.com/589860/44803811-7fda8080-abfa-11e8-9be6-4312b26e909c.png)

My strategy
----
It was to integrate [this](http://www.chinedufn.com/webgl-shadow-mapping-tutorial/) technology. Depth packing functions are (almost) copied from this page.

What I've done:
 * Copy the source of `OffscreenRenderer`, rename it to `ShadowRenderer`.
 * Build an orthogonal projection matrix, because it's a directional light.
 * Build shadow map texture by rendering "building" polygons (actually the depth) to the frame buffer.
 * Read the shadow texture from frame buffer and render the final shadow.

As a result
----
I succeeded to render shadow map, but failed to render the final shadow.

Problems
----
 * Shadow maps are flashing. It should affect to the shadow rendering. Why flashing? Double buffering not working correctly?
 * Buildings are expected to be rendered twice (first when building shadow map, second when rendering directly), but the second rendering failed unless mRenderer.update() was called. I'm not sure why.
 * I've prepared 800x800 plane to check if it works, checked out that it works, but not sure why 800 is enough.
 * The final shadow is not rendered. Where did I mistake?
 * I've been working on this for eight days, but no progress. It's nearly uncontrollable. This feature needs technical support.

**Comment by Gustl22** [comment]
Thanks @schedul-xor: Gettin closer :)

![screenshot from 2018-12-16 17-57-34](https://user-images.githubusercontent.com/18537755/50056422-53705300-015c-11e9-8ea4-2d2623cca5d7.png)

**Comment by Gustl22** [comment]
As said...without modyfing the `ExtrusionRenderer`, wouldn't be possible (at least the setters).

**Comment by schedul-xor** [comment]
`ShadowRenderer` is currently depending on `ExtrusionRenderer`, but is probably expected to stand on it's own feet in the future. Building polygons are currently generated only from extrusion, and is better to leave room for improvement ... for example, to support additional 3d polygon data (using `com.badlogic.gdx.graphics.g3d.model.*`) later. Extending `ExtrusionRenderer`, in my opinion, is not a good idea.

How about adding multiple "Shadowable renderer" to `ShadowRenderer`, and let `ExtrusionRenderer` implement "Shadowable renderer" interfaces?

Can `ExtrusionRenderer` be used only as a rule-based 3d polygon generator? Actually it currently _is_, but it also contains complex building shaders.

**Comment by devemux86** [comment]
After latest merges, what is the state of this feature?

**Comment by devemux86** [comment]
Closed via #668.

**Comment by devemux86** [comment]
Another sample of the nice work and the library's power:

![3d_shadows](https://user-images.githubusercontent.com/3484020/53115039-d4c5d680-354d-11e9-951c-8f4202293704.png)
