### ISSUE TITLE
BoundingBox is immutable

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#58]
Is there any reason for BoundingBox to be immutable? In my app I am dynamically expanding it. Can I pull request this?

**Comment by devemux86** [comment]
Actually there are two box classes.
There is also the mutable [Box](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/core/Box.java) which is used for transformations.

Usually in map libraries, core geographic classes are immutable.
Though that does not forbid them to participate in calculations, e.g. see Mapsforge [BoundingBox](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-core/src/main/java/org/mapsforge/core/model/BoundingBox.java) and its various extension methods.

**Comment by andreynovikov** [comment]
Yes, in my app I manipulate the BoundingBox as it is used for map viewport management.

**Comment by devemux86** [comment]
Why not creating a new `BoundingBox` after a new modification?
Changing internal values of such a core element needs caution, if the class reference is already used in calculations somewhere else.

So do you mean removing the `final`?
And should we make also `GeoPoint` mutable?

**Comment by andreynovikov** [comment]
Yes, I mean removing `final`. I have added the `expand` method to the `BoundingBox`, feed it with hundreds of coordinates and pass it to the map so it covers all these coordinates. Of course I can do it in some other object and then initialize `BoundingBox` but as I said I do not see any practical reason of making it final.

As for GeoPoint I see some reason why it is final. Otherwise if you change it, referencing objects, like markers, will become inconsistent. But this is not good too. When I have to move marker I have to recreate it instead of just modifying it's location. In case of continuous movement it is much overhead.

**Comment by devemux86** [comment]
>When I have to move marker I have to recreate it instead of just modifying it's location. In case of continuous movement it is much overhead.

Thanks for bringing that to my attention again.
I intend to push some improvements to that area too.
