### ISSUE TITLE
vtm-models module

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#580]
Include 3D models in their own separate module.

**Comment by Gustl22** [comment]
More convenient :+1:

**Comment by schedul-xor** [comment]
May I move `vtm-playground`/src/`org.oscim.test.gdx.poi3d.*` to `vtm-models`/src? Currently poi3d is only available on LWJGL3 demo.

**Comment by devemux86** [comment]
`vtm-models` is meant to host 3D models, like `vtm-themes` used for render themes.

Any `vtm-playground` classes can move to other lib module, e.g. `vtm-gdx` (discussed in #570).

**Comment by schedul-xor** [comment]
#600 is a decision to separate `vtm-models` from `vtm-gdx` (named `vtm-gdx-models`), which makes the structure more complex, but on the other side prevents the model data to be included even if it's not needed.

**Comment by devemux86** [comment]
> May I move vtm-playground/src/org.oscim.test.gdx.poi3d.* to vtm-models/src?

Got confused with your statement above. :slightly_smiling_face: 

If they don't bring new dependencies (besides libGDX), can be hosted in `vtm-gdx` for simplicity.
