### ISSUE TITLE
Polygon holes cannot be displayed

### ISSUE THREAD

**Issue by sunshine0576** [mapsforge/vtm#591]
Style style = Style.builder()
                .fillColor(Color.RED)
                .strokeColor(Color.BLACK).build();

        Coordinate[] coord_shell=new Coordinate[]{
                new Coordinate(0,0),
                new Coordinate(10,0),
                new Coordinate(10,10),
                new Coordinate(0,10),
                new Coordinate(0,0)
        };
        Coordinate[] coord_hole1=new Coordinate[]{
                new Coordinate(2,2),
                new Coordinate(8,2),
                new Coordinate(8,8),
                new Coordinate(2,8),
                new Coordinate(2,2)
        };
        GeometryFactory geometryFactory=new GeometryFactory();
        LinearRing shell=geometryFactory.createLinearRing(coord_shell);
        LinearRing hole1=geometryFactory.createLinearRing(coord_hole1);
        Geometry geometry=geometryFactory.createPolygon(shell,new LinearRing[]{hole1});
        vectorLayer.add(new PolygonDrawable(geometry, style));
        vectorLayer.update();

**Comment by sunshine0576** [comment]
![1212](https://user-images.githubusercontent.com/21358135/45679391-25826f00-bb6b-11e8-9383-beb3956d101f.png)

**Comment by devemux86** [comment]
See my answer in https://github.com/opensciencemap/vtm/issues/178.
