### ISSUE TITLE
Fatal Crash on Android Application

### ISSUE THREAD

**Issue by DefaultXYZ** [mapsforge/vtm#599]
Hello!

I'm trying to add OpenMapTiles with UrlTileSource, and MvtTileDecoder. 

Application keeps getting fatal crash on library for OS x86_64 and arm64-v8a:
`A/libc: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8 (TileLoader0)`

What can be reason of this critical exception?

Thank you for support!

**Comment by devemux86** [comment]
Can check [OpenMapTilesMvtActivity](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/OpenMapTilesMvtActivity.java) sample in [vtm-android-example](https://github.com/mapsforge/vtm/tree/master/vtm-android-example) where is demonstrated how can use `OpenMapTilesMvtTileSource` with OpenMapTiles.

**Comment by DefaultXYZ** [comment]
Yes, I have implemented exactly the same class, but with my custom Map URL, which consumes .pbf maps.

**Comment by devemux86** [comment]
If you create custom vector tiles or use custom decoder, you will need to debug the process.

There don't seem any issues with OMT and [mapbox-vector-tile-java](https://github.com/wdtinc/mapbox-vector-tile-java) decoder in `vtm-mvt` module.

For further questions let's continue in [forum](https://groups.google.com/group/mapsforge-dev).
