### ISSUE TITLE
Render themes: SVG resources

### ISSUE THREAD

**Issue by Longri** [mapsforge/vtm#60]
add svg constructor for Bitmap
Implement SVG loading for theme symbol

I will do that with PR in the next days.

Tests with iOS framework are successful

**Comment by devemux86** [comment]
I already have under testing an initial implementation for Android / Desktop with the proper infrastructure. It requires several intermediate steps:

- Allow symbols without texture atlas
- Read resources from file system
- ...

So wait a bit until I push all the commits. :smile:

**Comment by devemux86** [comment]
>Tests with iOS framework are successful

Very good news! :+1:

**Comment by Longri** [comment]
> Allow symbols without texture atlas

thats not god! The Textureatlas has one Texture with all Symbols! If you change this to single Texture you need many performance for swap Textures with render any Symbol! And Texture swaping cost performance!

> So wait a bit until I push all the commits. 

Yes I wait and hope your implementation on Android and Desktop is implementable at iOS

**Comment by devemux86** [comment]
>thats not god! The Textureatlas has one Texture with all Symbols! If you change this to single Texture you need many performance for swap Textures with render any Symbol! And Texture swaping cost performance!

I know but a library should be versatile. If users need to have their symbols in a regular folder collection, library could provide that option.

BTW how do you think SVG symbols should be stored in a render theme?
As files, as SVG atlas, as what?

**Comment by Longri** [comment]
I think the best way is to create the Textureatlas at runtime.
Some Themer like Klaus from Freizeitkarte, use SVG and BMP.

Wen a Theme is loaded, so we created all the symbols into Textureatlas!

Maybe we can Buffer this Textureatlas on Feilesystem for the next load.

**Comment by devemux86** [comment]
Note that now only symbols are read from a texture atlas.
Patterns and textures are still loaded from separate files.

Runtime creation is more complicated (needs a writer too) and I'd leave it as a future step.
For start we need to support properly all known functionality and then will see how to proceed.

**Comment by Longri** [comment]
> Runtime creation is more complicated (needs a writer too) and I'd leave it as a future step.
> For start we need to support properly all known functionality and then will see how to proceed.

no, is not complicated!

`
public static TextureAtlas createTextureAtlasFromImages(FileHandle folder) {

        int pageWidth = 2048;
        int pageHeight = 2048;
        int padding = 2;
        boolean duplicateBorder = false;

        PixmapPacker packer = new PixmapPacker(pageWidth, pageHeight, Pixmap.Format.RGBA8888, padding, duplicateBorder);

        ArrayList<FileHandle> fileHandleArrayList = new ArrayList<FileHandle>();
        getHandles(folder, fileHandleArrayList);

        for (FileHandle fileHandle : fileHandleArrayList) {

            Pixmap pixmap = null;
            String name = null;

            //check for svg or png
            if (fileHandle.extension().equalsIgnoreCase("svg")) {
                try {
                    pixmap =CanvasAdapter.decodeSvg(fileHandle.read(), 1, 100, 100, 100, fileHandle.hashCode()).getPixmap();
                    name = fileHandle.name();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else if (fileHandle.extension().equalsIgnoreCase("png")) {
                pixmap = CanvasAdapter.decodeBitmap(fileHandle.read()).getPixmap();
                name = fileHandle.name();
            }

            if (pixmap != null) packer.pack(name, pixmap);

        }
        TextureAtlas atlas = packer.generateTextureAtlas(Texture.TextureFilter.Linear, Texture.TextureFilter.Linear, false);
        packer.dispose();
        return atlas;
    }

    public static void getHandles(FileHandle begin, ArrayList<FileHandle> handles) {
        FileHandle[] newHandles = begin.list();
        for (FileHandle f : newHandles) {
            if (f.isDirectory()) {
                getHandles(f, handles);
            } else {
                handles.add(f);
            }
        }
    }
`

this code is tested!

**Comment by devemux86** [comment]
Hmm we'd need to include a libGDX dependency on core module for that..

**Comment by Longri** [comment]
Yes, but I think that Libgdx is the better way here.
The Libgdx is constantly developed and a lot of things from VTM basing on the code of Libgdx!

**Comment by devemux86** [comment]
I created #63 for SVG texture atlas, to see what we can provide.

**Comment by devemux86** [comment]
I pushed the needed SVG infrastructure along with the Android and Desktop implementations.

**Comment by devemux86** [comment]
@Longri you can proceed for the iOS in `IosGraphics.decodeSvgBitmapImpl` method.

See the `AndroidGraphics` and `AndroidSvgBitmap` or `AwtGraphics` and `AwtSvgBitmap` classes for help.

**Comment by devemux86** [comment]
@Longri provided the iOS implementation via PR #69.
