### ISSUE TITLE
how to build vtm-themes dependency for android?

### ISSUE THREAD

**Issue by davmol** [mapsforge/vtm#602]
I have created my own xml map style based .map file created with custom tagging-xml. So I got new assets files and a new style xml file. How do I build a dependency in IDEA as an artefact upon that?
I tried it several times in different ways but something is missing... (there is no manifest).

it looks like this in IDEA:
<img width="499" alt="bildschirmfoto 2018-11-23 um 22 10 50" src="https://user-images.githubusercontent.com/37088985/48960455-fcb49680-ef6c-11e8-98ba-d422c42c669b.png">

and like this in android studio:
<img width="257" alt="bildschirmfoto 2018-11-23 um 22 12 22" src="https://user-images.githubusercontent.com/37088985/48960461-05a56800-ef6d-11e8-9c78-987d8bb2a47a.png">

can anybody help me?

**Comment by devemux86** [comment]
`vtm-themes` module is a simple Java library.
Can study its structure and create a new one.

For questions please use the [forum](https://groups.google.com/group/mapsforge-dev).
