### ISSUE TITLE
Buildings translucency on macOS

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#61]
Buildings translucency does not work on macOS.

Having enabled (default) the `BuildingLayer.TRANSLUCENT`, the buildings appear completely transparent.

**Comment by devemux86** [comment]
@longri can you confirm, also on iOS?

**Comment by Longri** [comment]
I can confirm that on MAC!

On iOS the Flag BuildingLayer.TRANSLUCENT are ignored! No changes at Display!

**Comment by devemux86** [comment]
>On iOS the Flag BuildingLayer.TRANSLUCENT are ignored! No changes at Display!

What do you mean, that changing the value the buildings appear the same?
And how do they appear, normal semi-transparent or completely transparent?

**Comment by Longri** [comment]
Yes, the building looks like same with or without the flag!

And no, they have no transparency! No semi-transparent!

**Comment by devemux86** [comment]
So in macOS we have completely transparent buildings and in iOS we have completely solid ones (ignoring the flag too).

Can you open a new issue for buildings translucency on iOS?
It seems we have different case there.

**Comment by Longri** [comment]
Done!

But I can not set the BUG label!

**Comment by Longri** [comment]
I have played with BuildingLayer and if you set the Transcluent Flag to FALSE so on Mac Desktop the buildings are drawn transparency! And pleace don't ask why, I have no idiea.

 ```
public BuildingLayer(Map map, VectorTileLayer tileLayer, int zoomMin, int zoomMax) {

        super(map);

        tileLayer.addHook(this);

        mRenderer = new BuildingRenderer(tileLayer.tileRenderer(),
                zoomMin, zoomMax,
                false, true); <== set to FALSE to try
        if (POST_AA)
            mRenderer = new OffscreenRenderer(Mode.SSAO_FXAA, mRenderer);
    }
```

**Comment by devemux86** [comment]
Yes I have seen, that's how I use it currently on Mac.

I had also made the `BuildingLayer.TRANSLUCENT` public not final, so that users can play with it.

**Comment by devemux86** [comment]
Regarding the flag effect on rendering, see also #181.

**Comment by devemux86** [comment]
Can discuss in [forum](https://groups.google.com/group/mapsforge-dev) and if there is interest from community to contribute.
