### ISSUE TITLE
Null reference used for synchronization (MapScaleBarLayer)

### ISSUE THREAD

**Issue by calvinkehl** [mapsforge/vtm#611]
Sometimes the map crashes and throws following NullPointerException:
```
java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
        at org.oscim.scalebar.MapScaleBarLayer.onMapEvent(MapScaleBarLayer.java:54)
        at org.oscim.map.Map$2.tell(Map.java:153)
        at org.oscim.map.Map$2.tell(Map.java:149)
        at org.oscim.event.EventDispatcher.fire(EventDispatcher.java:66)
        at org.oscim.map.Animator.cancel(Animator.java:366)
        at org.oscim.map.Animator.updateAnimation(Animator.java:330)
        at org.oscim.map.Animator$1.go(Animator.java:347)
        at org.oscim.utils.async.Task.run(Task.java:32)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
The method `onMapEvent()` looks like this:
```
public void onMapEvent(Event e, MapPosition mapPosition) {
        if (e != Map.UPDATE_EVENT) {
            if (this.mapScaleBar.isVisible()) {
                if (this.mMap.getHeight() != 0) {
                    if (this.mapScaleBar.isRedrawNecessary()) {
                        Bitmap var3 = this.mapScaleBar.mapScaleBitmap;
                        synchronized(this.mapScaleBar.mapScaleBitmap) { // HERE THE EXCEPTION IS THROWN
                            this.mapScaleBar.drawScaleBar();
                        }

                        this.bitmapRenderer.updateBitmap();
                        this.mapScaleBar.redrawNeeded = false;
                    }
                }
            }
        }
    }
```

As you can see `synchronized()` is called with `this.mapScaleBar.mapScaleBitmap` while the bitmap can be (and sometimes is) `null` for some reason.

**Comment by devemux86** [comment]
Scale bar bitmap can be null only in app exit when destroy scale bar along with map view and other resources.

Have not seen such exception, can it be reproduced with vtm-android-example?
Or could be related to app implementation and how handle map life cycle compared to [GettingStarted](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/GettingStarted.java) example.

**Comment by calvinkehl** [comment]
I will try to reproduce it with vtm-android-example.

The map life cycle is implemented exactly as in GettingStarted.
in `onCreate()` we do:

```
TileSource openScienceMap = OSciMap4TileSource.builder().httpFactory(new OkHttpEngine.OkHttpFactory()).build();
createTileCache(openScienceMap);
VectorTileLayer tileLayer = mapView.map().setBaseMap(openScienceMap);
GroupLayer groupLayer = new GroupLayer(mapView.map());
groupLayer.layers.add(new BuildingLayer(mapView.map(), tileLayer));
groupLayer.layers.add(new LabelLayer(mapView.map(), tileLayer));
mapView.map().layers().add(groupLayer);

//Scale
mapScaleBar = new DefaultMapScaleBar(mapView.map());
MapScaleBarLayer mapScaleBarLayer = new MapScaleBarLayer(mapView.map(), mapScaleBar);
mapScaleBarLayer.getRenderer().setPosition(GLViewport.Position.BOTTOM_LEFT);
mapScaleBarLayer.getRenderer().setOffset(5 * CanvasAdapter.getScale(), 0);
mapView.map().layers().add(mapScaleBarLayer);

mapView.map().setMapPosition(52.517037, 13.38886, 1 << 16);
```

**Comment by devemux86** [comment]
Check also the other life cycle methods of `Activity` in sample, for resume / pause / destroy of map.

Unless there is enabled the restart of `Activity` when device changes orientation (portrait / landscape), so with such fast changes could hit such case (disabled in [vtm-android-example](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/AndroidManifest.xml#L45)).

**Comment by calvinkehl** [comment]
> Check also the other life cycle methods of `Activity` in sample, for resume / pause / destroy of map.

The other methods are also the same.

> Unless there is enabled the restart of `Activity` when device changes orientation (portrait / landscape), so with such fast changes could hit such case (disabled in [vtm-android-example](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/AndroidManifest.xml#L45)).

Interesting, our app has to run in landscape mode, so maybe the activity first is started in portrait and then destroyed and started again in landscape mode. How can this be disabled?

**Comment by devemux86** [comment]
Depends on app implementation, if perform it via code or manifest, see also [documentation](https://developer.android.com/guide/topics/manifest/activity-element#screen).

**Comment by drakkan** [comment]
I can reproduce this issue too, in my case config changes are disabled.

I can reproduce, only sometime, if I try to load a non existent map file, more details here

https://groups.google.com/forum/#!topic/mapsforge-dev/qO3nfLr5LiU

can we add a null check? I mean something like this

```
if (mapScaleBar == null || mapScaleBar.mapScaleBitmap == null){
    return;
}
```

here

https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/scalebar/MapScaleBarLayer.java#L44

thanks

**Comment by devemux86** [comment]
`mapScaleBar` cannot get null, as a final initialization on constructor.

I can put a check for `mapScaleBitmap` to catch such corner cases.

**Comment by drakkan** [comment]
> I can put a check for `mapScaleBitmap` to catch such corner cases.

this would be great, thanks!

**Comment by calvinkehl** [comment]
Thank you! When will this fix be released?

**Comment by drakkan** [comment]
you can use a daily snapshot while waiting for an official release, take a look at the integration guide for details

https://github.com/mapsforge/vtm/blob/master/docs/Integration.md
