### ISSUE TITLE
Buildings translucency on iOS

### ISSUE THREAD

**Issue by Longri** [mapsforge/vtm#62]
On iOS the Flag BuildingLayer.TRANSLUCENT are ignored! No changes at Display!

**Comment by devemux86** [comment]
@Longri how are the buildings on iOS 10?

**Comment by Longri** [comment]
looks good
![screen shot 2016-09-25 at 09 55 04](https://cloud.githubusercontent.com/assets/2542295/18813787/7d4ae5ae-8306-11e6-9a2c-50db879cac94.png)

**Comment by devemux86** [comment]
I see them semi transparent, right?

Did you change the default `BuildingLayer.TRANSLUCENT = true`?
So is this issue still valid?

**Comment by Longri** [comment]
Yes, can close!

**Comment by devemux86** [comment]
Thanks for checking this!

Closing this as fixed in iOS 10.

**Comment by devemux86** [comment]
Regarding the flag effect on rendering, see #181.
