### ISSUE TITLE
MVT Tiles not being rendered

### ISSUE THREAD

**Issue by glorantq** [mapsforge/vtm#622]
MVT tiles (either in MVT or PBF format) are not being rendered, as you can see here:
![image](https://user-images.githubusercontent.com/17655680/50059048-39496b80-0182-11e9-9327-a6b81b504792.png)

This happens both with a locally-hosted server, and with cloud-hosted ones, such as MapTiler or Nextzen). When I download the files directly in the browser, I see data and even text for the labels, so the issue is not there:
![image](https://user-images.githubusercontent.com/17655680/50059069-82012480-0182-11e9-9b4b-fcc4878240ef.png)

Using OSciMap4 as a tile source, everything is rendered correctly:
![image](https://user-images.githubusercontent.com/17655680/50059088-9c3b0280-0182-11e9-89a3-1ea6a55fed19.png)

I am using VTM 0.10.0

**Comment by devemux86** [comment]
_For questions / discussions please use the [forum](https://groups.google.com/group/mapsforge-dev).
After a confirmed problem, we can open an issue._

Repository samples with Mapilion / OpenMapTiles / Nextzen providers work fine.
Also better use the [snapshot version](https://github.com/mapsforge/vtm/blob/master/docs/Integration.md#snapshots), as it has all latest improvements & fixes.

![nextzen](https://user-images.githubusercontent.com/3484020/50072848-4fd1e000-01df-11e9-9991-101ee2a88d47.png)
