### ISSUE TITLE
Force render of a single tile in specific layer

### ISSUE THREAD

**Issue by stleusc** [mapsforge/vtm#629]
This is more a question...
I am fighting and trying to accomplish the following.

I have a tile loader that loads tile data using a single zoom level for network performance.
Rendering of the extracted is done on the actual level.
I was not able to do this in a single layer due to the fact of loading and rendering having different zoom tables/min/max levels.

This is just background info, not really needed to answer my question...

So what I am trying:
I want to be able to force render a single map tile on a specific layer.
I need to have the ITileDataSource query running for that tile.
Is there any trigger to either force query specific tile or at least force query a layer.
Kinda mark the layer as dirty...

Calling Map.clearMap() redraws the whole map and causes flickering.

Any help?

**Comment by devemux86** [comment]
For questions / discussion please use the [forum](https://groups.google.com/group/mapsforge-dev).
