### ISSUE TITLE
Real time (SVG) texture atlas

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#63]
Generate an SVG texture atlas from `.svg` symbols (at runtime?) depending on device dpi.

The need is for increase OpenGL performance on SVG texture rendering.

**Comment by Longri** [comment]
Hi Emux,
I would now like to create an XmlAtlasThemeBuilder.
And need a flag, where a distinction is made, whether an XmlThemebuilder or an XmlAtlasThemeBuilder is taken.

I've been thinking for a very long time and would like to put this into the ThemeFile interface.
This breaks the API, but I think that all classes that implement this interface are contained in the VTM code and the users have not implemented this interface themselves.

**Comment by devemux86** [comment]
Do you mean like choosing to use one class or the other?

What's the final purpose?
Produce on the fly at 1st theme read a texture atlas from the theme SVG resources using device DPI?

**Comment by Longri** [comment]
yes, create a atlas from all used svg/png files with first reading of ThemeFile!

**Comment by devemux86** [comment]
Ok, so why we need a new theme builder class or modify the `ThemeFile`?
Don't we need some utility to make the texture atlas from SVG and some way for developers to choose whether they wish to use it in their apps or not?

**Comment by Longri** [comment]
We also want to pack a public static boolean useAtlas into the class ThemeLoader, there would have to be decided which BulderType is used.

**Comment by devemux86** [comment]
I think we should start with the simplest implementation trying to not break (if possible) the API.
When things work fine then we can decide how we can hook the SVG atlas to themes.

So I agree, a boolean flag is nice for now for backwards compatibility too.

**Comment by Longri** [comment]
Ok, I will try

**Comment by Longri** [comment]
Done!
But I will wait for #303 and #304 , to check for no conflicts

**Comment by devemux86** [comment]
Closed via #324.

**Comment by devemux86** [comment]
Until further testing, you can enable this feature with:
```java
ThemeLoader.USE_ATLAS = true;
```

**Comment by devemux86** [comment]
cc @Longri 

- We need to implement it also wherever theme resources are used, e.g. area patterns

- On Desktop with texture atlas I see blurred symbols, `MapTest` vs `AtlasThemeMapTest`:

![maptest](https://cloud.githubusercontent.com/assets/3484020/23623535/0bdc61b6-02ab-11e7-8717-419f09e40095.png)
![atlasthememaptest](https://cloud.githubusercontent.com/assets/3484020/23623539/105de0fc-02ab-11e7-93ee-a6b439a08a64.png)

**Comment by Longri** [comment]
Area can not use a TextureAtlas! 
They must have a single TexturItem for repeating. 
On OpenGL you can't repeat a TexturRegion.

**Comment by Longri** [comment]
For blurred symbols I'll check the TextureFilter

**Comment by Longri** [comment]
I think the problem is that AwtCanvas draws the Bitmap with anti aliasing, but better is without, pixel for pixel.

**Comment by devemux86** [comment]
Hmm similar drawing happens directly with SVG or in scale bar and they don't have such issues.

**Comment by Longri** [comment]
Many try's later I have a solution! PR is folloing
MapTest:
![maptest](https://cloud.githubusercontent.com/assets/2542295/23651759/d0665d9a-0326-11e7-8519-101df230052f.png)

current Atlas drawing:
![formatchange](https://cloud.githubusercontent.com/assets/2542295/23651816/03402930-0327-11e7-8b28-49660d0d7470.png)

Pixel perfect drawing;
![pixelperfect](https://cloud.githubusercontent.com/assets/2542295/23651845/1dcfa406-0327-11e7-9877-318ec533d927.png)

**Comment by Longri** [comment]
#328
