### ISSUE TITLE
Include starting guide

### ISSUE THREAD

**Issue by matkoniecz** [mapsforge/vtm#644]
Some very simple hello world example would be nice.

Screenshot has link to nice 3D map but without clear way to get source code, screenshots (great) and https://github.com/mapsforge/vtm/blob/master/docs/Integration.md but from what I see there is not even single simple hello world example that would be a good starting point for somebody new

**Comment by devemux86** [comment]
Main page links the [integration guide](https://github.com/mapsforge/vtm/blob/master/docs/Integration.md) with the needed dependencies per platform.
And a [GettingStarted](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/GettingStarted.java) example for Android, note the API is common everywhere.
Also there are many samples in [vtm-android-example](https://github.com/mapsforge/vtm/tree/master/vtm-android-example) and [vtm-playground](https://github.com/mapsforge/vtm/tree/master/vtm-playground).

We're open for suggestions for improving first-time user experience.
Though for questions and discussion please use our [forum](https://groups.google.com/group/mapsforge-dev).
