### ISSUE TITLE
OSX vtm-theme-comparator problem

### ISSUE THREAD

**Issue by ago75** [mapsforge/vtm#645]
Hi everyone,

I created an application for mac osx quite similar to vtm-theme-comparator with the map inside a JPanel.
In this case the map is not rendered and the canvas is completely black.
The problem also occurs in vtm-theme-comparator with this output:

> Task :vtm-theme-comparator:run
10:51:48.262 [LWJGL Application] DEBUG org.oscim.renderer.MapRenderer - Intel Inc./Intel Iris Pro OpenGL Engine/2.1 INTEL-12.4.7
10:51:48.543 [LWJGL Application] DEBUG org.oscim.renderer.MapRenderer - Intel Inc./Intel Iris Pro OpenGL Engine/2.1 INTEL-12.4.7
10:51:48.590 [LWJGL Application] DEBUG org.oscim.theme.comparator.mapsforge.MapsforgeMapPanel - reload MAP:/Data/job/Android/maps_repository/maps/west_alps/west_alps.map THEME:null
10:51:48.643 [LWJGL Application] DEBUG org.oscim.tiling.source.mapfile.MapFileTileSource - File version: 3
10:51:48.667 [LWJGL Application] DEBUG org.oscim.theme.XmlThemeBuilder - put style caption-small-blue
10:51:48.669 [LWJGL Application] DEBUG org.oscim.theme.XmlThemeBuilder - put style shop
10:51:48.674 [LWJGL Application] DEBUG org.oscim.theme.XmlThemeBuilder - put style tavern
10:51:48.676 [LWJGL Application] DEBUG org.oscim.theme.XmlThemeBuilder - put style accommodation
10:51:48.677 [LWJGL Application] DEBUG org.oscim.theme.XmlThemeBuilder - put style education
10:51:48.678 [LWJGL Application] DEBUG org.oscim.theme.XmlThemeBuilder - put style health
10:51:48.680 [LWJGL Application] DEBUG org.oscim.theme.XmlThemeBuilder - put style entertainment
10:51:48.682 [LWJGL Application] DEBUG org.oscim.theme.XmlThemeBuilder - put style highway-road
10:51:48.688 [LWJGL Application] DEBUG org.oscim.theme.XmlThemeBuilder - put style highway-track
10:51:48.691 [LWJGL Application] DEBUG org.oscim.theme.XmlThemeBuilder - put style ref
10:51:48.692 [LWJGL Application] DEBUG org.oscim.theme.XmlThemeBuilder - put style ref-caption
10:51:48.733 [LWJGL Application] DEBUG org.oscim.utils.Utils - loading assets:patterns/military.png
10:51:48.736 [LWJGL Application] DEBUG org.oscim.utils.Utils - loading assets:patterns/cemetery.png
10:51:48.740 [LWJGL Application] DEBUG org.oscim.utils.Utils - loading assets:patterns/wood-coniferous.png
10:51:48.744 [LWJGL Application] DEBUG org.oscim.utils.Utils - loading assets:patterns/wood-deciduous.png
10:51:48.749 [LWJGL Application] DEBUG org.oscim.utils.Utils - loading assets:patterns/wood-mixed.png
10:51:48.752 [LWJGL Application] DEBUG org.oscim.utils.Utils - loading assets:patterns/cemetery.png
10:51:48.755 [LWJGL Application] DEBUG org.oscim.utils.Utils - loading assets:patterns/access-private.png
10:51:48.758 [LWJGL Application] DEBUG org.oscim.utils.Utils - loading assets:patterns/marsh.png
10:51:48.775 [LWJGL Application] DEBUG org.oscim.utils.Utils - loading assets:patterns/nature-reserve.png
10:51:48.780 [LWJGL Application] DEBUG org.oscim.utils.Utils - loading assets:patterns/military.png
10:51:48.834 [LWJGL Application] DEBUG org.oscim.utils.Utils - loading assets:symbols/oneway.svg
10:51:49.299 [TileLoader2] DEBUG org.oscim.renderer.bucket.MeshBucket - error in tessellation 16

thanks in advance for your reply
Ago.

**Comment by devemux86** [comment]
What VTM version?
Do the [vtm-playground](https://github.com/mapsforge/vtm/tree/master/vtm-playground) samples work?

e.g. [SimpleMapTest](https://github.com/mapsforge/vtm/blob/master/vtm-playground/src/org/oscim/test/SimpleMapTest.java) or [MapilionMvtTest](https://github.com/mapsforge/vtm/blob/master/vtm-playground/src/org/oscim/test/MapilionMvtTest.java)

**Comment by ago75** [comment]
..sorry
All playgrounds work perfectly.
The VTM version is today's branch master.

OSX 10.14.3 version
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

Ago

**Comment by devemux86** [comment]
> All playgrounds work perfectly.

Then the other implementations could need changes to work too.

BTW on Linux `vtm-theme-comparator` seems working via:
```groovy
./gradlew :vtm-playground:run
```

**Comment by devemux86** [comment]
> All playgrounds work perfectly.

Then the other implementations could need changes to work too.

BTW on Linux `vtm-theme-comparator` seems working via:
```
./gradlew :vtm-theme-comparator:run
```

**Comment by ago75** [comment]
with ./gradlew: vtm-theme-comparator:run  continues to give black screen

I think the problem is caused by using java.awt.Canvas in the LwjglApplication constructor.

Ago

**Comment by ago75** [comment]
good morning,
I did an additional test:
I allowed myself to download Cruiser Desktop,
the vtm version works correctly on my mac.
.....I'm going crazy

**Comment by ago75** [comment]
Would it be possible to add a simple example with a JFrame and a JPanel containing the map in vtm-playground?

Ago

**Comment by devemux86** [comment]
Since `vtm-playground` samples work, let's continue any discussion for how to use VTM in [forum](https://groups.google.com/group/mapsforge-dev).
