### ISSUE TITLE
vtm-android: target API 28

### ISSUE THREAD

**Issue by Gustl22** [mapsforge/vtm#647]
Didn't notice any compatibility issues so far, so can upgrade android's target api version to 28?

**Comment by devemux86** [comment]
[vtm-android](https://search.maven.org/search?q=a:vtm-android) is published mainly as a [Java library](https://github.com/mapsforge/vtm/blob/master/docs/Integration.md#android), so the target is irrelevant coming from main Gradle configuration.

**Comment by Gustl22** [comment]
I mean for all android examples/apps to better estimate behavior on actual os (such as permissions).

**Comment by devemux86** [comment]
See my comments in #648.
