### ISSUE TITLE
vtm-web: cannot compile with JDK 10+

### ISSUE THREAD

**Issue by Gustl22** [mapsforge/vtm#659]
Since I upgraded to Java JDK 11, I cannot run vtm-web-app anymore. Reason is the gwt plugin, which needs Gwt 2.8.2 to [run with these java versions](https://github.com/Gustl22/vtm/commit/d7d421222e2c74fc173d8ba8820d01375cfeb5d0).
Unfortunately libGDX remains on Gwt 2.8.0 and an upgrade leads to inconsistencies. E.g. the gwt-user package is incompatible.
See: https://github.com/libgdx/libgdx/issues/5256

**Comment by devemux86** [comment]
_Note: Mapsforge + VTM cores are based on Android JDK compatibility, being still with 7, as anything even 8 related requires API level 24 or higher which is unsuitable for users._

**Comment by devemux86** [comment]
Note: Mapsforge + VTM cores are based on Android JDK compatibility, being still with 7, as anything above even 8 requires [API level 24 or higher](https://developer.android.com/studio/write/java8-support) which is unsuitable for users.

**Comment by Gustl22** [comment]
I mean if I install Java 9+ JDK for JVM, I am not able to run web modules. Compatibility to 7 should still be given, but should work with newest JDK as well. It seems we have to wait for a libGDX release with GWT 2.8.2 support.

**Comment by Gustl22** [comment]
My bad, GWT won't compile with JDK 10+. Thought it is possible :see_no_evil: Can close or wait a few years :)

**Comment by Gustl22** [comment]
Finally got it working by
- updating GWT to 2.8.2 and exclude `gwt-user`, and manually add `api "com.google.gwt:gwt-user:$gwtVersion"`
- using this [workaround](https://stackoverflow.com/questions/27522728/unable-to-compile-the-gwt-module-while-trying-to-use-javax-annotation-nullable) to leading GWT to believe there exists the `javax.annotaton.Annotation`.
- updating Gretty to at least 2.3.1 by using a recent [fork](https://github.com/gretty-gradle-plugin/gretty).

As some changes are messy I leave [branch](https://github.com/Gustl22/vtm/commit/5900b4b70b95dd39b96531cd8af5b1f080540796) as reference for future solutions, and can decide if changes are obligatory.

_BTW: At least, updating Gretty may be a good move._

**Comment by devemux86** [comment]
[LibGDX GWT backend 1.9.9](https://mvnrepository.com/artifact/com.badlogicgames.gdx/gdx-backend-gwt/1.9.9) still uses `gwt-user 2.8.0`. Could wait upstream for now, as it's the base and see how they progress.
