### ISSUE TITLE
Overpass tile source

### ISSUE THREAD

**Issue by Gustl22** [mapsforge/vtm#663]
I implemented an Overpass(Tile)Layer, so can view newest Osm changes directly for development purposes. 
Is there need of?

**Comment by boldtrn** [comment]
I think this sounds very helpful. Do you generate an overlay with the overpass results and on click a popup opens that contains the raw data?

**Comment by Gustl22** [comment]
No this was only meant for map drawing.

But a Layer to fetch element infos (for all tile sources) seems interesting, too.

**Comment by boldtrn** [comment]
Ah ok, now I understand, that sounds interesting as well :). So one can reuse the default offline maps theme but use a live online source?

**Comment by Gustl22** [comment]
Yes default theme is compatible. Of course not all optimizations done in Mapsforge map creation are available, and it's not that fast as other tile sources, but good for development and tagging.

**Comment by devemux86** [comment]
We can always add extra samples in [vtm-android-example](https://github.com/mapsforge/vtm/tree/master/vtm-android-example) and [vtm-playground](https://github.com/mapsforge/vtm/tree/master/vtm-playground) for testing. :slightly_smiling_face: 

> Do you generate an overlay with the overpass results and on click a popup opens that contains the raw data?

Such dense data as an overlay could be heavy even for OpenGL and specially on lower devices.

> But can then use `ReverseGeoCodeActivity` sample to fetch infos.

[ReverseGeocodeActivity](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/ReverseGeocodeActivity.java) is based on Mapsforge API to provide such info.
For other vector maps could need some extra implementation (e.g. #491).
Though users find more useful a proper search, not plain reverse geocode.

**Comment by boldtrn** [comment]
> Such dense data as an overlay could be heavy even for OpenGL and specially on lower devices.

Yes, if we assume that we fetch all data, but if we only fetch for example highways on high zoom levels, this should work I guess.

For example there is a nice project [Openbeermap](https://openbeermap.github.io) that fetches pubs from Overpass. I first thought this issue would be about something like this.

**Comment by Gustl22** [comment]
Could work with adding filters for custom search to accelerate overpass query and adapt theme.

**Comment by devemux86** [comment]
> adapt theme

Mean to add extra POI?

**Comment by Gustl22** [comment]
Yes, for example.

**Comment by Gustl22** [comment]
Can try [here](https://github.com/Gustl22/vtm/tree/vtm-extras).

**Comment by devemux86** [comment]
Thanks, merged via 23d65486e67d3fb9f2c38be80d125469d6ddb595.

**Comment by devemux86** [comment]
Closed via #665.
