### ISSUE TITLE
Move test classes to vtm-tests or vtm-extras

### ISSUE THREAD

**Issue by Gustl22** [mapsforge/vtm#682]
We have [`TestTileSource`](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/tiling/source/test/TestTileSource.java) and [`TestTileLayer`](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/layers/tile/example/TestTileLayer.java) in vtm-core. We should move them to vtm-extras or vtm-tests. Not sure if vtm-tests is only for unit tests or test classes, too.

**Comment by devemux86** [comment]
They're not used anywhere, so moved them in `vtm-tests` for now.

**Comment by Gustl22** [comment]
So if want to use them in playground can then depend on test module?

**Comment by devemux86** [comment]
> So if want to use them in playground can then depend on test module?

Certainly not, `vtm-tests` is not a library module, only for self-hosted tests.
Also these classes contain arbitrary code to debug various things in past.
When they will be needed in samples can move them in sample modules.

**Comment by Gustl22** [comment]
Problem is, I wanted to use these classes to debug some code. But for that need a full visible sample, not a unit test. Question is if classes should be available for other platforms, too.

**Comment by devemux86** [comment]
Well you didn't mentioned more detailes in issue description and the classes were unused. :slightly_smiling_face: 

We duplicate code in `vtm-android-example` and `vtm-playground`, so can move then in the needed samples module, unless we decide differently in the future.

**Comment by devemux86** [comment]
Or you can create your own test classes and leave them as-is there for the history.

**Comment by Gustl22** [comment]
Didn't expect to react so quickly with a commit. My fault, didn't mention to use them.
So can you move to playground then?

**Comment by devemux86** [comment]
See my above [comment](https://github.com/mapsforge/vtm/issues/682#issuecomment-468908025).

Probably you need to change them too, can't you create your own ones for your testing?

**Comment by Gustl22** [comment]
Ok, only wanted to avoid double code. Then I'll make my own classes and then decide if need the "old" ones.
