### ISSUE TITLE
vtm-playground/AnimatorTest not working

### ISSUE THREAD

**Issue by 4rne** [mapsforge/vtm#696]
I want to use the `Map.animator().animateTo()` method in my desktop application. But I can't even get the `AnimatorTest` from the vtm-playground to work like (I expect) it should.
The `animateTo()` method seems to only animate the map properly, if the map is already moving (zooming in or out, or fling animation). Otherwise it does nothing.
Steps to reproduce:
1. clone the repository
2. import as gradle project into Eclipse
3. run `vtm-playground/src/org.oscim.test/AnimatorTest.java`

This happens with Oracle Java 8u201 on Win7 and OpenJDK 10.0.2 on Linux

How it looks on my machine:
[animator_test_behavior_video.zip](https://github.com/mapsforge/vtm/files/2938959/animator_test_behavior_video.zip)

**Comment by devemux86** [comment]
Thanks for the report.

As seen in [InputHandler](https://github.com/mapsforge/vtm/blob/master/vtm-gdx/src/org/oscim/gdx/InputHandler.java) various key events, we missed a `map.updateMap` call here.

**Comment by 4rne** [comment]
Thank you for the fast fix!
