### ISSUE TITLE
BitmapRenderer.initialized property

### ISSUE THREAD

**Issue by vasilenkoalexey** [mapsforge/vtm#697]
Looks like:
1. `BitmapRenderer.initialized` should set to `true` at `BitmapRenderer.update` method
```
@Override
    public synchronized void update(GLViewport v) {
        if (!initialized) {
            buckets.clear();

            BitmapBucket l = new BitmapBucket(true);
            l.setBitmap(mBitmap, mWidth, mHeight);
            buckets.set(l);

            mUpdateBitmap = true;
        }

        if (mUpdateBitmap) {
            mUpdateBitmap = false;
            compile();
        }
    }
```
2. `BitmapRenderer.initialized` can by replaced by `BucketRenderer.mInititialzed`
3. `BucketRenderer.mInititialzed` should by renamed to `BucketRenderer.mInitialized`

**Comment by devemux86** [comment]
(1) Have you test that or seen any issues with current implementation?
`BitmapRenderer` is used in scale bar and if do that change, then scale bar doesn't work anymore.

(2, 3) Thanks, fixed that.

**Comment by vasilenkoalexey** [comment]
> then scale bar doesn't work anymore.

Very strange, i will test it. As i see `BitmapRenderer.initialized` is always `false`. So `if (!initialized)` can be removed or `BitmapRenderer.initialized` should set to `true` inside `if` body.

**Comment by devemux86** [comment]
It's not strange, as scale bar bitmap is not fixed but dynamic, so needs often updating.

>  So if (!initialized) can be removed or BitmapRenderer.initialized should set to true inside if body.

`BitmapRenderer` and `mInitialized` are generic, may be needed for another implementation. So if it works correctly we can leave it for future reference.

**Comment by vasilenkoalexey** [comment]
Ok, now it's clear, issue can by closed
