### ISSUE TITLE
Large 3D POI model and map-view collision detecting

### ISSUE THREAD

**Issue by schedul-xor** [mapsforge/vtm#698]
Currently, POI 3D objects are related to lat/long points.

In most cases when 3d poi models are small enough, lat/long points are suitable for location expression. But when the models are extremely large (bridge models for example), models will disappear from map if the lat/long goes out from map view.

 To prevent this issue, large 3d models may have polygon data used for map-view collision detecting.

**Comment by devemux86** [comment]
Can discuss in [forum](https://groups.google.com/group/mapsforge-dev) and if there is interest from community to contribute.
