### ISSUE TITLE
Android: OpenGL version extraction crash

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#705]
Some manufacturers don't adhere to spec: `OpenGL ES <major>.<minor> <vendor-specific information>`.

So Android OpenGL version extraction, introduced in #652, crashes VTM on devices due to not proper fallback.

**Comment by devemux86** [comment]
Fixed via a7d50fa8fa8706b15d452320c834b274b9f7478f.

**Comment by Gustl22** [comment]
Thanks!
