### ISSUE TITLE
MBTiles vector tile source

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#712]
Implement MBTiles vector tile source for all supported platforms.

**Comment by devemux86** [comment]
After #711 the work should be mostly changing the tiles type.

**Comment by boldtrn** [comment]
Indeed, adding a MBtiles vector source should be fairly straight forward now. 

One thing to consider is if the tile data is gzipped in the MBtile. So one might has to unzip the data.

**Comment by devemux86** [comment]
Can discuss in [forum](https://groups.google.com/group/mapsforge-dev) and if there is interest from community to contribute.

**Comment by devemux86** [comment]
Implemented in #740.
