### ISSUE TITLE
GLSurfaceView RuntimeException on Android 4.2

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#713]
There are reports for crashes of latest VTM on Android 4.2.

As all previous versions worked fine, probably some of the latest OpenGL changes (3D shadows, GL API, shaders) seem to cause that unwanted behavior.

```java
java.lang.RuntimeException: 
  at android.opengl.GLSurfaceView$EglHelper.throwEglException (GLSurfaceView.java:1201)
  at android.opengl.GLSurfaceView$EglHelper.throwEglException (GLSurfaceView.java:1192)
  at android.opengl.GLSurfaceView$EglHelper.start (GLSurfaceView.java:1042)
  at android.opengl.GLSurfaceView$GLThread.guardedRun (GLSurfaceView.java:1409)
  at android.opengl.GLSurfaceView$GLThread.run (GLSurfaceView.java:1248)
```

**Comment by Gustl22** [comment]
You know if it's reproduceable with emulator?

**Comment by devemux86** [comment]
I always test VTM also in emulator on Android 4.1 (API level 16) and seems working fine.

But emulator's OpenGL using desktop GPU, is not representative of actual device GPU.

**Comment by Gustl22** [comment]
I see. If I obtain such a device, I'll let u know the results.

**Comment by devemux86** [comment]
Devices reported with Android 4.2:
- [Sony Xperia Z](https://www.gsmarena.com/sony_xperia_z-5204.php) (Adreno)
- [Samsung Galaxy Tab 2 10.1](https://www.gsmarena.com/samsung_galaxy_tab_2_10_1_p5110-4669.php) (PowerVR)
- [Lenovo IdeaTab A3000](https://www.gsmarena.com/lenovo_ideatab_a3000-5353.php) (PowerVR)
- [Huawei Ascend G700](https://www.gsmarena.com/huawei_ascend_g700-5633.php) (PowerVR)

**Comment by devemux86** [comment]
Android documentation states that for [Checking the OpenGL ES version](https://developer.android.com/guide/topics/graphics/opengl.html#version-check), should attempt to create the higher-level OpenGL ES context (`EGLContext`) and check the result in [GlContextFactory](https://github.com/mapsforge/vtm/blob/master/vtm-android/src/org/oscim/android/gl/GlContextFactory.java).

The problem is that on Android 4.2 the returned OpenGL ES context is OpenGL ES 3.0, even if the devices support only OpenGL ES 2.0!

Also since [OpenGL ES 3.0 is supported with Android 4.3 (API level 18) and higher](https://developer.android.com/guide/topics/graphics/opengl.html#compatibility), such check is useful on newer Android versions, in older ones can use directly the supported OpenGL ES 2.0.

**Comment by devemux86** [comment]
[VTM 0.11.1](https://search.maven.org/search?q=g:org.mapsforge) was released with the fix.
