### ISSUE TITLE
Problems caused by activity switching

### ISSUE THREAD

**Issue by geochenyj** [mapsforge/vtm#720]
Map activity with BitmapTileLayer and JeoVectorLayer (Polygon on this layer) can be switched to blank activity with MapView by calling startActivity, and then back up. Abnormal phenomena occur. Vector elements （Polygon）on JeoVector Layer sometimes become a line, 
meanwhile，BitmapTile Layer and Background raster layers will flicker fiercely and lack tiles

![normal](https://user-images.githubusercontent.com/28072949/56797982-83d1a780-6848-11e9-9a40-88fb6ce510d9.jpg)
This is normal

![abnormal](https://user-images.githubusercontent.com/28072949/56798117-c2fff880-6848-11e9-812d-86ede396be14.jpg)
This is abnormal

sometimes，BitmapTile Layer and Background raster layers will flicker fiercely and lack tiles

**Comment by devemux86** [comment]
See the [GettingStarted](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/GettingStarted.java) about how to properly use the MapView with Activity life cycle.

Or could be related to #194.

For questions or discussion about the library use please use first our [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by geochenyj** [comment]
Your answer still hasn't solved my problem！

**Comment by geochenyj** [comment]
Your MultiMapViewActivity is also problematic, which must be the result of poorly managed shared resources

**Comment by devemux86** [comment]
> Your MultiMapViewActivity is also problematic

Obviously it is, since as seen in mentioned #194, multiple map views are **not** supported.
vtm-android-example samples work fine when switch activities following Android life cycle.

Can continue discussion in [forum](https://groups.google.com/group/mapsforge-dev).
Issues list is for monitor confirmed (non duplicate) problems or new features.
