### ISSUE TITLE
Custom Theme-File ignores new value

### ISSUE THREAD

**Issue by calvinkehl** [mapsforge/vtm#722]
Hi, I've created a custom theme file from the default theme. I added one value "exit" to the "highway" key, to show a custom symbol "exit.svg". 
I've also created my own OSM map containing points with attrubute "highway=exit", but for some reason the new symbol is not drawn. Other symbols work perfectly.
How to fix this?

**Comment by devemux86** [comment]
For questions or discussion please always use the [forum](https://groups.google.com/group/mapsforge-dev).
