### ISSUE TITLE
enable zooming of markers

### ISSUE THREAD

**Issue by tsuellow** [mapsforge/vtm#730]
Hi, I am trying to allow for zooming of the MarkerLayer within a range. such that markers will become bigger/smaller when I zoom in/out up to a point. I have seen that other layers such as vector layers exhibit this behaviour but I have not been able to achieve the same result with markers.  the farthest I got was rescaling the bitmap in the MarkerRenderer class but this messes with the resolution of the bitmap.
Is this possible and could you point me in the right direction in the code?

- Forum: https://groups.google.com/group/mapsforge-dev

- Contributing Guide: https://github.com/mapsforge/vtm/blob/master/docs/CONTRIBUTING.md

**Comment by devemux86** [comment]
For questions please use the [forum](https://groups.google.com/group/mapsforge-dev).
