### ISSUE TITLE
Render theme: only match tags with filled values

### ISSUE THREAD

**Issue by boldtrn** [mapsforge/vtm#736]
There is an option to match tags that have no value: `~`, but the opposite is not available. Using for example: `-|~` does not work.

**Comment by devemux86** [comment]
According to [documentation](https://github.com/mapsforge/vtm/blob/master/docs/Rendertheme.md) for the `~`:

_"A tilde `~` matches if the map element does not have a tag with the specified key."_

**Comment by devemux86** [comment]
All tags declared in themes have respective keys and values.
What probably mean is check if is filled another tag, e.g. `name`.

So match `amenity=restaurant` + filter the named ones.
Don't know if it's feasible during theme processing to know beforehand the element data and their multilingual names.

In any case can discuss and investigate first in [forum](https://groups.google.com/group/mapsforge-dev) any possibility and then see if can proceed. Naturally any valid contribution is welcome.

**Comment by devemux86** [comment]
See [here](https://github.com/mapsforge/vtm/blob/master/vtm-themes/resources/assets/vtm/default.xml#L1096-L1097).
