### ISSUE TITLE
JTS (LocationTech) 1.16.1

### ISSUE THREAD

**Issue by sunshine0576** [mapsforge/vtm#738]
JTS (LocationTech) current version is 1.6.1，When to update it？

**Comment by devemux86** [comment]
There are no plans, since JTS 1.16 seems to require latest Android 7 Nougat (API 24):

```java
D8: Default interface methods are only supported starting with Android N (--min-api 24):
org.locationtech.jts.geom.Coordinate org.locationtech.jts.geom.CoordinateSequence.createCoordinate()
```
See also https://github.com/locationtech/jts/issues/145

For questions, reports and discussion please always use the [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by CodeK1988** [comment]
JTS (LocationTech) current version is 1.19.0，When to update it？

**Comment by devemux86** [comment]
We may see this in the future as min Android increases.

VTM works fine with current JTS, why want an update?

**Comment by CodeK1988** [comment]
because OffsetCurveBuilder getOffsetCurve not working. works fine when distance is set to 100, has bug when set to 1000.
ocb.getOffsetCurve(lineDrawable.getGeometry().getCoordinates(), -100 / NEARNESS_FACTOR);  working.
ocb.getOffsetCurve(lineDrawable.getGeometry().getCoordinates(), -10000 / NEARNESS_FACTOR);  have bug. @devemux86

**Comment by devemux86** [comment]
You can exclude VTM transitive dependencies in application Gradle and use your preferred versions.

**Comment by CodeK1988** [comment]
@devemux86 not working, https://github.com/wdtinc/mapbox-vector-tile-java/issues/48  get this. by the way,thank you reply. mate

**Comment by devemux86** [comment]
Dependencies are not updated without extensive testing and they must update + work together.
_More important is not break Android min SDK and keep compatibility with older Android / Java._

VTM uses JTS in `vtm-jts` for overlays, which is a core feature of the library and must work.

Mapbox vector tiles in `vtm-mvt` module use 3rd-party `mapbox-vector-tile` lib (using JTS).
