### ISSUE TITLE
Could not resolve org.mapsforge:vtm:master-SNAPSHOT

### ISSUE THREAD

**Issue by carlos-mg89** [mapsforge/vtm#742]
I'm getting quite often in Android Studio these errors:

> ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve org.mapsforge:vtm:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve org.mapsforge:vtm-themes:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve org.mapsforge:vtm-android:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve org.mapsforge:vtm-android-mvt:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve org.mapsforge:vtm-gdx:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve org.mapsforge:vtm-android-gdx:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve org.mapsforge:vtm-http:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve org.mapsforge:vtm-mvt:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve org.mapsforge:vtm:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve org.mapsforge:vtm-themes:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve org.mapsforge:vtm-android:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve org.mapsforge:vtm-android-mvt:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve org.mapsforge:vtm-gdx:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve org.mapsforge:vtm-android-gdx:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve org.mapsforge:vtm-http:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve org.mapsforge:vtm-mvt:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve org.mapsforge:vtm:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve org.mapsforge:vtm-themes:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve org.mapsforge:vtm-android:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve org.mapsforge:vtm-android-mvt:master-SNAPSHOT.
> Show Details
> Affected Modules: app
> 
> 

If I change the version to "0.12.0" it works good again, but then I don't have the content of the current master version. Sometimes it works, and sometimes it does not. But most of the times it doesn't.

Perhaps anything wrong with my config?

**Comment by devemux86** [comment]
See the [integration guide](https://github.com/mapsforge/vtm/blob/master/docs/Integration.md#snapshots).

For questions, reports and discussion please always use the [forum](https://groups.google.com/group/mapsforge-dev).
