### ISSUE TITLE
Risk of memory leak in texturepool

### ISSUE THREAD

**Issue by sunshine0576** [mapsforge/vtm#747]
This usage can lead to memory leaks，probably because bitmap is not released。

    @Override
    protected void processFeatures(Task t, Box bbox) {       
        if (Double.isNaN(bbox.xmin))
            return;
        /* go through features, find the matching style and draw */
        synchronized (this) {
            mTextLayer=new TextBucket();
            t.buckets.set(mTextLayer);
            int index_text=0;
            int N=20;
            for (int i = -N; i <N ; i++) {
                for (int j = -N; j <N ; j++) {
                    TextItem it = TextItem.pool.get();
                    String text=System.currentTimeMillis()+":"+index_text++;
                    it.set(i*20, j*20, text, mText);
                    mTextLayer.addText(it);
                }
            }
            mTextLayer.prepare();
        }
    }

**Comment by devemux86** [comment]
For questions, reports and discussion please always use the [forum](https://groups.google.com/group/mapsforge-dev).

With details to reproduce / verify the report and after that how can be improved.
(above code doesn't exist in library)
