### ISSUE TITLE
PathLayer does not support outlines and CAPs

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#756]
I wanted to add outline in PathLayer. I've noticed that it is not currently supported. I've tried to modify VTM code to add it. As I understand it should be added somewhere here:
https://github.com/mapsforge/vtm/blob/b2a8d3040ad3ad861818467ff17a5f7ffce868b0/vtm/src/org/oscim/layers/PathLayer.java#L337
But I'm not familiar with OpenGL staff and several hours of experiments didn't help.

I've also noticed that CAPs are also not supported. I've found #107, but it seems I am missing some essential knowledge - why path layers behave differently from vector tile layers if they use the same buckets?

Is there any other way to draw nice looking thick lines over map?

**Comment by devemux86** [comment]
Outlines can be rendered like in render themes with 2 lines: one wider below for casing and one thinner on top for core.

For questions, reports and discussion please always use the [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by devemux86** [comment]
Should be fixed in #758.
