### ISSUE TITLE
vtm-jeo cannot compile because the boundlessgeo.com maven repo is not reachable

### ISSUE THREAD

**Issue by ironjan** [mapsforge/vtm#768]
The maven repository https://repo.boundlessgeo.com/main/ is currently not reachable.
The corresponding company Boundlessgeo has been acquired by another company called planet. 
https://boundlessgeo.com/ redirects to https://www.planet.com/ - I don't know if https://repo.boundlessgeo.com/main/ will be down for an indefinite time.

Are there any mirrors for the [jeo dependencies](https://github.com/mapsforge/vtm/blob/master/docs/Integration.md#jeo-indoor-maps)?

```
> Could not resolve all task dependencies for configuration ':vtm-android-example:releaseCompileClasspath'.
   > Could not resolve org.jeo:jeo:0-SNAPSHOT.
     Required by:
         project :vtm-android-example > project :vtm-jeo
      > Could not resolve org.jeo:jeo:0-SNAPSHOT.
         > Unable to load Maven meta-data from https://repo.boundlessgeo.com/main/org/jeo/jeo/0-SNAPSHOT/maven-metadata.xml.
            > Could not HEAD 'https://repo.boundlessgeo.com/main/org/jeo/jeo/0-SNAPSHOT/maven-metadata.xml'.
               > repo.boundlessgeo.com
   > Could not resolve org.jeo:jeo-carto:0-SNAPSHOT.
     Required by:
         project :vtm-android-example > project :vtm-jeo
      > Could not resolve org.jeo:jeo-carto:0-SNAPSHOT.
         > Unable to load Maven meta-data from https://repo.boundlessgeo.com/main/org/jeo/jeo-carto/0-SNAPSHOT/maven-metadata.xml.
            > Could not HEAD 'https://repo.boundlessgeo.com/main/org/jeo/jeo-carto/0-SNAPSHOT/maven-metadata.xml'.
               > repo.boundlessgeo.com
```

**Comment by ironjan** [comment]
Sorry, accidentally created an issue instead of forum post.

**Comment by devemux86** [comment]
I disabled the `vtm-jeo` module, so VTM can build successfully, until a solution is found.

Note that I reported some years ago in https://github.com/mapsforge/vtm/issues/375 that `vtm-jeo` uses old dependencies.
We should upgrade them to Maven, but community has not helped in the changes.
