### ISSUE TITLE
PointDrawable.java

### ISSUE THREAD

**Issue by LonelyPluto** [mapsforge/vtm#775]
at the class path vtm/vtm-jts/src/org/oscim/layers/vector/geometries/PointDrawable.java
the 
`public PointDrawable(GeoPoint point, Style style) {
        this(point.getLongitude(), point.getLatitude(), style);
    }`
The parameters are reversed，should be `this(point.getLatitude(), point.getLongitude(), style);`

**Comment by devemux86** [comment]
Thanks for the report.
