### ISSUE TITLE
Which version should be used

### ISSUE THREAD

**Issue by LonelyPluto** [mapsforge/vtm#777]
when I use Graphhopper routing，I download Graphhopper routing files from this address [https://download.mapsforge.org/graphs/](url),
I use the Graphhopper library 
`implementation 'com.graphhopper:graphhopper-core:1.0'`，
but running error
`An error happened while creating graph:Version of string_index unsupported: , expected:5. Make sure you are using the same GraphHopper version for reading the files that was used for creating them.`

Which version should I use？

**Comment by devemux86** [comment]
For questions or discussion please use the [forum](https://groups.google.com/group/mapsforge-dev).

**Comment by devemux86** [comment]
Mapsforge server provides GraphHopper 0.13 graphs.

GraphHopper dropped support for offline routing and Android: https://github.com/graphhopper/graphhopper/issues/1940
