### ISSUE TITLE
Not clipping Buildings and Buildingparts leads to rendering Issues

### ISSUE THREAD

**Issue by braandl** [mapsforge/vtm#787]
I came along an issue, that in some rare cases, where large buildings are drawn, crossing tile boundarys, the renderer generates artifacts.

![clipping-problem](https://user-images.githubusercontent.com/3504490/95457106-aee28500-0970-11eb-8aac-9366e06bf2b4.png)

The issue ist related with https://github.com/mapsforge/vtm/blob/98a977ea722c7beb0c3985b812d69c2b6e21fe3d/vtm/src/org/oscim/tiling/source/mapfile/MapDatabase.java#L1038-L1044 for Mapsforge Layers and
https://github.com/mapsforge/vtm/blob/98a977ea722c7beb0c3985b812d69c2b6e21fe3d/vtm/src/org/oscim/tiling/OverzoomDataSink.java#L49-L55 for Vectortilelayers.

Omitting the seperator and always using the clipper does solve this problem, but I had no time to track down the stated performance drawback so far.

**Comment by devemux86** [comment]
Which map file and coordinates can reproduce the report?

`TileSeparator` was introduced in #518.
@Gustl22 any thoughts?

**Comment by braandl** [comment]
For me this issue appears at quite some buildings that occupy large areas.

e.g. Lat 51.5260895 Long 9.8851319

with OSciMap4 Tilesource using latest Tilestache as a Tile Server.

It also happens on the same area converted to a mapsforge mapfile.

**Comment by braandl** [comment]
For testing I now did add the same buffer on the tilesperator as it is configured on the tileclipper, which fixes the visible problems. I am not sure if it fixes all of them, but at least the once I know about.

**Comment by Gustl22** [comment]
Back then, I missed the two cases on the right, which occur more often on large zoom levels.

![TileSeparator](https://user-images.githubusercontent.com/18537755/95792464-d70d1380-0ce3-11eb-848a-ed439dde3fc1.png)

A possible solution would be to use Algorithm of TileClipper to determine if geometry is inside or outside of a tile, but without actually clipping the geometry, to not destroy S3DB buildings. 
One drawback: With TileClipper algo you experience small lag, especially on large cities with mobile devices (need to test without labels).

Points / POIs can further be separated with TileSeparator.

**Comment by devemux86** [comment]
> One drawback: With TileClipper algo you experience small lag, especially on large cities with mobile devices (need to test without labels).

Performance and stability are always our top priorities, so cannot load the library with too much calculations (unless be optional).

So what would be an improvement, use the buffer of `TileClipper` also in `TileSeparator` (applicable on `OverzoomDataSink`)?
Use `TileClipper` everywhere like before?
Or need something else?

Where is `TileSeparator` really needed and for what?

**Comment by devemux86** [comment]
> One drawback: With TileClipper algo you experience small lag, especially on large cities with mobile devices (need to test without labels).

Performance and stability are always our top priorities, so cannot load the library with too much calculations (unless be optional).

So what would be an improvement, use the buffer of `TileClipper` also in `TileSeparator` (applicable on `OverzoomDataSink`)?
Use `TileClipper` everywhere like before?
Or need something else?

**Comment by devemux86** [comment]
> One drawback: With TileClipper algo you experience small lag, especially on large cities with mobile devices (need to test without labels).

Performance and stability are always our top priorities, so cannot load the library with too many calculations (unless be optional).

So what would be an improvement, use the buffer of `TileClipper` also in `TileSeparator` (applicable on `OverzoomDataSink`)?
Use `TileClipper` everywhere like before?
Or something else?

**Comment by braandl** [comment]
If I understand this correctly, the buffer would only decrease the amount of pitfalls, since it is artificially widening the grid.

Maybe we can make a less accurate approach like matching the boundingsbox to the containing tiles? That would be implementable in O(1). At least it would be much more effective than the TileClipper and about on par with the TileSeperator?

**Comment by Gustl22** [comment]
@braandl applying the tile separator to the bounding box seems a very interesting approach for almost all cases, except for the rare third case, where inner tiles are ignored. Then we have to use the width and height of the geometry (which already should be available, when calculating the bounding box). And if it is larger than the actual tile width / height, we use a more precise algo e.g. the one from TileClipper.

Yes, the buffer adapts to zoom level and therefore I think it don't makes much difference in very high zoom levels (imagine a large airport, which will inherit lots of overzoomed tiles).

**Comment by braandl** [comment]
@Gustl22 I'd think that, ignoring holes in polygons, all tiles that are in between the tile coordinate extremas, must also be inside, or am I mistaken?
So whenever `tileMax_X - tileMin_X > 1`, all tiles in between must also be inside, which is the third case. Same for `Y` of course.

I think, since this is all about S3DB holes are properbly not very relevant (even tough I am not 100% sure how the S3DB is implemented)?

**Comment by Gustl22** [comment]
You are correct, but DataSink architecture doesn't allow such assumptions, as each tile and its elements are calculated separately without knowing that neighbor tiles already include this element.

> I think, since this is all about S3DB holes are properbly not very relevant

No, the holes can only occur in polygon rendering (like your case) with TileSeparator. S3DB roofs only will be affected, when clipping the polygons.

**Comment by braandl** [comment]
Ah, yes, you are absolutly right.
Without verifying right now, the part-element of the building should be still contained in the tile and occupy most of it's space, elsewise all those parts would be missing?

So is it even a Problem?

**Comment by Gustl22** [comment]
Do you mean the TileSeparator algo? Like shown in the [image](https://github.com/mapsforge/vtm/issues/787#issuecomment-707360981), the elements are only attached to the tile, if at least one point is inherited in the tile boundaries (+- buffer), so if all points (even of a bounding box) are outside of a tile, the tile renderer won't know to render the whole surface as a building (at least I expect that).

**Comment by braandl** [comment]
Hm, but when I create a Tile from mit PostGIS, it should select the entity and clip it to the exact size of that vector-tile?

**Comment by devemux86** [comment]
Let's continue the discussion in the [forum](https://groups.google.com/group/mapsforge-dev) as these are the [instructions](https://github.com/mapsforge/vtm/blob/master/docs/ISSUE_TEMPLATE.md) appearing in new issues
and if after we can reproduce the report and decide for a solution then can see what to be done.
