### ISSUE TITLE
not found OkHttpEngine

### ISSUE THREAD

**Issue by ccclao** [mapsforge/vtm#791]
For questions or discussion please use the [forum](https://groups.google.com/group/mapsforge-dev).
package org.oscim.tiling.source.OkHttpEngine

**Comment by devemux86** [comment]
It exists in `vtm-http` module, see the [integration guide](https://github.com/mapsforge/vtm/blob/master/docs/Integration.md#online-tiles).

For questions or discussion please use the [forum](https://groups.google.com/group/mapsforge-dev).
