### ISSUE TITLE
Jar with dependencies

### ISSUE THREAD

**Issue by Longri** [mapsforge/vtm#82]
At vtm-android-0.6.0-SNAPSHOT.jar the AndroidSvg is not included.
At vtm-desktop-0.6.0-SNAPSHOT.jar the SVG Salamander is not included!

One has to set an additional dependence!

compile 'com.caverock: androidsvg: 1.2.2-beta-1'
compile 'com.kitfox.svg: svg salamander: 1.0'

**Comment by devemux86** [comment]
Dependencies never were included in a library's published artifacts.
The developer is supposed to do that in the app, having the flexibility to choose the dependencies versions too.

What I can provide is probably `jar-with-dependencies` artifacts for the platforms, like I did for Mapsforge.

**Comment by devemux86** [comment]
I added `jar-with-dependencies` artifacts for the platforms:
- vtm-android
- vtm-android-gdx
- vtm-desktop
- vtm-ios
