### ISSUE TITLE
Map scale bar

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#84]
VTM map scale bar is Mapsforge's old implementation.
It's not dpi aware and works only on Android.

A new implementation should work on all platforms with various unit adapters, like in Mapsforge.

Having it as layer isn't probably the best approach, instead of regular platform view / panel?

**Comment by andreynovikov** [comment]
Don't think making it a regular view is a good idea. Instead it should be implemented in vector and be drawn by GL like position indicator.

**Comment by devemux86** [comment]
Why is that?
External map components have usually nothing to do with internal map rendering.

**Comment by devemux86** [comment]
BTW painting a bitmap scale bar in GL is not vector rendering.

**Comment by andreynovikov** [comment]
I know, so I propose to make it true vector.

**Comment by Longri** [comment]
but I think that map scale bar is no external map components

**Comment by devemux86** [comment]
Map scale bar is a component placed on top of map, like a location button.
It just listens for map changes, it has not to take part in map elements rendering.

If you have a true vector scale bar please submit a PR.
A true vector should work in any platform from the start.

Currently the only working available is Mapsforge's and it involves bitmap rendering.

**Comment by devemux86** [comment]
I integrated Mapsforge's scale bar (Android) in #88.
DPI aware, multiple units, smooth rendering, etc.

I deliberately kept separately the core scale bar classes from the bitmap renderer.
There is new `MapScaleBarLayer` for that, see API in action at `SimpleMapActivity`.

For the rest platforms I need first to enrich VTM graphics API, like in Mapsforge.

**Comment by andreynovikov** [comment]
As for me, looks a little bit over-scaled. Otherwise perfect.

**Comment by devemux86** [comment]
Others in Mapsforge have found it small!
We can never satisfy all, I'll see making the scale factor variable.

**Comment by devemux86** [comment]
After the needed Graphics API refactoring in #92...
The map scale bar moved in `vtm` module, being now a multi-platform implementation.
