### ISSUE TITLE
Default theme: Flat buildings should be drawn if BuildingLayer is not added

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#91]
Building extrusion is hardcoded in the theme:
https://github.com/mapsforge/vtm/blob/master/vtm-themes/resources/assets/styles/default.xml#L543
If 3D buildings layer is not added then regular buildings are not drawn at zooms 17+.

**Comment by devemux86** [comment]
Other themes (besides `default`) seem working correctly.
So all that needs done is remove the `zoom-max` from regular buildings.
