### ISSUE TITLE
Graphics API enhancements

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#92]
- Enhance graphics API
- Fix platform inconsistencies

**Comment by devemux86** [comment]
I pushed a major refactoring of multi-platform Graphics API.
Adding, improving and fixing many things for supported platforms.

**Comment by devemux86** [comment]
@longri you can check the TODO in `IosCanvas` and `IosPaint` for iOS to support all new functionality.

**Comment by Longri** [comment]
Yes of course, wich playground project can I use to see it works?

**Comment by devemux86** [comment]
It's used in Android `SimpleMapActivity` and Desktop `MapTest` classes for the new map scale bar.

**Comment by Longri** [comment]
@emux almost finished! 
But I found a little problem with text color. They are always white. I think in IosPaint I have set the default color wrong. 
Can you say where you set the Paint for the text. 
At RoboVm I can't set a debug break, so I must set log output to check if the Paint has correct values.

**Comment by devemux86** [comment]
@Longri you can see the text color use in `DefaultMapScaleBar`'s [paints creation](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/scalebar/DefaultMapScaleBar.java#L67-L68) for `fill` / `stroke` and in [createTextPaint](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/scalebar/DefaultMapScaleBar.java#L109-L117) method.

**Comment by Longri** [comment]
Ok thanks, the problem is the StrokeWidth=0.
I will check this!

**Comment by devemux86** [comment]
You mean for for `fill` paint?
That's normal and is ignored in that case.

**Comment by Longri** [comment]
I have see it on Android but I have a mistake at IosPaint. 
I will fix it in the evening

**Comment by Longri** [comment]
done
