### ISSUE TITLE
Opengles render weather grib data

### ISSUE THREAD

**Issue by qq908323236** [mapsforge/vtm#939]
Hello,

I want to render weather grid data through OpenGLES，Like this
![image](https://user-images.githubusercontent.com/19360225/176876423-15f70f28-85d3-40dd-b7ca-bcb54818b510.png)
Now the weather data is available,

I don't know how to transform opengles vertex coordinates into map coordinates，I didn't find this matrix.

Vertex coordinates:
![image](https://user-images.githubusercontent.com/19360225/176807528-29ba770c-abbe-43bf-9710-435ae657059d.png)

I want to use a matrix to make the rendered position of vertex coordinates cover the whole map,So I can render the weather data to the map

**Comment by devemux86** [comment]
For questions, reports and feature requests please use the Discussions.

https://github.com/mapsforge/vtm/discussions/938
