### ISSUE TITLE
Outline of area not visible

### ISSUE THREAD

**Issue by Klaus-Tockloth** [mapsforge/vtm#981]
The following statement renders an outline (framing) for an area in Mapforge (see 'stroke-with' parameter):

`<area src="file:/patterns/mischwald-einfach.svg" stroke="#69c274" stroke-width="0.05" symbol-width="32"/>`

The same statement in VTM leads to nothing or nearly (?) nothing.

Mapsforge:
![Mapsforge](https://user-images.githubusercontent.com/5493128/203822537-1154bf88-cc5d-467e-874f-4fbdd497b2b8.jpg)

VTM:
![VTM](https://user-images.githubusercontent.com/5493128/203822546-faf2c157-3090-49f8-880e-066d3df43ce1.jpg)

**Comment by devemux86** [comment]
Please see https://github.com/mapsforge/vtm/issues/121#issuecomment-238960462 and https://github.com/mapsforge/vtm/issues/121#issuecomment-564531329.

Recommendation: use separate lines (i.e. extra theme rules) for area outlines in OpenGL.
Or probably [XmlThemeBuilder](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/theme/XmlThemeBuilder.java) could make such an addition when parsing an area stroke?

**Comment by Klaus-Tockloth** [comment]
The problem can be solved by splitting the rendering instruction:

Not working:

`<area fill="#f1eee9" stroke="#bfbcb7" stroke-width="0.05"/>`

Working:
```
<area fill="#f1eee9"/>
<line stroke="#bfbcb7" stroke-width="0.05"/>
```
We will change this within the map theme.

**Comment by devemux86** [comment]
Let's keep it open, because even though we can split the rendering instructions in the themes,
perhaps VTM theme parser can automatically do the split internally, so all themes could work.
