### ISSUE TITLE
stroke-dasharray not working as expected

### ISSUE THREAD

**Issue by Klaus-Tockloth** [mapsforge/vtm#983]
Dashed lines are not rendered as expected. We have this:

```
<line stroke="#99f1eee9" stroke-width="0.7" stroke-linecap="butt"/>
<line stroke="#ad8500" stroke-width="0.5" stroke-dasharray="2.0,1.0" stroke-linecap="butt" scale="all"/>
```
Mapsforge:
![mapsforge](https://user-images.githubusercontent.com/5493128/204105132-716413ff-47f0-45ca-bc0d-365149768737.jpg)

VTM:
![vtm](https://user-images.githubusercontent.com/5493128/204105137-42944eba-da73-4e97-b7d6-2c5029f7e930.jpg)

**Comment by devemux86** [comment]
For reference in [XmlThemeBuilder.createLine](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/theme/XmlThemeBuilder.java) there is a section to create stipple with color
from the line dasharray instruction.

**Comment by devemux86** [comment]
[Cruiser 3.0.3](https://wiki.openstreetmap.org/wiki/Cruiser) is available with the latest VTM library.
Please try it and see if now rendering works properly
