### ISSUE TITLE
Lines with SVG pattern are draw as black lines

### ISSUE THREAD

**Issue by Klaus-Tockloth** [mapsforge/vtm#985]
We have lines with a SVG pattern. They are rendered incorrectly as 'black lines':

`<line src="file:/patterns/fussgaengerzone.svg" symbol-width="32" stroke-width="1.5" stroke-linecap="butt"/>`

Mapsforge:
![mapsforge2](https://user-images.githubusercontent.com/5493128/204105664-9413deb3-a2c2-4ade-88ba-bfa187d66380.jpg)

VTM:
![vtm2](https://user-images.githubusercontent.com/5493128/204105670-00b9d98b-0a87-469c-bdc0-522bd8cf457b.jpg)

**Comment by devemux86** [comment]
For reference in [XmlThemeBuilder.createLine](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/theme/XmlThemeBuilder.java) there is a section to create stipple with texture
from the line symbol instruction.

**Comment by devemux86** [comment]
The `<line src` rule does not seem to be parsed, so the default (black) color is used.

**Comment by devemux86** [comment]
[Cruiser 3.0.3](https://wiki.openstreetmap.org/wiki/Cruiser) is available with the latest VTM library.
Please try it and see if now rendering works properly
